(()=>{'use strict';
const IMG={head:'https://imgur.com/34KkHrB.png',tail:'https://imgur.com/yshLPnQ.png',burn:'https://imgur.com/L4bRd44.png',bleed:'https://imgur.com/mp9fbme.png',tremor:'https://imgur.com/fuDGjpn.png',sinking:'https://imgur.com/ZnulGzZ.png',poise:'https://imgur.com/KFEmJB5.png',stagger:'https://imgur.com/I56BWDC.png',slash:'https://imgur.com/Akf25L5.png',pierce:'https://imgur.com/slcQlpc.png'};
const BASE={ally:{hp:176,maxHp:176,sp:0,status:{},thresholds:[70,40,20],used:[],stage:0},enemy:{hp:158,maxHp:158,sp:0,status:{},thresholds:[70,40,20],used:[],stage:0}};
let S,lessonIndex=0,stepIndex=0,busy=false;
const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o)),wait=ms=>new Promise(r=>setTimeout(r,ms)),pct=u=>u.hp/u.maxHp*100;
function headsChance(u){return Math.max(5,Math.min(95,50+(Number(u.sp)||0)))}
function status(u,id){return u.status[id]||null}
function apply(u,id,p=0,c=0,type='negative'){u.status[id]={id,potency:p,count:c,type}}
function consume(u,id,n=1){const x=status(u,id);if(!x)return;x.count=Math.max(0,(x.count||0)-n);if(!x.count)delete u.status[id]}
function clearTransient(){['event','ally-skill','enemy-skill','coin-stage','calc','clash-center','trigger'].forEach(id=>{const e=$(id);e.className=id==='event'?'event-banner':id.includes('skill')?`skill-card ${id==='ally-skill'?'allycard':'enemycard'}`:id==='coin-stage'?'coin-stage':id==='calc'?'calc':id==='clash-center'?'clash-center':'trigger-beam';e.innerHTML=''});document.querySelectorAll('.float').forEach(e=>e.remove());document.querySelectorAll('.stag,.stxt').forEach(e=>e.classList.remove('show'));document.querySelectorAll('.status').forEach(e=>e.classList.remove('pulse'))}
function resetState(){clearTransient();S=clone(BASE);render()}
function event(title,sub='',cls=''){const e=$('event');e.className=`event-banner show ${cls}`;e.innerHTML=`<b>${title}</b><span>${sub}</span>`}
function caption(html){$('caption').innerHTML=html}
function showTrigger(text){const e=$('trigger');e.textContent=text;e.className='trigger-beam show'}
function calc(text){const e=$('calc');e.innerHTML=text;e.className='calc show'}
function skill(side,{name,base,coinPower,coins,trigger=''}){const e=$(side==='ally'?'ally-skill':'enemy-skill');e.innerHTML=`<h4>${name}</h4><div class="skill-meta"><span>Skill</span><span>${coins} Coin${coins===1?'':'s'}</span></div><div class="skill-power"><strong>${base}</strong><span>${coinPower>=0?'+':''}${coinPower}</span></div><div class="coin-stock">${Array.from({length:coins},()=>'<i class="coin-dot"></i>').join('')}</div>${trigger?`<div class="trigger-chip">${trigger}</div>`:''}`;e.classList.add('show');return e}
function markLostCoin(side,index=0){const card=$(side==='ally'?'ally-skill':'enemy-skill'),coins=[...card.querySelectorAll('.coin-dot')];if(coins[index])coins[index].classList.add('lost')}
function showCoins(results,label='COIN FLIP'){const e=$('coin-stage');e.innerHTML=`<span class="coin-label">${label}</span>`+results.map((r,i)=>`<i class="coin ${r==='spin'?'spin':''}" data-i="${i}"><img src="${r==='head'?IMG.head:IMG.tail}" alt="${r}"></i>`).join('');e.classList.add('show')}
function pulseStatus(side,id){requestAnimationFrame(()=>{const e=document.querySelector(`#${side} .status[data-id="${id}"]`);if(e){e.classList.remove('pulse');void e.offsetWidth;e.classList.add('pulse')}})}
function float(side,value,{icon=null,kind=''}={}){const h=$(side),e=document.createElement('div');e.className=`float ${kind}`;e.innerHTML=`<span>${value}</span>${icon?`<img src="${icon}" alt="">`:''}`;h.appendChild(e);setTimeout(()=>e.remove(),1100)}
function flash(side,selector){const e=document.querySelector(`#${side} ${selector}`);if(!e)return;e.classList.remove('flash');void e.offsetWidth;e.classList.add('flash')}
function stagger(u,side,i){if(u.used.includes(i))return;u.used.push(i);u.stage=Math.max(u.stage,i+1);renderUnit(side,u);const h=$(side),a=h.querySelector('.stag'),t=h.querySelector('.stxt');a.classList.remove('show');t.classList.remove('show');void h.offsetWidth;a.classList.add('show');t.classList.add('show')}
function setHP(u,side,v,{cross=true}={}){const old=pct(u);u.hp=Math.max(0,Math.min(u.maxHp,v));const now=pct(u);if(cross&&now<old)u.thresholds.forEach((t,i)=>{if(old>t&&now<=t&&!u.used.includes(i))stagger(u,side,i)});renderUnit(side,u)}
function damage(u,side,a,{icon=IMG.slash,fixed=false,cross=true,critical=false}={}){const d=Math.max(1,Math.floor(a*(critical?1.2:1)));float(side,d,{icon,kind:critical?'critdmg':fixed?'statusdmg':''});setHP(u,side,u.hp-d,{cross:cross&&!fixed});return d}
function setSP(u,side,v){u.sp=Math.max(-45,Math.min(45,v));renderUnit(side,u);flash(side,'.sp')}
function statuses(side,u){document.querySelector(`#${side} .statuses`).innerHTML=Object.values(u.status).map(x=>`<div class="status ${x.type==='positive'?'pos':''}" data-id="${x.id}"><span>${x.potency||''}</span><img src="${IMG[x.id]}" alt="${x.id}"><span>${x.count||''}</span></div>`).join('')}
function renderUnit(side,u){const h=$(side);h.querySelector('.hpfill').style.width=`${pct(u)}%`;h.querySelector('.hpnum').textContent=Math.round(u.hp);h.querySelector('.sp').textContent=Math.round(u.sp);h.querySelector('.spchance').textContent=`Heads ${headsChance(u)}%`;h.querySelectorAll('.thr').forEach((e,i)=>{e.style.left=`${u.thresholds[i]}%`;e.classList.toggle('used',u.used.includes(i))});statuses(side,u)}
function render(){renderUnit('ally',S.ally);renderUnit('enemy',S.enemy)}
function burnTurnEnd(){const x=status(S.enemy,'burn');if(!x)return;damage(S.enemy,'enemy',x.potency,{icon:IMG.burn,fixed:true,cross:false});consume(S.enemy,'burn');render();pulseStatus('enemy','burn')}
function bleedCoinFlip(){const x=status(S.ally,'bleed');if(!x)return;damage(S.ally,'ally',x.potency,{icon:IMG.bleed,fixed:true,cross:false});consume(S.ally,'bleed');render();pulseStatus('ally','bleed')}
function sinkingOnHit(){const x=status(S.enemy,'sinking');if(!x)return;setSP(S.enemy,'enemy',S.enemy.sp-x.potency);consume(S.enemy,'sinking');render();pulseStatus('enemy','sinking')}
function tremorBurst(){const x=status(S.enemy,'tremor');if(!x)return;const add=x.potency/S.enemy.maxHp*100,cur=pct(S.enemy);S.enemy.thresholds=S.enemy.thresholds.map((t,i)=>{if(S.enemy.used.includes(i))return t;const n=Math.min(100,t+add);if(cur>t&&cur<=n)stagger(S.enemy,'enemy',i);return n});consume(S.enemy,'tremor');render();pulseStatus('enemy','tremor');flash('enemy','.hpbar')}
function critHit(){const d=damage(S.enemy,'enemy',20,{critical:true,icon:IMG.slash});consume(S.ally,'poise');render();pulseStatus('ally','poise');return d}
const lessons=[
{id:'coin',group:'fund',icon:'C',name:'Coin',es:'Moneda',type:'Fundamento',plain:'Una Coin es una tirada dentro de una Skill. Puede resolver Heads o Tails.',why:'En el motor, SP cambia la probabilidad de Heads. En una Skill de Coin positiva, cada Heads suma Coin Power al Power de la tirada.',terms:[['Base Power','El valor inicial de la Skill.'],['Coin Power','Lo que añade cada Heads en una Skill positiva.'],['Heads / Tails','El resultado de la Coin; no son “acierto/fallo” por sí solos.']],steps:[['Skill preparada','Mira una Skill de ejemplo: <strong>Base 5 · Coin Power +3 · 2 Coins</strong>.',()=>{skill('ally',{name:'Training Cut',base:5,coinPower:3,coins:2});event('SKILL','Base 5 · Coin Power +3')}],['Coin 1 gira','La primera Coin se lanza. La animación te dice que <strong>todavía no está resuelta</strong>.',async()=>{event('COIN FLIP','La Coin está resolviendo','info');showCoins(['spin'],'COIN 1');await wait(700)}],['Heads suma Power','La Coin termina en <strong>Heads</strong>: 5 + 3 = 8 para esta lectura de Power.',()=>{showCoins(['head'],'COIN 1');calc('5 BASE + 3 HEADS = <b>8 POWER</b>');event('HEADS','Coin Power aplicado','info')}]]},
{id:'sp',group:'fund',icon:'SP',name:'SP',es:'Sanity',type:'Fundamento',plain:'SP no es HP. Cambia directamente la probabilidad de que tus Coins salgan Heads.',why:'El alpha calcula Heads % = 50 + SP, limitado entre 5% y 95%.',terms:[['0 SP','50% Heads.'],['+25 SP','75% Heads.'],['−30 SP','20% Heads.']],steps:[['Punto neutro','Con <strong>0 SP</strong>, la unidad tiene 50% de Heads. Mira el texto bajo el orbe azul.',()=>{event('SP','0 SP → Heads 50%','info');flash('ally','.sp')}],['SP positivo','Subimos Don a <strong>+25 SP</strong>. La probabilidad pasa a 75%.',()=>{setSP(S.ally,'ally',25);event('SP +25','Heads 75%','info');calc('50 + 25 = <b>75% HEADS</b>')}],['SP negativo','Ahora baja a <strong>−30 SP</strong>. La probabilidad queda en 20%.',()=>{setSP(S.ally,'ally',-30);event('SP −30','Heads 20%','info');calc('50 − 30 = <b>20% HEADS</b>')}]]},
{id:'clash',group:'fund',icon:'VS',name:'Clash',es:'Choque',type:'Fundamento',plain:'Un Clash ocurre cuando dos Skills se enfrentan. Ambas tiran Power; el lado con menor Power pierde una Coin.',why:'Si empatan, el Clash se repite sin perder Coin. Cuando un lado queda sin Coins, pierde el Clash; el ganador conserva sus Coins para golpear y gana SP.',terms:[['Clash Count','Cuántas rondas de Clash ocurrieron.'],['Perder Coin','El perdedor de una ronda elimina una Coin de su Skill.'],['Después del Clash','Las Coins restantes del ganador pasan a la secuencia de Hits.']],steps:[['Dos Skills chocan','Don entra con <strong>2 Coins</strong>; el Dummy con <strong>2 Coins</strong>.',()=>{skill('ally',{name:'Galloping Thrust',base:4,coinPower:3,coins:2});skill('enemy',{name:'Training Guard',base:4,coinPower:2,coins:2});$('clash-center').innerHTML='1<small>CLASH COUNT</small>';$('clash-center').classList.add('show');event('CLASH','Dos Skills compiten')}],['Se compara Power','Don resuelve <strong>10</strong> y Dummy <strong>6</strong>. Dummy pierde 1 Coin.',async()=>{showCoins(['head','head'],'DON 10');calc('DON 10  >  DUMMY 6');event('CLASH WIN','Dummy pierde 1 Coin');await wait(350);markLostCoin('enemy',0)}],['Se termina el Clash','Otra ronda deja al Dummy sin Coins. Don gana; sus Coins restantes pasan a Hits y recibe SP del Clash.',()=>{markLostCoin('enemy',1);setSP(S.ally,'ally',12);event('CLASH RESUELTO','Ganador → Hits restantes + SP');showTrigger('[CLASH WIN]');caption('<b>Clash no es un Hit.</b> Primero decide quién conserva Coins; después llegan los ataques.')}]]},
{id:'onhit',group:'fund',icon:'HIT',name:'On Hit',es:'Al golpear',type:'Trigger',plain:'[On Hit] ocurre después de que una Coin realmente conecta y hace su daño.',why:'El alpha resuelve el daño del Hit, después procesa estados reactivos existentes y luego aplica los efectos [On Hit] de esa Coin.',terms:[['Hit','La Coin conectó con el objetivo.'],['[On Hit]','Trigger que se ejecuta después del daño de ese Hit.'],['No es Clash','Un Clash puede ocurrir antes; [On Hit] pertenece a la fase de golpes.']],steps:[['La Coin va a golpear','Mostramos una Skill con un efecto explícito: <strong>[On Hit] Inflict Sinking 1/1</strong>.',()=>{skill('ally',{name:'Training Formula',base:4,coinPower:2,coins:1,trigger:'[On Hit] Inflict Sinking 1 / 1'});event('HIT SEQUENCE','El Clash ya terminó')}],['Primero entra el daño','La Coin conecta y quita <strong>7 HP</strong>. Todavía no mostramos el estado.',async()=>{event('HIT','Daño de la Coin');damage(S.enemy,'enemy',7,{icon:IMG.pierce});await wait(450)}],['Después dispara On Hit','Ahora aparece el trigger <strong>[On Hit]</strong> y recién entonces se aplica Sinking.',()=>{showTrigger('[ON HIT]');apply(S.enemy,'sinking',1,1);render();pulseStatus('enemy','sinking');event('ON HIT','Efecto de la Coin ejecutado','info')}]]},
{id:'stagger',group:'fund',icon:'ST',name:'Stagger Threshold',es:'Umbral de Tambaleo',type:'Fundamento',plain:'Las líneas blancas del HP son Stagger Thresholds: porcentajes de HP máximo que se activan al cruzarlos hacia abajo.',why:'El Dummy comienza con 70% / 40% / 20%. Una vez cruzado un Threshold, ese marcador queda consumido.',terms:[['70% / 40% / 20%','Porcentajes de Max HP, no daño fijo.'],['Cruzar','Estar arriba y caer hasta o por debajo del Threshold.'],['Stagger','El motor activa la etapa correspondiente y consume ese Threshold.']],setup:()=>setHP(S.enemy,'enemy',120,{cross:false}),steps:[['Mira las líneas','Dummy está en <strong>120 / 158 HP</strong>. El primer Threshold es 70% = 110.6 HP.',()=>{event('STAGGER THRESHOLD','Línea blanca = 70% Max HP');flash('enemy','.hpbar');calc('158 × 70% = <b>110.6 HP</b>')}],['El Hit cruza 70%','Un Hit de 20 baja a Dummy de 120 a 100 HP, cruzando el primer Threshold.',async()=>{event('HIT','120 → 100 HP');damage(S.enemy,'enemy',20,{icon:IMG.slash});await wait(550)}],['Stagger se activa','El Threshold se consume y aparece la UI de <strong>STAGGER</strong>. Al cambiar de lección o Reiniciar, esta UI debe desaparecer.',()=>{event('STAGGER','Threshold 70% consumido','danger');caption('<b>Stagger es consecuencia de cruzar la línea.</b> La línea blanca te deja anticiparlo antes del Hit.')}]]},
{id:'burn',group:'status',icon:IMG.burn,name:'Burn',es:'Quemadura',type:'Estado negativo',plain:'Burn no necesita una Coin ni un Hit para hacer su daño: se activa en Turn End.',why:'Potency determina el daño fijo; después pierde 1 Count.',terms:[['Potency','Daño fijo que hará el trigger.'],['Count','Cuántas activaciones quedan.'],['Turn End','Momento del turno donde Burn se resuelve.']],steps:[['Aplica Burn','Dummy recibe <strong>Burn 12 / 3</strong>. No pierde HP inmediatamente.',()=>{apply(S.enemy,'burn',12,3);render();pulseStatus('enemy','burn');event('STATUS APPLIED','Burn 12 / 3')}],['Llega Turn End','El motor entra al evento <strong>TURN END</strong>. Esto es lo que dispara Burn.',()=>{event('TURN END','Burn escucha este timing','danger');showTrigger('TURN END → BURN')}],['Burn hace daño','Burn inflige <strong>12 daño fijo</strong>; Count baja de 3 a 2.',async()=>{burnTurnEnd();await wait(350);event('BURN','12 Fixed Damage · Count −1','danger')}]]},
{id:'bleed',group:'status',icon:IMG.bleed,name:'Bleed',es:'Sangrado',type:'Estado negativo',plain:'Bleed daña a la unidad que está lanzando una Coin de ataque.',why:'En el alpha, Bleed se dispara cuando una Coin de ataque se resuelve. Observation/Guard no lo consumen. El daño es fijo y no cruza Stagger Thresholds.',terms:[['Quién recibe el daño','La unidad que TIENE Bleed y lanza la Coin.'],['Coin de ataque','El trigger ocurre al resolver esa Coin.'],['No es daño del Hit','Bleed puede dañarte antes de que tu Skill golpee al objetivo.']],steps:[['Don recibe Bleed','Para verlo claro, ponemos <strong>Bleed 8 / 3</strong> en Don, no en el Dummy.',()=>{apply(S.ally,'bleed',8,3);render();pulseStatus('ally','bleed');event('STATUS APPLIED','Don: Bleed 8 / 3')}],['Don usa una Coin','Don inicia una Skill de ataque. La Coin gira; todavía no ha golpeado al Dummy.',async()=>{skill('ally',{name:'Training Slash',base:5,coinPower:3,coins:1});event('COIN FLIP','Bleed escucha este evento','info');showCoins(['spin'],'DON COIN');await wait(700)}],['La Coin se resuelve','Antes del Hit, Bleed quita <strong>8 HP a Don</strong> y Count baja a 2. Después la Skill puede continuar hacia el Dummy.',async()=>{showCoins(['head'],'HEADS');showTrigger('COIN RESOLVED → BLEED');bleedCoinFlip();event('BLEED','8 Fixed Damage a Don · Count −1','danger');await wait(700);damage(S.enemy,'enemy',10,{icon:IMG.slash});caption('<b>Ahora se ve la diferencia:</b> rojo + icono Bleed en Don = estado; 10 + Slash en Dummy = Hit de la Skill.')}]]},
{id:'sinking',group:'status',icon:IMG.sinking,name:'Sinking',es:'Hundimiento',type:'Estado negativo',plain:'Sinking reacciona cuando la unidad recibe un Hit y, si tiene SP, daña su SP en vez de su HP.',why:'Los estados reactivos existentes se procesan después del daño del Hit. Sinking consume 1 Count.',terms:[['SP Damage','Cambia Sanity y por tanto Heads %.'],['On getting Hit','Primero entra el Hit; luego Sinking reacciona.'],['Sin SP','El alpha usa daño Gloom normal para unidades sin SP.']],setup:()=>{S.enemy.sp=25;render()},steps:[['Prepara Sinking','Dummy tiene <strong>25 SP</strong> y recibe <strong>Sinking 10 / 2</strong>. Heads está en 75%.',()=>{apply(S.enemy,'sinking',10,2);render();pulseStatus('enemy','sinking');event('STATUS APPLIED','Sinking 10 / 2');flash('enemy','.sp')}],['La Skill conecta','Un Hit de entrenamiento quita <strong>6 HP</strong>. Esta es la parte de daño normal.',async()=>{skill('ally',{name:'Training Pierce',base:4,coinPower:2,coins:1});event('HIT','Daño normal primero');damage(S.enemy,'enemy',6,{icon:IMG.pierce});await wait(500)}],['Sinking reacciona','Después del Hit, Sinking quita <strong>10 SP</strong>: 25 → 15. Heads baja de 75% a 65%. Count baja a 1.',()=>{showTrigger('GETTING HIT → SINKING');sinkingOnHit();event('SINKING','SP 25 → 15 · Heads 75% → 65%','info');calc('SP 15 → <b>65% HEADS</b>')}]]},
{id:'tremor',group:'status',icon:IMG.tremor,name:'Tremor',es:'Temblor',type:'Estado negativo',plain:'Tremor guarda Potency para mover Stagger Thresholds cuando ocurre Tremor Burst.',why:'Tremor Burst eleva los Thresholds restantes por Potency / Max HP y consume 1 Count. Puede provocar Stagger sin quitar HP.',terms:[['No daña HP','El Burst mueve Thresholds.'],['Potency','Cuántos HP-equivalentes desplaza el Threshold.'],['Burst','Trigger separado; acumular Tremor por sí solo no mueve líneas.']],setup:()=>setHP(S.enemy,'enemy',130,{cross:false}),steps:[['Acumula Tremor','Dummy recibe <strong>Tremor 25 / 2</strong>. HP y Thresholds todavía no cambian.',()=>{apply(S.enemy,'tremor',25,2);render();pulseStatus('enemy','tremor');event('STATUS APPLIED','Tremor 25 / 2')}],['Se ejecuta Tremor Burst','Ahora sí aparece el evento <strong>TREMOR BURST</strong>. Mira las líneas blancas, no el número de HP.',()=>{event('TREMOR BURST','Mueve Stagger Thresholds');showTrigger('TREMOR BURST');calc('25 / 158 = <b>+15.8 puntos de Threshold</b>')}],['Las líneas suben','Los Thresholds restantes suben. Si uno alcanza el HP actual, puede activar Stagger sin daño.',async()=>{const hp=S.enemy.hp;tremorBurst();await wait(450);event('THRESHOLD MOVED',`HP sigue en ${hp}`);caption('<b>Tremor se lee mirando las líneas blancas.</b> Si miras solo HP, parece que “no hizo nada”.')}]]},
{id:'poise',group:'status',icon:IMG.poise,name:'Poise',es:'Aplomo',type:'Estado positivo',plain:'Poise aporta probabilidad de crítico; cuando el ataque crita, el daño usa ×1.2 y Poise consume Count.',why:'El alpha marca el resultado como critical dentro del cálculo de daño. La demostración fuerza el crítico para que el jugador aprenda a reconocerlo.',terms:[['Crit Chance','Potency de Poise × 5% en esta versión del motor.'],['Critical','Multiplicador de daño ×1.2.'],['Count','Se consume 1 cuando ocurre el crítico, salvo la excepción de Paralyzed auto-crit.']],steps:[['Aplica Poise','Don recibe <strong>Poise 10 / 3</strong>: 50% Crit Chance.',()=>{apply(S.ally,'poise',10,3,'positive');render();pulseStatus('ally','poise');event('STATUS APPLIED','Poise 10 / 3');calc('10 Potency × 5% = <b>50% CRIT</b>')}],['La Skill va a golpear','Mostramos un ataque base de <strong>20 daño</strong>. La Coin se resuelve antes del Hit.',async()=>{skill('ally',{name:'Training Crit',base:5,coinPower:3,coins:1,trigger:'Poise can Critical'});event('COIN FLIP','Resolviendo ataque','info');showCoins(['spin'],'DON COIN');await wait(700);showCoins(['head'],'HEADS')}],['CRITICAL es distinto','Forzamos el resultado crítico: aparece <strong>CRITICAL ×1.2</strong> y el daño 20 se convierte en 24. Poise Count baja 3 → 2.',async()=>{event('CRITICAL ×1.2','Poise convirtió el Hit en crítico','crit');showTrigger('ON CRIT');calc('20 × 1.2 = <b>24 DAMAGE</b>');const d=critHit();await wait(450);caption(`<b>Señales visuales del crítico:</b> banner dorado CRITICAL, daño dorado ${d}, fórmula ×1.2 y Count de Poise reducido.`)}]]}
];
function current(){return lessons[lessonIndex]}
function snapText(){const L=current();return L.steps.map((s,i)=>`<div class="row${i<stepIndex?' done':i===stepIndex?' cur':''}"><b>${String(i+1).padStart(2,'0')}</b><span>${s[0]}</span></div>`).join('')}
function drawTabs(){const draw=(g,id)=>{$(id).innerHTML=lessons.map((L,i)=>({L,i})).filter(x=>x.L.group===g).map(({L,i})=>`<button class="tab${i===lessonIndex?' on':''}" data-i="${i}" title="${L.name} (${L.es})">${typeof L.icon==='string'&&L.icon.startsWith('http')?`<img src="${L.icon}" alt="">`:`${L.icon}`}<span class="tiny">${i+1}</span></button>`).join('');$(id).querySelectorAll('.tab').forEach(b=>b.onclick=()=>load(+b.dataset.i))};draw('fund','fund-tabs');draw('status','status-tabs')}
function drawLesson(){const L=current(),icon=$('concept-icon');icon.innerHTML=L.icon.startsWith?.('http')?`<img src="${L.icon}" alt="">`:L.icon;$('title').textContent=`${L.name} (${L.es})`;$('type').textContent=L.type;$('plain').textContent=L.plain;$('why').textContent=L.why;$('terms').innerHTML=(L.terms||[]).map(([a,b])=>`<div class="term"><b>${a}</b><span>${b}</span></div>`).join('');$('log').innerHTML=snapText();drawStep();drawTabs()}
function drawStep(){const L=current(),done=stepIndex>=L.steps.length,x=L.steps[Math.min(stepIndex,L.steps.length-1)];$('steph').textContent=done?'Simulación completada':x[0];$('stepc').innerHTML=done?'Terminaste esta lección. Reinicia o elige otra pestaña.':`${x[1]}<div class="hint">Pulsa “Siguiente paso” y mira el campo de batalla.</div>`;$('next').disabled=busy||done;$('play').disabled=busy||done}
function load(i){if(busy)return;lessonIndex=i;stepIndex=0;resetState();const L=current();L.setup?.();drawLesson();caption(`<b>${L.name}:</b> ${L.plain}`)}
async function next(){if(busy)return;const L=current();if(stepIndex>=L.steps.length)return;busy=true;drawStep();const x=L.steps[stepIndex];caption(`<b>${x[0]}:</b> ${x[1].replace(/<[^>]+>/g,'')}`);await x[2]();stepIndex++;$('log').innerHTML=snapText();busy=false;drawStep();if(stepIndex>=L.steps.length)caption(`<b>Resultado:</b> ${L.plain}`)}
async function play(){if(busy)return;busy=true;drawStep();const L=current();while(stepIndex<L.steps.length){const x=L.steps[stepIndex];caption(`<b>${x[0]}:</b> ${x[1].replace(/<[^>]+>/g,'')}`);await x[2]();stepIndex++;$('log').innerHTML=snapText();await wait(900)}busy=false;drawStep();caption(`<b>Resultado:</b> ${L.plain}`)}
$('reset').onclick=()=>load(lessonIndex);$('next').onclick=next;$('play').onclick=play;load(0);
})();
