(function (global) {
  "use strict";
  if (global.LuminousInventoryHudV2) return;
  const doc = global.document;
  if (!doc) return;
  const state={playerId:null,db:null,unit:null,snapshot:null,unsubscribeInventory:null,unsubscribeStash:null,stashUnlocked:false,selected:null,selectedContainer:"active",ready:false};
  const qualityNames={1:"LOW",2:"STANDARD",3:"GOOD",4:"FINE",5:"EXCEPTIONAL"};
  const slotSpecs=[
    {id:"mainHand",label:"MAIN HAND",hint:"WEAPON",className:"inv2-eq-main"},
    {id:"offHand",label:"OFF HAND",hint:"WEAPON / SHIELD",className:"inv2-eq-off"},
    {id:"armor",label:"ARMOR",hint:"BODY",className:"inv2-eq-armor"},
    {id:"shield",label:"SHIELD",hint:"DEFENSE",className:"inv2-eq-shield"},
    {id:"accessory0",label:"ACCESSORY A",hint:"ACCESSORY",className:"inv2-eq-acc-a"},
    {id:"accessory1",label:"ACCESSORY B",hint:"ACCESSORY",className:"inv2-eq-acc-b"}
  ];
  const runtime=()=>global.LuminousItemRuntime||global.LuminousItemInventoryRuntime||null;
  const persistence=()=>global.LuminousItemPersistenceRuntime||null;
  const bridge=()=>global.LuminousItemEquipmentBridge||null;
  const workshop=()=>global.LuminousWorkshopRuntime||null;
  function resolveDb(){try{if(typeof db!=="undefined"&&db?.ref)return db}catch(_){}try{if(global.firebase?.database)return global.firebase.database()}catch(_){}return null}
  function resolvePlayerId(){try{if(typeof playerId!=="undefined"&&playerId)return String(playerId)}catch(_){}try{const stored=global.localStorage?.getItem("playerId");if(stored)return stored}catch(_){}return null}
  function itemId(item={}){return String(item.instanceId||item.instance_id||runtime()?.itemId?.(item)||item.key||item.definitionId||item.id||"").trim()}
  function itemName(item={}){const resolved=runtime()?.resolveItem?.(item)||item;return String(resolved?.displayName||resolved?.nombre||resolved?.name||item.definitionId||"ITEM").trim()}
  function itemCategory(item={}){return String(runtime()?.categoryOf?.(item)||item.tipo_categoria||item.category||item.itemType||item.type||"item")}
  function entries(container){return Object.entries(container&&typeof container==="object"?container:{})}
  function findByKey(container,key){if(!container||!key)return null;if(container[key])return container[key];const wanted=String(key);for(const [entryKey,item] of entries(container)){if(!item)continue;if([entryKey,itemId(item),item.instanceId,item.key,item.definitionId,item.id].map(String).includes(wanted))return item}return null}
  function selectedItem(){if(!state.selected)return null;if(state.selectedContainer==="equipment")return state.selected.item||null;const source=state.selectedContainer==="stash"?state.unit?.inventario_stash:state.unit?.inventario_activo;return findByKey(source,state.selected.key)||state.selected.item||null}
  function manufacturerName(item={}){if(!item.manufacturerId)return "—";const ws=workshop()?.getWorkshop?.(item.manufacturerId);return String(ws?.workshopName||ws?.name||item.manufacturerName||item.manufacturerId||"—").replace(/\s+Workshop$/i,"")}
  function productLineName(item={}){if(item.productLineName)return item.productLineName;const ws=item.manufacturerId?workshop()?.getWorkshop?.(item.manufacturerId):null;const line=(ws?.productLines||[]).find(entry=>String(entry?.productLineId||entry?.id||"")===String(item.productLineId||item.product_line_id||""));return line?.productLineName||line?.name||item.productLineId||"—"}
  function installedModules(item={}){const raw=item.installedModules||item.installedModuleIds||item.installed_module_ids||[];return Array.isArray(raw)?raw:Object.values(raw||{})}
  function escapeHtml(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}

  function ensureActiveLayout(){
    const activePane=doc.getElementById("inv-active"),grid=doc.getElementById("inv-active-grid");
    if(!activePane||!grid)return false;
    if(activePane.querySelector(".inventory-v2-active-stack"))return true;
    const stack=doc.createElement("div");stack.className="inventory-v2-active-stack";
    const equipment=doc.createElement("section");equipment.className="inventory-v2-equipment";
    equipment.innerHTML=`<header class="inventory-v2-equipment-header"><div><span>ANATOMY / EQUIPMENT MAP</span><strong>EQUIPPED LOADOUT</strong></div><div class="inventory-v2-sync" id="inventory-v2-sync-state">SYNC // WAITING</div></header><div class="inventory-v2-equipment-field"><div class="inventory-v2-body-silhouette" aria-hidden="true"></div>${slotSpecs.map(slot=>`<button type="button" class="inventory-v2-eq-slot ${slot.className}" data-equipment-slot="${slot.id}" aria-label="${slot.label}"><span class="inventory-v2-eq-label">${slot.label}</span><span class="inventory-v2-eq-name">EMPTY</span><span class="inventory-v2-eq-hint">${slot.hint}</span></button>`).join("")}<div class="inventory-v2-augment-summary" id="inventory-v2-augment-summary"><span>AUGMENTS</span><strong>NO INSTALLED AUGMENTS</strong></div></div>`;
    const inventory=doc.createElement("section");inventory.className="inventory-v2-carry";inventory.innerHTML=`<header class="inventory-v2-carry-header"><div><span>FIELD CARRY // QUICK ACCESS</span><strong>ACTIVE INVENTORY</strong></div><b id="inventory-v2-carry-count">0 / 10</b></header><div class="inventory-v2-grid-host"></div>`;
    inventory.querySelector(".inventory-v2-grid-host").appendChild(grid);stack.appendChild(equipment);stack.appendChild(inventory);activePane.appendChild(stack);
    equipment.addEventListener("click",onEquipmentClick);equipment.addEventListener("dragover",onEquipmentDragOver);equipment.addEventListener("dragleave",onEquipmentDragLeave);equipment.addEventListener("drop",onEquipmentDrop);return true;
  }
  function ensureDetailExtensions(){const card=doc.getElementById("item-detail-card");if(!card||card.querySelector(".inventory-v2-detail-extra"))return;const extra=doc.createElement("div");extra.className="inventory-v2-detail-extra";extra.innerHTML=`<div class="inventory-v2-detail-grid"><div><span>QUALITY</span><b data-v2-detail="quality">—</b></div><div><span>CONDITION</span><b data-v2-detail="condition">—</b></div><div><span>MANUFACTURER</span><b data-v2-detail="manufacturer">—</b></div><div><span>PRODUCT LINE</span><b data-v2-detail="product-line">—</b></div><div><span>SERIAL</span><b data-v2-detail="serial">—</b></div><div><span>EQUIPMENT</span><b data-v2-detail="equipment">—</b></div></div><div class="inventory-v2-modules"><span>MODULES / STRUCTURAL TECH</span><div data-v2-detail="modules">NO INSTALLED MODULES</div></div><div class="inventory-v2-actions" id="inventory-v2-actions"></div><div class="inventory-v2-action-status" id="inventory-v2-action-status"></div>`;card.appendChild(extra)}
  function rethemeTabs(){const modal=doc.getElementById("inventory-modal");if(!modal)return;modal.classList.add("inventory-v2-ready");const active=modal.querySelector('.inv-tab-btn[data-tab="inv-active"]'),stash=modal.querySelector('.inv-tab-btn[data-tab="inv-stash"]'),synth=modal.querySelector('.inv-tab-btn[data-tab="inv-sintesis"]');if(active)active.textContent="LOADOUT";if(stash)stash.textContent="STASH / ALIJO";if(synth)synth.textContent="SYNTHESIS"}
  function slotData(slotId){return bridge()?.getSlotItem?.(state.unit||{},slotId)||null}
  function renderEquipment(){if(!state.unit)return;const equipment=doc.querySelector(".inventory-v2-equipment");if(!equipment)return;const activeSelected=state.selectedContainer==="active"?selectedItem():null;const compatible=activeSelected?(bridge()?.compatibleSlots?.(activeSelected)||[]):[];equipment.querySelectorAll("[data-equipment-slot]").forEach(button=>{const slotId=button.dataset.equipmentSlot,item=slotData(slotId),name=button.querySelector(".inventory-v2-eq-name"),hint=button.querySelector(".inventory-v2-eq-hint");button.classList.toggle("is-filled",Boolean(item));button.classList.toggle("is-compatible",Boolean(activeSelected)&&compatible.includes(slotId));button.classList.toggle("is-selected",Boolean(item)&&state.selectedContainer==="equipment"&&itemId(item)===itemId(selectedItem()));if(item){name.textContent=itemName(item);hint.textContent=`${item.tier?`TIER ${item.tier}`:itemCategory(item).toUpperCase()} // ${item.condition!=null?`${Math.round(Number(item.condition))}%`:"READY"}`;button.draggable=true}else{name.textContent="EMPTY";hint.textContent=compatible.includes(slotId)?"CLICK / DROP TO EQUIP":slotSpecs.find(entry=>entry.id===slotId)?.hint||"AVAILABLE";button.draggable=false}});const augments=bridge()?.equippedSlots?.(state.unit)?.augments||[],summary=doc.getElementById("inventory-v2-augment-summary");if(summary){const strong=summary.querySelector("strong");strong.textContent=augments.length?augments.slice(0,2).map(itemName).join(" // "):"NO INSTALLED AUGMENTS"}const sync=doc.getElementById("inventory-v2-sync-state");if(sync)sync.textContent=state.playerId?"SYNC // REALTIME":"SYNC // WAITING"}
  function renderCarryCount(){const count=entries(state.unit?.inventario_activo).filter(([,item])=>item&&Number(item.quantity??item.cantidad??1)>0).length;const el=doc.getElementById("inventory-v2-carry-count");if(el)el.textContent=`${String(count).padStart(2,"0")} / 10`}
  function decorateGrid(containerType){const grid=doc.getElementById(containerType==="stash"?"inv-stash-grid":"inv-active-grid");if(!grid||!state.unit)return;const source=containerType==="stash"?state.unit.inventario_stash:state.unit.inventario_activo;grid.querySelectorAll(".item-slot").forEach(slot=>{const key=slot.dataset.key,item=findByKey(source,key);slot.classList.remove("inventory-v2-equipped","inventory-v2-damaged","inventory-v2-stolen");slot.querySelector(".inventory-v2-item-state")?.remove();if(!item)return;const equippedSlot=bridge()?.itemEquippedSlot?.(state.unit,item),flags=[];if(equippedSlot){slot.classList.add("inventory-v2-equipped");flags.push("EQUIPPED")}if(Number(item.condition??100)<=50){slot.classList.add("inventory-v2-damaged");flags.push("DAMAGED")}if(item.stolen===true){slot.classList.add("inventory-v2-stolen");flags.push("STOLEN")}if(flags.length){const badge=doc.createElement("span");badge.className="inventory-v2-item-state";badge.textContent=flags.join(" / ");slot.appendChild(badge)}})}
  function renderDetail(){ensureDetailExtensions();const item=selectedItem(),card=doc.getElementById("item-detail-card");if(!card||!item)return;const resolved=runtime()?.resolveItem?.(item)||item,quality=Number(item.qualityTier??item.quality??2),condition=Number(item.condition??item.durability??100),max=Math.max(1,Number(item.conditionMax??item.maxCondition??100)),percent=Math.max(0,Math.min(100,Math.round(condition/max*100))),equippedSlot=bridge()?.itemEquippedSlot?.(state.unit,item);const set=(name,value)=>{const el=card.querySelector(`[data-v2-detail="${name}"]`);if(el)el.textContent=value};set("quality",`${qualityNames[quality]||`Q${quality}`} // Q${quality}`);const conditionState=runtime()?.getConditionState?.(item);set("condition",`${percent}% // ${String(conditionState?.state||conditionState||"SERVICEABLE").toUpperCase()}`);set("manufacturer",manufacturerName(item));set("product-line",productLineName(item));set("serial",item.productSerial||item.product_serial||item.instanceId||"—");set("equipment",equippedSlot?String(equippedSlot).toUpperCase():"NOT EQUIPPED");const moduleHost=card.querySelector('[data-v2-detail="modules"]');if(moduleHost){const modules=installedModules(item),tech=Array.isArray(item.signatureTechnologyIds)?item.signatureTechnologyIds:[],values=[...modules,...tech].filter(Boolean).map(entry=>typeof entry==="string"?entry:entry.name||entry.id||"MODULE");moduleHost.innerHTML=values.length?values.map(entry=>`<span>${escapeHtml(entry)}</span>`).join(""):"NO INSTALLED MODULES"}const title=doc.getElementById("detail-title");if(title&&resolved?.displayName)title.textContent=resolved.displayName;renderActions(item,equippedSlot)}
  function renderActions(item,equippedSlot){const host=doc.getElementById("inventory-v2-actions");if(!host)return;host.innerHTML="";const add=(label,action,className="",disabled=false)=>{const button=doc.createElement("button");button.type="button";button.className=`inventory-v2-action ${className}`.trim();button.textContent=label;button.disabled=disabled;button.addEventListener("click",action);host.appendChild(button);return button};if(state.selectedContainer==="equipment"){add("UNEQUIP",()=>unequipSelected(),"primary");add("RETURN TO ACTIVE",()=>selectActiveCopy(item));return}if(state.selectedContainer==="stash"){add("CARRY / LLEVAR",()=>moveSelected("stash","active"),"primary",!state.stashUnlocked);return}const compatible=bridge()?.compatibleSlots?.(item)||[];if(equippedSlot)add("UNEQUIP",()=>unequipSelected(),"primary");else if(compatible.length)add("EQUIP",()=>equipSelectedAuto(),"primary");add("STORE / GUARDAR",()=>moveSelected("active","stash"),"",!state.stashUnlocked);const canUse=runtime()?.hasFunction?.(item,"use")||itemCategory(item)==="consumable";if(canUse)add("USE",()=>useSelected())}
  function showStatus(message,tone=""){const el=doc.getElementById("inventory-v2-action-status");if(!el)return;el.textContent=message||"";el.dataset.tone=tone}
  async function persistUnit(successMessage){if(!state.db||!state.playerId||!state.unit)return false;showStatus("SYNCING...","working");try{const result=await bridge()?.persist?.(state.db,state.playerId,state.unit);if(!result?.saved)throw new Error(result?.reason||"save_failed");showStatus(successMessage||"SYNCED","success");renderEquipment();renderCarryCount();decorateGrid("active");decorateGrid("stash");renderDetail();return true}catch(error){showStatus(`ERROR // ${error.message||error}`,"error");return false}}
  async function equipSelectedTo(slotId){const item=selectedItem();if(!item||state.selectedContainer!=="active"||!state.unit)return;const gate=bridge()?.canEquipTo?.(state.unit,item,slotId);if(!gate?.allowed){showStatus(`BLOCKED // ${String(gate?.reason||"INCOMPATIBLE").toUpperCase()}`,"error");return}const result=bridge().equipTo(state.unit,item,slotId);if(!result?.equipped){showStatus(`BLOCKED // ${String(result?.reason||"EQUIP FAILED").toUpperCase()}`,"error");return}state.selected={key:itemId(item),item};state.selectedContainer="equipment";await persistUnit(`EQUIPPED // ${String(slotId).toUpperCase()}`)}
  async function equipSelectedAuto(){const item=selectedItem();if(!item||!state.unit)return;const compatible=bridge()?.compatibleSlots?.(item)||[];if(!compatible.length){showStatus("ITEM NOT EQUIPPABLE","error");return}const preferred=compatible.find(slotId=>!bridge().getSlotItem(state.unit,slotId))||compatible[0];await equipSelectedTo(preferred)}
  async function unequipSelected(){const item=selectedItem();if(!item||!state.unit)return;const slotId=bridge()?.itemEquippedSlot?.(state.unit,item);if(!slotId){showStatus("ITEM IS NOT EQUIPPED","error");return}const result=bridge().unequipSlot(state.unit,slotId);if(!result?.unequipped){showStatus(`BLOCKED // ${String(result?.reason||"UNEQUIP FAILED").toUpperCase()}`,"error");return}state.selectedContainer="active";state.selected={key:itemId(item),item};await persistUnit(`UNEQUIPPED // ${String(slotId).toUpperCase()}`)}
  async function moveSelected(from,to){if(!state.unit)return;if((from==="stash"||to==="stash")&&!state.stashUnlocked){showStatus("STASH LOCKED BY DM","error");return}const item=selectedItem();if(!item)return;const id=itemId(item)||state.selected?.key,result=bridge()?.moveItem?.(state.unit,id,from,to);if(!result?.moved){showStatus(`BLOCKED // ${String(result?.reason||"MOVE FAILED").toUpperCase()}`,"error");return}state.selectedContainer=to;state.selected={key:id,item:null};await persistUnit(`${from.toUpperCase()} → ${to.toUpperCase()}`)}
  async function useSelected(){const item=selectedItem();if(!item||!state.unit||!runtime()?.useItem)return;const result=runtime().useItem(state.unit,item,{});if(!result?.used){showStatus(`BLOCKED // ${String(result?.reason||"USE FAILED").toUpperCase()}`,"error");return}const qty=Number(runtime()?.quantityOf?.(item)??item.quantity??item.cantidad??1);if(qty<=0){const source=state.selectedContainer==="stash"?state.unit.inventario_stash:state.unit.inventario_activo;for(const [key,entry] of entries(source))if(entry===item||itemId(entry)===itemId(item))delete source[key];state.selected=null}await persistUnit(`USED // ${itemName(item).toUpperCase()}`)}
  function selectActiveCopy(item){if(!item)return;state.selectedContainer="active";state.selected={key:itemId(item),item};const gridSlot=[...(doc.querySelectorAll("#inv-active-grid .item-slot")||[])].find(slot=>slot.dataset.key===itemId(item));gridSlot?.click?.();renderDetail();renderEquipment()}
  function onEquipmentClick(event){const slot=event.target.closest("[data-equipment-slot]");if(!slot||!state.unit)return;const slotId=slot.dataset.equipmentSlot,current=bridge()?.getSlotItem?.(state.unit,slotId);if(current){state.selectedContainer="equipment";state.selected={key:itemId(current),item:current};renderEquipment();renderDetail();return}if(state.selectedContainer==="active"&&selectedItem())equipSelectedTo(slotId)}
  function onEquipmentDragOver(event){const slot=event.target.closest("[data-equipment-slot]");if(!slot||!state.unit)return;const key=event.dataTransfer?.getData?.("text/plain")||state.selected?.key,item=findByKey(state.unit.inventario_activo,key);if(!item||!bridge()?.canEquipTo?.(state.unit,item,slot.dataset.equipmentSlot)?.allowed)return;event.preventDefault();slot.classList.add("is-drop-target")}
  function onEquipmentDragLeave(event){event.target.closest("[data-equipment-slot]")?.classList.remove("is-drop-target")}
  function onEquipmentDrop(event){const slot=event.target.closest("[data-equipment-slot]");if(!slot||!state.unit)return;event.preventDefault();slot.classList.remove("is-drop-target");const key=event.dataTransfer?.getData?.("text/plain"),item=findByKey(state.unit.inventario_activo,key);if(!item)return;state.selectedContainer="active";state.selected={key,item};equipSelectedTo(slot.dataset.equipmentSlot)}
  function bindGridSelection(){const activeGrid=doc.getElementById("inv-active-grid"),stashGrid=doc.getElementById("inv-stash-grid");activeGrid?.addEventListener("click",event=>{const slot=event.target.closest(".item-slot");if(!slot?.dataset?.key||!state.unit)return;const item=findByKey(state.unit.inventario_activo,slot.dataset.key);if(!item)return;state.selectedContainer="active";state.selected={key:slot.dataset.key,item};global.setTimeout(()=>{renderEquipment();renderDetail()},0)});stashGrid?.addEventListener("click",event=>{const slot=event.target.closest(".item-slot");if(!slot?.dataset?.key||!state.unit)return;const item=findByKey(state.unit.inventario_stash,slot.dataset.key);if(!item)return;state.selectedContainer="stash";state.selected={key:slot.dataset.key,item};global.setTimeout(renderDetail,0)});[activeGrid,stashGrid].filter(Boolean).forEach(grid=>{new MutationObserver(()=>{renderCarryCount();decorateGrid(grid.id==="inv-stash-grid"?"stash":"active")}).observe(grid,{childList:true,subtree:false})})}
  function applySnapshot(snapshot){const persist=persistence();if(!persist)return;const base={...(global.datosJugador&&typeof global.datosJugador==="object"?global.datosJugador:{}),inventario_activo:{},inventario_stash:{},equipment:{}};persist.applyInventoryState(base,snapshot||{});state.snapshot=snapshot;state.unit=base;renderEquipment();renderCarryCount();decorateGrid("active");decorateGrid("stash");if(state.selected)renderDetail()}
  function bindStashAccess(dbRef){state.unsubscribeStash?.();const ref=dbRef.ref("campaña/ajustes_globales/alijo_desbloqueado"),handler=snap=>{state.stashUnlocked=snap?.val?.()===true;doc.getElementById("inventory-modal")?.classList.toggle("inventory-v2-stash-locked",!state.stashUnlocked);renderDetail()};ref.on("value",handler);state.unsubscribeStash=()=>ref.off?.("value",handler)}
  function bindRealtime(){const pid=resolvePlayerId(),dbRef=resolveDb(),persist=persistence();if(!pid||!dbRef||!persist?.subscribePlayerInventory)return false;if(state.playerId===pid&&state.db===dbRef&&state.unsubscribeInventory)return true;state.unsubscribeInventory?.();state.unsubscribeStash?.();state.playerId=pid;state.db=dbRef;state.unsubscribeInventory=persist.subscribePlayerInventory(dbRef,pid,applySnapshot);bindStashAccess(dbRef);return true}
  function scheduleRealtimeBind(){if(bindRealtime())return;let attempts=0;const timer=global.setInterval(()=>{attempts+=1;if(bindRealtime()||attempts>=80)global.clearInterval(timer)},250)}
  function boot(){if(state.ready)return;const modal=doc.getElementById("inventory-modal");if(!modal||!doc.getElementById("inv-active-grid"))return;state.ready=true;rethemeTabs();ensureActiveLayout();ensureDetailExtensions();bindGridSelection();scheduleRealtimeBind();modal.addEventListener("click",event=>{const tab=event.target.closest(".inv-tab-btn");if(!tab)return;if(tab.dataset.tab==="inv-active"){state.selectedContainer="active";global.setTimeout(()=>{renderEquipment();decorateGrid("active")},0)}else if(tab.dataset.tab==="inv-stash"){state.selectedContainer="stash";global.setTimeout(()=>decorateGrid("stash"),0)}});global.addEventListener("beforeunload",()=>{state.unsubscribeInventory?.();state.unsubscribeStash?.()},{once:true})}
  if(doc.readyState==="loading")doc.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
  global.LuminousInventoryHudV2=Object.freeze({version:2,state,boot,ensureActiveLayout,renderEquipment,renderDetail,bindRealtime,equipSelectedTo,moveSelected,useSelected});
})(typeof window!=="undefined"?window:globalThis);
