from pathlib import Path

def rep(path, old, new, count=1):
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    if old not in text: raise SystemExit(f'missing block in {path}')
    p.write_text(text.replace(old, new, count), encoding='utf-8')

rep('js/trait-engine.js', 'const OPERATION_TYPES = Object.freeze(["modify", "resource", "apply_status", "remove_status", "heal_hp", "heal_sp", "gain_shield", "set_flag", "clear_flag", "log"]);', 'const OPERATION_TYPES = Object.freeze(["modify", "resource", "apply_status", "remove_status", "heal_hp", "heal_sp", "gain_shield", "set_flag", "clear_flag", "register_dm_effect", "log"]);')
rep('js/trait-engine.js', '    else if (type === "clear_flag") { const id = assertSafeKey(op.flagId || op.path, "Flag id"); delete env.state.flags[id]; out = Object.assign(base, { flagId: id, cleared: true }); }\n    else if (type === "log") out = Object.assign(base, { message: String(op.message || "") }); else throw new Error(`Unsupported trait operation type: ${op.type}`);', '''    else if (type === "clear_flag") { const id = assertSafeKey(op.flagId || op.path, "Flag id"); delete env.state.flags[id]; out = Object.assign(base, { flagId: id, cleared: true }); }\n    else if (type === "register_dm_effect") {\n      const target = env.runtime.target || env.runtime.defender || null;\n      const descriptor = { effectId: normalizeId(op.effectId || env.trait.id), name: String(op.name || env.trait.name || env.trait.id), durationHours: Math.max(0, num(op.durationHours ?? op.hours, 1)), sourceTraitId: env.trait.id, targetId: target?.id ?? target?.actorId ?? target?.characterId ?? null, targetName: target?.name ?? target?.nombre ?? target?.characterName ?? null, check: clone(op.check || {}), modifier: clone(op.modifier || {}), note: String(op.note || "") };\n      const registered = typeof env.runtime.registerDmEffect === "function" ? env.runtime.registerDmEffect(descriptor) : null;\n      out = Object.assign(base, { descriptor, registered: clone(registered) });\n    }\n    else if (type === "log") out = Object.assign(base, { message: String(op.message || "") }); else throw new Error(`Unsupported trait operation type: ${op.type}`);''')

rep('js/racial-trait-catalog.js', '''    yuan_ti_subtle_influence: {\n      schemaVersion: 1,\n      id: "yuan_ti_subtle_influence",\n      name: "Subtle Influence",\n      description: "Choose a creature and make the configured CHA Check; on pass, CHA Checks against that target reduce Threshold by 4 for the effect duration.",\n      source: raceSource("yuan_ti_pureblood"),\n      contexts: ["theatre"],\n      activation: { type: "manual", actionCost: "action", target: "creature" },\n      effects: [{ id: "yuan_ti_subtle_influence_request", contexts: ["theatre"], trigger: "on_use", conditions: [], operations: [{ type: "set_flag", flagId: "subtle_influence_check_requested", value: true }] }],\n      rules: [],\n    },''', '''    yuan_ti_subtle_influence: {\n      schemaVersion: 1,\n      id: "yuan_ti_subtle_influence",\n      name: "Subtle Influence",\n      description: "Choose a creature. For 1 hour, the DM is warned that Subtle Influence is active against that target. The DM decides whether it applies to a CHA Check and may grant +4 Check Power for that roll or disable the effect.",\n      source: raceSource("yuan_ti_pureblood"),\n      contexts: ["theatre"],\n      activation: { type: "manual", actionCost: "action", target: "creature", conditions: [{ path: "target", operator: "truthy" }] },\n      effects: [{ id: "yuan_ti_subtle_influence_effect", contexts: ["theatre"], trigger: "on_use", conditions: [], operations: [{ type: "register_dm_effect", effectId: "subtle_influence", name: "Subtle Influence", durationHours: 1, check: { abilityId: "cha", targetScoped: true }, modifier: { channel: "final_power", mode: "add", value: 4 }, note: "Source condition: DC 10 + target WIS Mod. The DM adjudicates whether the effect applies to a CHA Check against this target; disable it if it no longer applies." }] }],\n      rules: [],\n    },''')

print('Subtle Influence trait staged')
