from pathlib import Path

p = Path('Battle-viewer.html')
text = p.read_text(encoding='utf-8')

def rep(old, new, count=1):
    global text
    if old not in text: raise SystemExit('missing Battle-viewer block')
    text = text.replace(old, new, count)

rep('    <script src="js/combatEngine.js"></script>\n', '''    <script src="js/status-engine.js"></script>\n    <script src="js/trait-engine.js"></script>\n    <script src="js/racial-trait-catalog.js"></script>\n    <script src="js/universal-modifier-engine.js"></script>\n    <script src="js/universal-action-economy.js"></script>\n    <script src="js/trait-player-tray.js"></script>\n    <script src="js/trait-standardization-runtime.js"></script>\n    <script src="js/combatEngine.js"></script>\n''')
rep("    const COMBAT_STATE_PATH = 'campaña/combate/estado';\n    let luminousCombatPhaseState = null;\n", "    const COMBAT_STATE_PATH = 'campaña/combate/estado';\n    const SHARED_PLANNED_ACTIONS_PATH = 'campaña/combate/plannedActions';\n    let luminousCombatPhaseState = null;\n    let sharedPlannedActions = {};\n")
old = '''    function collectPlannedActionSlotIds() {\n        const economy = window.LuminousActionEconomy;\n        if (!economy?.actionSlotMaximum || !economy?.getPlannedAction) return [];\n        const slotIds = [];\n        combatUnitsForActionEconomy().forEach(unit => {\n            const unitId = String(unit.id || unit.unitId || unit.characterId || '');\n            if (!unitId) return;\n            const maximum = economy.actionSlotMaximum(unit);\n            for (let slotIndex = 0; slotIndex < maximum; slotIndex++) {\n                if (economy.getPlannedAction(unit, slotIndex)) slotIds.push(`${unitId}_slot_${slotIndex}`);\n            }\n        });\n        return slotIds;\n    }\n'''
new = '''    function getSharedPlannedAction(unitId, slotIndex) {\n        return sharedPlannedActions?.[unitId]?.[slotIndex] || sharedPlannedActions?.[unitId]?.[String(slotIndex)] || null;\n    }\n\n    function collectPlannedActionSlotIds() {\n        const slotIds = [];\n        Object.entries(sharedPlannedActions || {}).forEach(([unitId, slots]) => {\n            Object.entries(slots || {}).forEach(([slotIndex, action]) => {\n                if (action?.status === 'planned') slotIds.push(`${unitId}_slot_${slotIndex}`);\n            });\n        });\n        return slotIds;\n    }\n\n    async function claimSharedPlannedAction(unitId, slotIndex) {\n        const ref = db.ref(`${SHARED_PLANNED_ACTIONS_PATH}/${unitId}/${slotIndex}`);\n        const result = await ref.transaction(current => {\n            if (!current || current.status !== 'planned') return;\n            return { ...current, status: 'resolving', resolvingAt: Date.now() };\n        });\n        return result.committed ? result.snapshot.val() : null;\n    }\n\n    async function finishSharedPlannedAction(unitId, slotIndex, resolution) {\n        const success = Boolean(resolution?.handled && resolution?.result?.available);\n        const payload = { status: success ? 'resolved' : 'failed', resolvedAt: Date.now(), resolution: { handled: Boolean(resolution?.handled), available: Boolean(resolution?.result?.available), traitId: resolution?.planned?.traitId || resolution?.result?.trait?.id || null, reasons: resolution?.result?.reasons || [] } };\n        await db.ref(`${SHARED_PLANNED_ACTIONS_PATH}/${unitId}/${slotIndex}`).update(payload);\n        return payload;\n    }\n'''
rep(old, new)
old = '''            const slotIndex = Number(attackerSlotId.split('_slot_')[1]);\n            if (Number.isInteger(slotIndex) && typeof CombatEngine.resolveActionSlot === 'function') {\n                const plannedResolution = CombatEngine.resolveActionSlot(attackerUnit, slotIndex, {\n                    phase: 'combat',\n                    combatData,\n                    attackerSlotId,\n                });\n                if (plannedResolution?.handled) {\n                    const actionName = plannedResolution.result?.trait?.name || plannedResolution.planned?.traitId || 'Trait';\n                    if (plannedResolution.result?.available) {\n                        addLogEntry(`[ ACTION ] - ${attackerUnit.name}: ${actionName}`);\n                    } else {\n                        addLogEntry(`[ ACTION FAILED ] - ${attackerUnit.name}: ${actionName}`, 'interrupt');\n                    }\n                    resolvedSlots.add(attackerSlotId);\n                    continue;\n                }\n            }\n'''
new = '''            const slotIndex = Number(attackerSlotId.split('_slot_')[1]);\n            const sharedAction = Number.isInteger(slotIndex) ? getSharedPlannedAction(attackerBaseId, slotIndex) : null;\n            if (sharedAction?.status === 'planned' && typeof CombatEngine.resolveActionSlot === 'function') {\n                let claimed = null;\n                try { claimed = await claimSharedPlannedAction(attackerBaseId, slotIndex); } catch (error) { console.error('No se pudo reclamar el Action Slot compartido:', error); }\n                if (claimed) {\n                    const plannedResolution = CombatEngine.resolveActionSlot(attackerUnit, slotIndex, { phase: 'combat', combatData, attackerSlotId, plannedAction: claimed });\n                    try { await finishSharedPlannedAction(attackerBaseId, slotIndex, plannedResolution); } catch (error) { console.error('No se pudo cerrar el Action Slot compartido:', error); }\n                    const actionName = plannedResolution?.result?.trait?.name || claimed?.traitId || 'Trait';\n                    if (plannedResolution?.result?.available) addLogEntry(`[ ACTION ] - ${attackerUnit.name}: ${actionName}`);\n                    else addLogEntry(`[ ACTION FAILED ] - ${attackerUnit.name}: ${actionName}`, 'interrupt');\n                    resolvedSlots.add(attackerSlotId);\n                    continue;\n                }\n            }\n'''
rep(old, new)
rep("        // Escuchar datos de los combatientes\n        db.ref('campaña/combate/combatants').on('value', snap => {", "        // Shared Planning is authoritative across every player and the DM viewer.\n        db.ref(SHARED_PLANNED_ACTIONS_PATH).on('value', snap => { sharedPlannedActions = snap.val() || {}; });\n\n        // Escuchar datos de los combatientes\n        db.ref('campaña/combate/combatants').on('value', snap => {")
p.write_text(text, encoding='utf-8')
print('shared planned action viewer staged')
