const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const KEYS = ['LuminousVttTopology','LuminousVttFloorOpenings','LuminousVttBuildingPhysics'];
const ORIGINAL = new Map(KEYS.map(k => [k, global[k]]));
function fresh(file){const r=require.resolve(path.join(ROOT,file));delete require.cache[r];return require(r);}
function reset(){for(const k of KEYS)delete global[k];global.LuminousVttTopology=fresh('js/vtt/topology.js');global.LuminousVttFloorOpenings=fresh('js/vtt/floor-opening-core.js');}
function restore(){for(const k of KEYS){const v=ORIGINAL.get(k);if(v===undefined)delete global[k];else global[k]=v;}}
function edge(id,type,from,to,z=0){return global.LuminousVttTopology.normalizeElement({id,type,from,to,z:[z],state:type==='wall'?null:'closed'});}
function perimeter(footprint,z=0,doorEdge='1,1-2,1'){
  const out=[];let n=0;
  for(let c=footprint.minCol;c<=footprint.maxCol;c+=1){for(const [a,b] of [[{col:c,row:footprint.minRow},{col:c+1,row:footprint.minRow}],[{col:c,row:footprint.maxRow+1},{col:c+1,row:footprint.maxRow+1}]]){const key=global.LuminousVttBuildingPhysics?.edgeKey?.(a,b)||`${Math.min(a.col,b.col)},${Math.min(a.row,b.row)}-${Math.max(a.col,b.col)},${Math.max(a.row,b.row)}`;out.push(edge(`e${z}_${n++}`,key===doorEdge?'door':'wall',a,b,z));}}
  for(let r=footprint.minRow;r<=footprint.maxRow;r+=1){for(const [a,b] of [[{col:footprint.minCol,row:r},{col:footprint.minCol,row:r+1}],[{col:footprint.maxCol+1,row:r},{col:footprint.maxCol+1,row:r+1}]]){const key=global.LuminousVttBuildingPhysics?.edgeKey?.(a,b)||`${Math.min(a.col,b.col)},${Math.min(a.row,b.row)}-${Math.max(a.col,b.col)},${Math.max(a.row,b.row)}`;out.push(edge(`e${z}_${n++}`,key===doorEdge?'door':'wall',a,b,z));}}
  return out;
}
function mapBase(levels=[0]){const zLevels={};levels.forEach(z=>zLevels[String(z)]={zLayer:z,elevationFt:z*15,label:`Z${z}`});return{id:'building_physics',grid:{cols:12,rows:12,size:70,distancePerCell:5,distanceUnit:'ft'},defaultZStepFt:15,zLevels,topology:[],verticalPortals:[],floorOpenings:[],horizontalPlanes:[]};}
function addPlane(map,z,footprint,type='ceiling'){map.horizontalPlanes.push({id:`plane_${z}_${map.horizontalPlanes.length}`,type,zLayer:z,toZLayer:z+1,between:[z,z+1],footprint,state:'intact'});}
function basicPlan(footprint={minCol:1,minRow:1,maxCol:2,maxRow:2}){return{id:'building_a',segments:[{id:'z0',zLayer:0,footprint}],levels:[0],entrances:[{id:'front',zLayer:0,topologyId:'front_door'}]};}
function replaceDoorId(topology){const door=topology.find(e=>e.type==='door');if(door)door.id='front_door';}

test.beforeEach(()=>{reset();global.LuminousVttBuildingPhysics=fresh('js/vtt/building-physics-core.js');});
test.afterEach(restore);

test('closed envelope + real boundary door + overhead is a valid physical building',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase(),f={minCol:1,minRow:1,maxCol:2,maxRow:2};map.topology=perimeter(f);replaceDoorId(map.topology);addPlane(map,0,f);const result=core.validatePlan(basicPlan(f),map);expect(result.valid).toBe(true);expect(result.errors).toEqual([]);});

test('missing exterior edge is rejected as BUILDING_ENVELOPE_GAP',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase(),f={minCol:1,minRow:1,maxCol:2,maxRow:2};map.topology=perimeter(f);replaceDoorId(map.topology);map.topology.pop();addPlane(map,0,f);const result=core.validatePlan(basicPlan(f),map);expect(result.valid).toBe(false);expect(result.errors.some(e=>e.code==='BUILDING_ENVELOPE_GAP')).toBe(true);});

test('declared entrance must resolve to a door on the building envelope',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase(),f={minCol:1,minRow:1,maxCol:2,maxRow:2};map.topology=perimeter(f,0,null);map.topology[0]=edge('front_door','wall',{col:1,row:1},{col:2,row:1},0);addPlane(map,0,f);const result=core.validatePlan(basicPlan(f),map);expect(result.errors.some(e=>e.code==='BUILDING_ENTRANCE_NOT_DOOR')).toBe(true);});

test('same-building open continuation permits a deliberate envelope gap but rejects a fake wall',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase(),f={minCol:1,minRow:1,maxCol:2,maxRow:2};map.topology=perimeter(f);replaceDoorId(map.topology);const seam={from:{col:3,row:1},to:{col:3,row:2}};map.topology=map.topology.filter(e=>core.edgeKey(e.from,e.to)!==core.edgeKey(seam.from,seam.to));addPlane(map,0,f);const plan={...basicPlan(f),continuities:[{id:'chunk_seam',zLayer:0,...seam,relation:'open'}]};expect(core.validatePlan(plan,map).valid).toBe(true);map.topology.push(edge('fake_chunk_wall','wall',seam.from,seam.to,0));const blocked=core.validatePlan(plan,map);expect(blocked.errors.some(e=>e.code==='BUILDING_CONTINUATION_BLOCKED')).toBe(true);});

test('attached-building party wall contract requires a real wall',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase(),f={minCol:1,minRow:1,maxCol:2,maxRow:2};map.topology=perimeter(f);replaceDoorId(map.topology);const joint={from:{col:3,row:1},to:{col:3,row:2}};map.topology=map.topology.filter(e=>core.edgeKey(e.from,e.to)!==core.edgeKey(joint.from,joint.to));addPlane(map,0,f);const plan={...basicPlan(f),continuities:[{id:'party',zLayer:0,...joint,relation:'party_wall'}]};expect(core.validatePlan(plan,map).errors.some(e=>e.code==='PARTY_WALL_REQUIRED')).toBe(true);map.topology.push(edge('party_wall','wall',joint.from,joint.to,0));expect(core.validatePlan(plan,map).valid).toBe(true);});

test('required street/alley/service corridor cannot be cut by undeclared topology',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase(),f={minCol:1,minRow:5,maxCol:2,maxRow:6};map.topology=perimeter(f,'1,5-2,5');replaceDoorId(map.topology);addPlane(map,0,f);map.topology.push(edge('bad_wall','wall',{col:4,row:1},{col:4,row:2},0));const plan={...basicPlan(f),segments:[{id:'z0',zLayer:0,footprint:f}],corridors:[{id:'street_exit',kind:'street',zLayer:0,footprint:{minCol:3,minRow:0,maxCol:4,maxRow:3}}]};const result=core.validatePlan(plan,map);expect(result.errors.find(e=>e.code==='REQUIRED_CORRIDOR_BLOCKED')?.conflictIds).toContain('bad_wall');});

test('multi-floor building requires connected vertical routes and physical floor openings',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase([0,1]),f={minCol:1,minRow:1,maxCol:2,maxRow:2};map.topology=[...perimeter(f,0),...perimeter(f,1,'')];replaceDoorId(map.topology);addPlane(map,0,f);addPlane(map,1,f,'roof');map.verticalPortals=[{id:'stairs_a',type:'stairs',between:[0,1],from:{col:1,row:1},to:{col:1,row:2},state:'open',allowsMovement:true}];map.floorOpenings=[{id:'stairwell_a',type:'stairwell',zLayer:1,toZLayer:0,between:[1,0],footprint:{minCol:1,minRow:1,maxCol:1,maxRow:1},state:'open',walkable:false,fallThrough:true,allowsMovementThrough:true,allowsVisionThrough:true,allowsLightThrough:true}];const plan={id:'tower',segments:[{id:'z0',zLayer:0,footprint:f},{id:'z1',zLayer:1,footprint:f}],levels:[0,1],entrances:[{id:'front',zLayer:0,topologyId:'front_door'}],verticalConnectorIds:['stairs_a']};expect(core.validatePlan(plan,map).valid).toBe(true);map.floorOpenings=[];const missingOpening=core.validatePlan(plan,map);expect(missingOpening.errors.some(e=>e.code==='BUILDING_VERTICAL_OPENING_REQUIRED')).toBe(true);map.verticalPortals=[];const missingRoute=core.validatePlan(plan,map);expect(missingRoute.errors.some(e=>e.code==='BUILDING_LEVEL_UNREACHABLE')).toBe(true);});

test('multi-stop elevator only requires openings between adjacent stops, not impossible skip-floor shafts',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase([0,1,2]),f={minCol:1,minRow:1,maxCol:2,maxRow:2};map.topology=[...perimeter(f,0),...perimeter(f,1,''),...perimeter(f,2,'')];replaceDoorId(map.topology);addPlane(map,0,f);addPlane(map,1,f);addPlane(map,2,f,'roof');map.verticalPortals=[{id:'lift_a',type:'elevator',between:[0,2],stops:[0,1,2],state:'open'}];map.floorOpenings=[{id:'shaft_01',type:'shaft',zLayer:1,toZLayer:0,between:[1,0],footprint:{minCol:1,minRow:1,maxCol:1,maxRow:1},state:'open'},{id:'shaft_12',type:'shaft',zLayer:2,toZLayer:1,between:[2,1],footprint:{minCol:1,minRow:1,maxCol:1,maxRow:1},state:'open'}];const plan={id:'tower',segments:[0,1,2].map(z=>({id:`z${z}`,zLayer:z,footprint:f})),levels:[0,1,2],entrances:[{id:'front',zLayer:0,topologyId:'front_door'}],verticalConnectorIds:['lift_a']};const result=core.validatePlan(plan,map);expect(result.valid).toBe(true);expect(result.errors.some(e=>e.fromZ===0&&e.toZ===2&&e.code==='BUILDING_VERTICAL_OPENING_REQUIRED')).toBe(false);});

test('roof/ceiling coverage is validated per occupied cell and reports precise gaps',()=>{const core=global.LuminousVttBuildingPhysics,map=mapBase(),f={minCol:1,minRow:1,maxCol:2,maxRow:2};map.topology=perimeter(f);replaceDoorId(map.topology);addPlane(map,0,{minCol:1,minRow:1,maxCol:1,maxRow:2});const result=core.validatePlan(basicPlan(f),map);const gap=result.errors.find(e=>e.code==='BUILDING_OVERHEAD_GAP');expect(gap).toBeTruthy();expect(gap.missingCells).toContainEqual({col:2,row:1});expect(gap.missingCells).toContainEqual({col:2,row:2});});

test('browser/runtime wiring exposes building physics without creating a new persistence root',()=>{const html=fs.readFileSync(path.join(ROOT,'vtt.html'),'utf8'),bootstrap=fs.readFileSync(path.join(ROOT,'js/vtt/building-physics-bootstrap.js'),'utf8');expect(html).toContain('js/vtt/building-physics-core.js');expect(html).toContain('js/vtt/building-physics-bootstrap.js');expect(bootstrap).toContain('buildingPhysics:api');expect(bootstrap).not.toContain('firebase');expect(bootstrap).not.toContain('saveDefinition');});

test('building physics modules parse as JavaScript',()=>{execFileSync(process.execPath,['--check',path.join(ROOT,'js/vtt/building-physics-core.js')],{stdio:'pipe'});execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,'js/vtt/building-physics-bootstrap.js'),'utf8'),stdio:['pipe','pipe','pipe']});});