const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..'),FILES=['js/vtt/semantic-map-core.js','js/vtt/building-semantic-core.js','js/vtt/topology.js','js/vtt/vertical-portal.js','js/vtt/building-navigation-core.js'],KEYS=['LuminousVttSemanticMap','LuminousVttBuildingSemantics','LuminousVttTopology','LuminousVttVerticalPortal','LuminousVttBuildingNavigation'],ORIGINAL=new Map(KEYS.map(k=>[k,global[k]]));
function fresh(f){const r=require.resolve(path.join(ROOT,f));delete require.cache[r];return require(r);}function reset(){KEYS.forEach(k=>delete global[k]);global.LuminousVttSemanticMap=fresh(FILES[0]);global.LuminousVttBuildingSemantics=fresh(FILES[1]);global.LuminousVttTopology=fresh(FILES[2]);global.LuminousVttVerticalPortal=fresh(FILES[3]);global.LuminousVttBuildingNavigation=fresh(FILES[4]);}function restore(){for(const f of FILES){try{delete require.cache[require.resolve(path.join(ROOT,f))];}catch(_){}}for(const k of KEYS){const v=ORIGINAL.get(k);if(v===undefined)delete global[k];else global[k]=v;}}
function map(){return{grid:{cols:30,rows:30,size:70,distancePerCell:5},zLevels:{'0':{zLayer:0},'1':{zLayer:1}},topology:[{id:'front_door',type:'door',state:'closed',from:{col:1,row:10},to:{col:1,row:11},z:[0]},{id:'apt0_door',type:'door',state:'locked',from:{col:5,row:10},to:{col:5,row:11},z:[0]},{id:'apt1_door',type:'door',state:'open',from:{col:5,row:10},to:{col:5,row:11},z:[1]}],verticalPortals:[{id:'stairs_a',type:'stairs',between:[0,1],from:{col:3,row:10},to:{col:3,row:10},state:'open',allowsMovement:true,movementMode:'stairs',costMultiplier:1,bidirectional:true}]};}
function semantics(){return{buildings:[{id:'apt_b',label:'Apartment B',archetypeId:'apartment_building',defaultAccess:'semi_public',verticalConnectorIds:['stairs_a']}],areas:[{id:'street',label:'Street',spatialType:'street',functionalType:'circulation',access:'public',zLayer:0,geometry:{minCol:0,minRow:8,maxCol:0,maxRow:13}},{id:'hall0',buildingId:'apt_b',label:'Hall Z0',spatialType:'hallway',functionalType:'circulation',access:'semi_public',zLayer:0,geometry:{minCol:1,minRow:9,maxCol:4,maxRow:11},allowTopologyIds:['front_door','apt0_door']},{id:'apt101',buildingId:'apt_b',label:'Apt 101',spatialType:'room',functionalType:'apartment',access:'private',zLayer:0,geometry:{minCol:5,minRow:9,maxCol:8,maxRow:12}},{id:'hall1',buildingId:'apt_b',label:'Hall Z1',spatialType:'hallway',functionalType:'circulation',access:'semi_public',zLayer:1,geometry:{minCol:1,minRow:9,maxCol:4,maxRow:11},allowTopologyIds:['apt1_door']},{id:'apt201',buildingId:'apt_b',label:'Apt 201',spatialType:'room',functionalType:'apartment',access:'private',zLayer:1,geometry:{minCol:5,minRow:9,maxCol:8,maxRow:12}}],points:[{id:'entrance',buildingId:'apt_b',parentId:'hall0',label:'Main Entrance',type:'entrance',access:'public',zLayer:0,position:{col:1,row:10},physicalRefId:'front_door'}],relations:[{id:'street_entrance',type:'connects',fromId:'street',toId:'entrance',physicalRefId:'front_door',bidirectional:true},{id:'entrance_hall',type:'connects',fromId:'entrance',toId:'hall0',bidirectional:true},{id:'hall0_apt101',type:'connects',fromId:'hall0',toId:'apt101',physicalRefId:'apt0_door',bidirectional:true},{id:'hall0_hall1',type:'connects',fromId:'hall0',toId:'hall1',physicalRefId:'stairs_a',bidirectional:true},{id:'hall1_apt201',type:'connects',fromId:'hall1',toId:'apt201',physicalRefId:'apt1_door',bidirectional:true}]};}
test.beforeEach(reset);test.afterEach(restore);

test('graph includes building semantic nodes, exterior boundary nodes and derived portal stops',()=>{const g=global.LuminousVttBuildingNavigation.buildGraph(semantics(),'apt_b',map());expect(g.nodeById.street.external).toBe(true);expect(g.nodeById.entrance.external).toBe(false);expect(g.nodeById['portal:stairs_a:z:0']).toBeTruthy();expect(g.nodeById['portal:stairs_a:z:1']).toBeTruthy();expect(g.edges.some(e=>e.kind==='vertical'&&e.physicalRefId==='stairs_a')).toBe(true);});

test('closed public entrance remains plannable and reports open-door interaction',()=>{const nav=global.LuminousVttBuildingNavigation,g=nav.buildGraph(semantics(),'apt_b',map()),r=nav.shortestRoute(g,'street','hall0',{allowedAccess:['public','semi_public']});expect(r.found).toBe(true);expect(r.interactions.some(i=>i.action==='open_door'&&i.physicalRefId==='front_door')).toBe(true);});

test('private apartment is denied by access policy before physical A-star',()=>{const nav=global.LuminousVttBuildingNavigation,g=nav.buildGraph(semantics(),'apt_b',map());expect(nav.shortestRoute(g,'hall0','apt101',{allowedAccess:['public','semi_public'],allowLocked:true}).found).toBe(false);expect(nav.shortestRoute(g,'hall0','apt101',{allowedAccess:['public','semi_public','private'],allowLocked:true}).found).toBe(true);});

test('locked door blocks normal route but becomes a route with explicit unlock capability',()=>{const nav=global.LuminousVttBuildingNavigation,g=nav.buildGraph(semantics(),'apt_b',map()),opts={allowedAccess:['public','semi_public','private']};expect(nav.shortestRoute(g,'hall0','apt101',opts).found).toBe(false);const unlocked=nav.shortestRoute(g,'hall0','apt101',{...opts,allowLocked:true});expect(unlocked.found).toBe(true);expect(unlocked.interactions.some(i=>i.action==='unlock_door'&&i.physicalRefId==='apt0_door')).toBe(true);});

test('multi-Z route uses vertical physical edge and returns access transitions',()=>{const nav=global.LuminousVttBuildingNavigation,g=nav.buildGraph(semantics(),'apt_b',map()),r=nav.shortestRoute(g,'hall0','apt201',{allowedAccess:['public','semi_public','private']});expect(r.found).toBe(true);expect(r.edges.some(e=>e.kind==='vertical'&&e.physicalRefId==='stairs_a')).toBe(true);expect(r.accessTransitions.some(t=>t.toAccess==='private')).toBe(true);});

test('building navigation validator rejects semantic jumps across Z without a vertical portal',()=>{const nav=global.LuminousVttBuildingNavigation,s=semantics();s.relations.find(r=>r.id==='hall0_hall1').physicalRefId=null;s.buildings[0].verticalConnectorIds=[];const v=nav.validateGraph(s,'apt_b',map());expect(v.valid).toBe(false);expect(v.errors.some(e=>e.code==='BUILDING_NAV_VERTICAL_EDGE_UNBACKED')).toBe(true);});

test('structural validator catches an isolated interior area but ignores access and closed doors',()=>{const nav=global.LuminousVttBuildingNavigation,s=semantics();s.relations=s.relations.filter(r=>r.id!=='hall1_apt201');const v=nav.validateGraph(s,'apt_b',map());expect(v.errors.some(e=>e.code==='BUILDING_NAV_AREA_DISCONNECTED'&&e.areaId==='apt201')).toBe(true);expect(v.errors.some(e=>e.areaId==='apt101')).toBe(false);});

test('route context exposes only high-level physical refs and interactions for downstream world query',()=>{const nav=global.LuminousVttBuildingNavigation,g=nav.buildGraph(semantics(),'apt_b',map()),r=nav.shortestRoute(g,'street','apt201',{allowedAccess:['public','semi_public','private']});expect(r.found).toBe(true);expect(r.edges.map(e=>e.physicalRefId).filter(Boolean)).toEqual(expect.arrayContaining(['front_door','stairs_a','apt1_door']));expect(r.path).toEqual(expect.arrayContaining(['street','entrance','hall0','hall1','apt201']));});

test('runtime wiring exposes route, structuralRoute, routeContext and DM graph inspection',()=>{const boot=fs.readFileSync(path.join(ROOT,'js/vtt/building-navigation-bootstrap.js'),'utf8'),author=fs.readFileSync(path.join(ROOT,'js/vtt/building-navigation-authoring-bootstrap.js'),'utf8'),semantic=fs.readFileSync(path.join(ROOT,'js/vtt/semantic-map-bootstrap.js'),'utf8');expect(boot).toContain('routeContext');expect(boot).toContain('structuralRoute');expect(author).toContain('BUILD / VALIDATE');expect(semantic).toContain('startBuildingNavigation');expect(semantic).toContain('startBuildingNavigationAuthoring');});

test('building navigation modules parse as JavaScript',()=>{execFileSync(process.execPath,['--check',path.join(ROOT,'js/vtt/building-navigation-core.js')],{stdio:'pipe'});for(const f of ['js/vtt/building-navigation-bootstrap.js','js/vtt/building-navigation-authoring-bootstrap.js','js/vtt/semantic-map-bootstrap.js'])execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,f),'utf8'),stdio:['pipe','pipe','pipe']});});
