const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const ROOT = path.resolve(__dirname, '..');
const KEYS=['LuminousVttSpatialVision','LuminousVttVerticalPortal','LuminousVttElevator','LuminousVttElevatorPortalPatch','LuminousVttFloorOpenings','LuminousVttFloorOpeningTerrainPatch','LuminousVttElevatorFloorSupportPatch','LuminousVttElevatorTerrainPatch','LuminousVttSurfaceCore','LuminousVttMapAuthoring','LuminousVttSurfaceAuthoringPatch','LuminousVttStructureCore','LuminousVttStructureAuthoringPatch','LuminousVttHorizontalPlanes','LuminousVttHorizontalPlaneAuthoringPatch','LuminousVttVerticalAuthoringPatch','LuminousVttElevatorMapAuthoringPatch','LuminousVttStairBuilder','LuminousVttStairRoute'];
const ORIGINAL=new Map(KEYS.map(k=>[k,global[k]]));
function fresh(file){const r=require.resolve(path.join(ROOT,file));delete require.cache[r];return require(r);}
function reset(){for(const k of KEYS)delete global[k];}
function restore(){for(const k of KEYS){const v=ORIGINAL.get(k);if(v===undefined)delete global[k];else global[k]=v;}}
function mapBase(){return{id:'elevator_test',grid:{cols:10,rows:10,size:10,distancePerCell:5,distanceUnit:'ft'},defaultZStepFt:15,zLevels:{0:{zLayer:0,elevationFt:0,label:'Ground'},1:{zLayer:1,elevationFt:15,label:'Mid'},2:{zLayer:2,elevationFt:30,label:'Top'}},surfaceLayers:{},movement:{terrain:{}},topology:[],verticalPortals:[],floorOpenings:[],structures:[],tokens:[]};}
function loadElevator(){global.LuminousVttSpatialVision=fresh('js/vtt/spatial-vision.js');global.LuminousVttVerticalPortal=fresh('js/vtt/vertical-portal.js');global.LuminousVttElevator=fresh('js/vtt/elevator-core.js');fresh('js/vtt/elevator-portal-patch.js').install();return{core:global.LuminousVttElevator,portal:global.LuminousVttVerticalPortal};}
test.beforeEach(reset);test.afterEach(restore);

test('elevator portal has rectangular shaft footprint and every known stop between terminal floors',()=>{const{core,portal}=loadElevator(),map=mapBase(),lift=core.createElevatorPortal({from:{col:2,row:2},to:{col:4,row:5},fromZ:0,toZ:2,mapData:map});expect(lift.type).toBe('elevator');expect(lift.stops).toEqual([0,1,2]);expect(lift.currentZ).toBe(0);expect(lift.motionState).toBe('idle');expect(lift.doorState).toBe('open');expect(lift.footprint).toEqual({minCol:2,minRow:2,maxColExclusive:4,maxRowExclusive:5});expect(portal.portalLayers(lift)).toEqual([0,1,2]);expect(portal.portalOnLayer(lift,1)).toBe(true);expect(core.footprintCells(lift,map)).toHaveLength(6);});

test('elevator travel is temporal, interpolates elevation, closes doors, and opens on arrival',()=>{const{core}=loadElevator(),map=mapBase(),lift=core.createElevatorPortal({from:{col:2,row:2},to:{col:3,row:3},fromZ:0,toZ:2,mapData:map,speedFtPerSecond:15});const trip=core.beginTrip(lift,2,map,1000,['hero']);expect(trip.valid).toBe(true);expect(trip.travelMs).toBe(2000);expect(trip.portal.motionState).toBe('moving');expect(trip.portal.doorState).toBe('closed');expect(core.currentElevation(trip.portal,map,2000)).toBeCloseTo(15,5);expect(core.completeTrip(trip.portal,map,2500).reason).toBe('ELEVATOR_IN_TRANSIT');const done=core.completeTrip(trip.portal,map,3000);expect(done).toMatchObject({valid:true,arrived:true,arrivedZ:2,passengerIds:['hero']});expect(done.portal.currentZ).toBe(2);expect(done.portal.motionState).toBe('idle');expect(done.portal.doorState).toBe('open');});

test('passengers are attached during travel and change layer only when cabin arrives',()=>{const{core}=loadElevator(),map=mapBase(),token={id:'hero',x:25,y:25,zLayer:0,z:[0],gridPosition:{col:2,row:2,z:0},elevationFt:0};map.tokens=[token];const lift=core.createElevatorPortal({from:{col:2,row:2},to:{col:4,row:4},fromZ:0,toZ:2,mapData:map,speedFtPerSecond:15});expect(core.tokensInCabin(lift,map.tokens,map).map(t=>t.id)).toEqual(['hero']);const trip=core.beginTrip(lift,2,map,1000,['hero']);core.attachPassengers(map.tokens,trip.portal,map);core.updatePassengerElevation(map.tokens,trip.portal,map,2000);expect(token.zLayer).toBe(0);expect(token.elevationFt).toBeCloseTo(15,5);expect(token.elevatorRide).toMatchObject({elevatorId:lift.id,fromZ:0,toZ:2});const done=core.completeTrip(trip.portal,map,3000);core.arrivePassengers(map.tokens,done.passengerIds,done.arrivedZ,map);expect(token.zLayer).toBe(2);expect(token.gridPosition.z).toBe(2);expect(token.elevationFt).toBe(30);expect(token.elevatorRide).toBeUndefined();expect(token.lastVerticalTravel.movementMode).toBe('elevator');});

test('elevator generates one deterministic SHAFT opening per adjacent stop pair',()=>{const{core}=loadElevator(),map=mapBase(),lift=core.createElevatorPortal({from:{col:1,row:1},to:{col:3,row:3},fromZ:0,toZ:2,mapData:map});const specs=core.shaftOpeningSpecs(lift,map);expect(specs).toHaveLength(2);expect(specs.map(x=>x.between)).toEqual([[1,0],[2,1]]);expect(specs[0].id).toContain(`floor_shaft_${lift.id}_1_0`);expect(specs[0].footprint).toEqual({minCol:1,minRow:1,maxCol:2,maxRow:2});expect(specs.every(x=>x.type==='shaft'&&x.fallThrough)).toBe(true);});

test('stationary cabin restores physical support, while closed doors remain non-walkable terrain',()=>{const{core}=loadElevator(),map=mapBase();global.LuminousVttFloorOpenings=fresh('js/vtt/floor-opening-core.js');const lift=core.createElevatorPortal({from:{col:2,row:2},to:{col:3,row:3},fromZ:0,toZ:2,mapData:map});map.verticalPortals=[core.normalizeElevatorPortal({...lift,currentZ:1,doorState:'open',motionState:'idle'},map,lift)];map.floorOpenings=core.shaftOpeningSpecs(lift,map).map(x=>global.LuminousVttFloorOpenings.normalizeOpening(x,map));fresh('js/vtt/elevator-floor-support-patch.js').install();expect(global.LuminousVttFloorOpenings.supportAtCell(map,1,2,2)).toMatchObject({supported:true,elevatorCabin:true});global.LuminousVttSurfaceCore=fresh('js/vtt/surface-core.js');fresh('js/vtt/floor-opening-terrain-patch.js').install();fresh('js/vtt/elevator-terrain-patch.js').install();global.LuminousVttSurfaceCore.ensureMapState(map);expect(map.movement.terrain['1']?.['2_2']?._floorOpening).not.toBe(true);map.verticalPortals=[core.normalizeElevatorPortal({...map.verticalPortals[0],doorState:'closed',elevator:{...map.verticalPortals[0].elevator,doorState:'closed'}},map,map.verticalPortals[0])];global.LuminousVttSurfaceCore.syncFloorOpeningTerrain(map);expect(map.movement.terrain['1']['2_2']).toMatchObject({_floorOpening:true,allowedModes:['fly']});expect(global.LuminousVttFloorOpenings.supportAtCell(map,1,2,2).supported).toBe(true);});

test('shaft becomes unsupported again while cabin is moving',()=>{const{core}=loadElevator(),map=mapBase();global.LuminousVttFloorOpenings=fresh('js/vtt/floor-opening-core.js');const lift=core.createElevatorPortal({from:{col:2,row:2},to:{col:3,row:3},fromZ:0,toZ:2,mapData:map,speedFtPerSecond:15}),atMid=core.normalizeElevatorPortal({...lift,currentZ:1},map,lift),trip=core.beginTrip(atMid,2,map,1000,[]);map.verticalPortals=[trip.portal];map.floorOpenings=core.shaftOpeningSpecs(lift,map).map(x=>global.LuminousVttFloorOpenings.normalizeOpening(x,map));fresh('js/vtt/elevator-floor-support-patch.js').install();expect(global.LuminousVttFloorOpenings.supportAtCell(map,1,2,2).supported).toBe(false);});

test('stairs movement engine ignores elevators; elevators use their own authority/runtime',()=>{const{core}=loadElevator(),map=mapBase();global.LuminousVttStairRoute=fresh('js/vtt/stair-route.js');map.verticalPortals=[core.createElevatorPortal({from:{col:2,row:2},to:{col:3,row:3},fromZ:0,toZ:2,mapData:map})];const movement=fresh('js/vtt/vertical-movement.js');expect(movement.transitionCandidates(map,0)).toEqual([]);});

test('MapDefinition round-trip preserves elevator stops and intermediate floors cannot be deleted',()=>{const{core}=loadElevator(),map=mapBase();global.LuminousVttMapAuthoring=fresh('js/vtt/map-authoring.js');global.LuminousVttSurfaceCore=fresh('js/vtt/surface-core.js');fresh('js/vtt/surface-authoring-patch.js');global.LuminousVttStructureCore=fresh('js/vtt/structure-core.js');fresh('js/vtt/structure-authoring-patch.js');global.LuminousVttHorizontalPlanes=fresh('js/vtt/horizontal-plane-core.js');fresh('js/vtt/horizontal-plane-authoring-patch.js');global.LuminousVttStairBuilder=fresh('js/vtt/stair-builder.js');fresh('js/vtt/vertical-authoring-patch.js').install();fresh('js/vtt/elevator-map-authoring-patch.js').install();map.verticalPortals=[core.createElevatorPortal({from:{col:2,row:2},to:{col:4,row:4},fromZ:0,toZ:2,mapData:map})];const authoring=global.LuminousVttMapAuthoring,definition=authoring.definitionFromMapData(map);expect(definition.verticalPortals[0].type).toBe('elevator');expect(definition.verticalPortals[0].stops).toEqual([0,1,2]);const restored=mapBase();authoring.applyDefinition(restored,definition);expect(restored.verticalPortals[0].stops).toEqual([0,1,2]);const gate=authoring.canDeleteLevel(restored,1);expect(gate.valid).toBe(false);expect(gate.dependencies.elevators).toHaveLength(1);});

test('browser wiring preloads elevator portal/state before main and exposes functional DM/player controls',()=>{const html=fs.readFileSync(path.join(ROOT,'vtt.html'),'utf8'),bootstrap=fs.readFileSync(path.join(ROOT,'js/vtt/elevator-bootstrap.js'),'utf8'),authoring=fs.readFileSync(path.join(ROOT,'js/vtt/elevator-authoring-bootstrap.js'),'utf8'),state=fs.readFileSync(path.join(ROOT,'js/vtt/elevator-state-patch.js'),'utf8');expect(html.indexOf('elevator-portal-patch.js')).toBeLessThan(html.indexOf('vertical-portal-state.js'));expect(html.indexOf('elevator-state-patch.js')).toBeLessThan(html.indexOf('main.js'));expect(html).toContain('elevator-autostart.js');expect(html).toContain('elevator-authoring-bootstrap.js');expect(bootstrap).toContain("['call','go','open','close']");expect(bootstrap).toContain('vtt:elevator-arrived');expect(authoring).toContain('data-elevator-tool="elevator"');expect(authoring).toContain('Z TOP');expect(state).toContain('elevatorRequests');expect(state).toContain('dmDirect:false');});

test('elevator modules parse as JavaScript',()=>{for(const file of ['js/vtt/elevator-core.js','js/vtt/elevator-portal-patch.js','js/vtt/elevator-state-patch.js','js/vtt/elevator-renderer-patch.js','js/vtt/elevator-floor-support-patch.js','js/vtt/elevator-terrain-patch.js','js/vtt/elevator-map-authoring-patch.js'])execFileSync(process.execPath,['--check',path.join(ROOT,file)],{stdio:'pipe'});for(const file of ['js/vtt/elevator-bootstrap.js','js/vtt/elevator-autostart.js','js/vtt/elevator-authoring-bootstrap.js','js/vtt/elevator-physics-preload.js','js/vtt/elevator-support-runtime.js'])execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,file),'utf8'),stdio:['pipe','pipe','pipe']});});
