const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT=path.resolve(__dirname,'..');
const KEYS=['LuminousVttHorizontalPlanes','LuminousVttHorizontalPlanePerceptionPatch','LuminousVttFloorOpenings','LuminousVttSpatialVision','LuminousVttFloorOpeningSpatialPatch','LuminousVttLightingEngine','LuminousVttPovEngine','LuminousVttMapAuthoring','LuminousVttSurfaceCore','LuminousVttStructureCore','LuminousVttSurfaceAuthoringPatch','LuminousVttStructureAuthoringPatch','LuminousVttHorizontalPlaneAuthoringPatch'];
const ORIGINAL=new Map(KEYS.map(key=>[key,global[key]]));
function fresh(file){const resolved=require.resolve(path.join(ROOT,file));delete require.cache[resolved];return require(resolved);}
function reset(){for(const key of KEYS)delete global[key];}
function restore(){for(const key of KEYS){const value=ORIGINAL.get(key);if(value===undefined)delete global[key];else global[key]=value;}}
function mapBase(){return{id:'roof_ceiling',grid:{cols:8,rows:8,size:10,distancePerCell:5,distanceUnit:'ft'},defaultZStepFt:15,defaultCeilingHeightFt:10,zLevels:{0:{zLayer:0,elevationFt:0,label:'Ground'},1:{zLayer:1,elevationFt:15,label:'Upper'}},topology:[],walls:[],tokens:[],structures:[],floorOpenings:[],horizontalPlanes:[],movement:{terrain:{}},lighting:{scene:{sources:[],interiors:[],transformers:[],switches:[]}}};}

test.beforeEach(reset);test.afterEach(restore);

test('canonical ceiling and roof planes normalize footprint, elevation and physical flags',()=>{const core=fresh('js/vtt/horizontal-plane-core.js'),map=mapBase();const ceiling=core.createPlane({type:'ceiling',from:{col:2,row:2},to:{col:4,row:3},zLayer:0,toZLayer:1,mapData:map});expect(ceiling).toMatchObject({type:'ceiling',zLayer:0,toZLayer:1,between:[0,1],elevationFt:10,blocksVision:true,blocksLight:true,blocksExteriorLight:true,walkableTop:false});expect(ceiling.footprint).toEqual({minCol:2,minRow:2,maxCol:4,maxRow:3});const roof=core.createPlane({type:'roof',from:{col:0,row:0},to:{col:1,row:1},zLayer:1,toZLayer:2,mapData:map});expect(roof.type).toBe('roof');expect(roof.walkableTop).toBe(true);expect(roof.thicknessFt).toBe(1);});

test('opaque horizontal plane blocks vertical ray unless an open floor opening punches the same footprint',()=>{const openings=fresh('js/vtt/floor-opening-core.js');global.LuminousVttFloorOpenings=openings;const core=fresh('js/vtt/horizontal-plane-core.js'),map=mapBase();const plane=core.createPlane({type:'ceiling',from:{col:2,row:2},to:{col:2,row:2},zLayer:0,toZLayer:1,mapData:map});map.horizontalPlanes=[plane];const from={x:25,y:25,zLayer:0,elevationFt:5},to={x:25,y:25,zLayer:1,elevationFt:15};expect(core.blocksRay(from,to,map,'vision').blocked).toBe(true);expect(core.blocksRay(from,to,map,'light').blocked).toBe(true);map.floorOpenings=[openings.createOpening({type:'stairwell',from:{col:2,row:2},to:{col:2,row:2},zLayer:1,toZLayer:0,mapData:map})];expect(core.blocksRay(from,to,map,'vision').blocked).toBe(false);expect(core.blocksRay(from,to,map,'light').blocked).toBe(false);map.floorOpenings=[openings.createOpening({type:'trapdoor',from:{col:2,row:2},to:{col:2,row:2},zLayer:1,toZLayer:0,mapData:map,state:'closed'})];expect(core.blocksRay(from,to,map,'vision').blocked).toBe(true);});

test('lighting and POV consume canonical planes while preserving floor opening passthrough',()=>{const openings=fresh('js/vtt/floor-opening-core.js');global.LuminousVttFloorOpenings=openings;global.LuminousVttSpatialVision=fresh('js/vtt/spatial-vision.js');fresh('js/vtt/floor-opening-spatial-patch.js');const core=fresh('js/vtt/horizontal-plane-core.js');global.LuminousVttHorizontalPlanes=core;global.LuminousVttLightingEngine=fresh('js/vtt/lighting-engine.js');global.LuminousVttPovEngine=fresh('js/vtt/pov-engine.js');const patch=fresh('js/vtt/horizontal-plane-perception-patch.js');patch.install();const light=global.LuminousVttLightingEngine,pov=global.LuminousVttPovEngine,map=mapBase(),scene=map.lighting.scene;map.horizontalPlanes=[core.createPlane({type:'ceiling',from:{col:2,row:2},to:{col:2,row:2},zLayer:0,toZLayer:1,mapData:map})];const from={x:25,y:25,zLayer:0,elevationFt:5},to={x:25,y:25,zLayer:1,elevationFt:15};expect(light.canTraverseLayers(from,to,scene,map,'vision')).toBe(false);expect(light.canTraverseLayers(from,to,scene,map,'light')).toBe(false);const viewer={x:25,y:25,zLayer:0,elevationFt:0,eyeHeightFt:5,facingDeg:0,visionConeDeg:360,senses:{darkvisionFt:60}};expect(pov.roofOcclusion(viewer,to,scene,map).blocked).toBe(true);map.floorOpenings=[openings.createOpening({type:'stairwell',from:{col:2,row:2},to:{col:2,row:2},zLayer:1,toZLayer:0,mapData:map})];expect(light.canTraverseLayers(from,to,scene,map,'vision')).toBe(true);expect(pov.roofOcclusion(viewer,to,scene,map).blocked).toBe(false);});

test('roof/ceiling overhead suppresses exterior ambient light only inside its footprint',()=>{global.LuminousVttFloorOpenings=fresh('js/vtt/floor-opening-core.js');const core=fresh('js/vtt/horizontal-plane-core.js');global.LuminousVttHorizontalPlanes=core;global.LuminousVttLightingEngine=fresh('js/vtt/lighting-engine.js');const patch=fresh('js/vtt/horizontal-plane-perception-patch.js');patch.install();const light=global.LuminousVttLightingEngine,map=mapBase(),scene=map.lighting.scene,environment={state:{light:'bright'}};map.horizontalPlanes=[core.createPlane({type:'roof',from:{col:2,row:2},to:{col:3,row:3},zLayer:0,toZLayer:1,mapData:map})];const covered=light.ambientAtPoint({x:25,y:25,zLayer:0,elevationFt:0},scene,map,environment);const outside=light.ambientAtPoint({x:55,y:55,zLayer:0,elevationFt:0},scene,map,environment);expect(covered).toMatchObject({level:'darkness',origin:'horizontal_plane'});expect(outside.level).toBe('bright');});

test('MapDefinition round-trip preserves horizontal planes and floor deletion detects them',()=>{global.LuminousVttMapAuthoring=fresh('js/vtt/map-authoring.js');global.LuminousVttSurfaceCore=fresh('js/vtt/surface-core.js');fresh('js/vtt/surface-authoring-patch.js');global.LuminousVttStructureCore=fresh('js/vtt/structure-core.js');fresh('js/vtt/structure-authoring-patch.js');global.LuminousVttHorizontalPlanes=fresh('js/vtt/horizontal-plane-core.js');fresh('js/vtt/horizontal-plane-authoring-patch.js').install();const authoring=global.LuminousVttMapAuthoring,core=global.LuminousVttHorizontalPlanes,map=mapBase();map.horizontalPlanes=[core.createPlane({type:'ceiling',from:{col:1,row:1},to:{col:4,row:4},zLayer:0,toZLayer:1,mapData:map})];const definition=authoring.definitionFromMapData(map);expect(definition.horizontalPlanes).toHaveLength(1);const restored=mapBase();authoring.applyDefinition(restored,definition);expect(restored.horizontalPlanes).toHaveLength(1);const gate=authoring.canDeleteLevel(restored,1);expect(gate.valid).toBe(false);expect(gate.dependencies.horizontalPlanes).toHaveLength(1);});

test('browser wiring preloads authoring before main and installs roof/ceiling perception + DM tools',()=>{const html=fs.readFileSync(path.join(ROOT,'vtt.html'),'utf8'),bootstrap=fs.readFileSync(path.join(ROOT,'js/vtt/horizontal-plane-bootstrap.js'),'utf8'),preload=fs.readFileSync(path.join(ROOT,'js/vtt/horizontal-plane-preload.js'),'utf8');expect(html.indexOf('horizontal-plane-preload.js')).toBeLessThan(html.indexOf('js/vtt/main.js'));expect(html).toContain('horizontal-plane-lighting-patch.js');expect(html).toContain('horizontal-plane-bootstrap.js');expect(preload).toContain("import './horizontal-plane-authoring-patch.js'");expect(bootstrap).toContain('data-plane-tool="ceiling"');expect(bootstrap).toContain('data-plane-tool="roof"');expect(bootstrap).toContain('__horizontalPlaneRevision');expect(bootstrap).toContain("lighting?.controller?.setTool?.('select')");});

test('roof/ceiling modules parse as JavaScript',()=>{for(const file of ['js/vtt/horizontal-plane-core.js','js/vtt/horizontal-plane-authoring-patch.js','js/vtt/horizontal-plane-perception-patch.js'])execFileSync(process.execPath,['--check',path.join(ROOT,file)],{stdio:'pipe'});for(const file of ['js/vtt/horizontal-plane-preload.js','js/vtt/horizontal-plane-lighting-patch.js','js/vtt/horizontal-plane-bootstrap.js'])execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,file),'utf8'),stdio:['pipe','pipe','pipe']});});
