const { test, expect } = require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..');
const MODULES=['js/vtt/semantic-map-core.js','js/vtt/topology.js','js/vtt/map-authoring.js','js/vtt/semantic-map-authoring-patch.js'];
const KEYS=['LuminousVttSemanticMap','LuminousVttTopology','LuminousVttMapAuthoring','LuminousVttSemanticMapAuthoringPatch'];
const ORIGINAL=new Map(KEYS.map(k=>[k,global[k]]));
function fresh(file){const r=require.resolve(path.join(ROOT,file));delete require.cache[r];return require(r);}
function reset(){for(const k of KEYS)delete global[k];global.LuminousVttTopology=fresh('js/vtt/topology.js');global.LuminousVttSemanticMap=fresh('js/vtt/semantic-map-core.js');}
function restore(){for(const file of MODULES){try{delete require.cache[require.resolve(path.join(ROOT,file))];}catch(_){}}for(const k of KEYS){const v=ORIGINAL.get(k);if(v===undefined)delete global[k];else global[k]=v;}}
function map(){return{id:'semantic_test',grid:{cols:12,rows:12,size:70,distancePerCell:5,distanceUnit:'ft'},zLevels:{0:{zLayer:0,elevationFt:0},1:{zLayer:1,elevationFt:15}},topology:[],semantics:{areas:[],points:[],relations:[]}};}
function area(id='shop'){return{id,kind:'area',label:'Shop Floor',spatialType:'room',functionalType:'shop',access:'public',zLayer:0,geometry:{type:'rect',minCol:1,minRow:1,maxCol:3,maxRow:3},tags:['interior']};}
test.beforeEach(reset);test.afterEach(restore);

test('rect and polygon semantic areas resolve cells without becoming per-cell authority',()=>{const core=global.LuminousVttSemanticMap,m=map();m.semantics.areas=[area(),{id:'plaza',spatialType:'plaza',functionalType:'circulation',access:'public',zLayer:0,geometry:{type:'polygon',points:[{col:5,row:1},{col:9,row:1},{col:7,row:5}]}}];const s=core.normalizeSemantics(m.semantics),index=core.buildCellIndex(s,m);expect(core.semanticAt(s,index,0,2,2).areas.map(x=>x.id)).toContain('shop');expect(core.semanticAt(s,index,0,7,2).areas.map(x=>x.id)).toContain('plaza');expect(Object.keys(index).length).toBeGreaterThan(0);expect(s.areas[0].geometry.type).toBe('rect');});

test('GOAP-facing queries filter function, spatial type, hierarchy and relations',()=>{const core=global.LuminousVttSemanticMap,m=map();m.semantics={areas:[area('shop'),{...area('storage'),label:'Storage',functionalType:'storage',access:'service',parentId:'shop',geometry:{type:'rect',minCol:2,minRow:2,maxCol:2,maxRow:2}}],points:[{id:'front',type:'entrance',label:'Front',zLayer:0,position:{col:1,row:2},parentId:'shop'}],relations:[{id:'street_shop',type:'connects',fromId:'front',toId:'shop',bidirectional:true}]};expect(core.areasByFunction(m.semantics,'storage').map(x=>x.id)).toEqual(['storage']);expect(core.areasBySpatialType(m.semantics,'room').length).toBe(2);expect(core.childrenOf(m.semantics,'shop').map(x=>x.id).sort()).toEqual(['front','storage']);expect(core.relationsFrom(m.semantics,'shop').map(x=>x.id)).toEqual(['street_shop']);expect(core.entityById(m.semantics,'front').type).toBe('entrance');});

test('semantic validator catches bad Z, parent, relation, polygon and point containment',()=>{const core=global.LuminousVttSemanticMap,m=map();m.semantics={areas:[area('shop'),{id:'badpoly',spatialType:'room',functionalType:'storage',zLayer:9,geometry:{type:'polygon',points:[{col:1,row:1},{col:2,row:2}]},parentId:'missing'}],points:[{id:'badpoint',type:'entrance',zLayer:0,position:{col:10,row:10},parentId:'shop'}],relations:[{id:'badrel',type:'connects',fromId:'shop',toId:'missing'}]};const result=core.validateSemantics(m.semantics,m),codes=result.errors.map(e=>e.code);expect(codes).toContain('SEMANTIC_Z_LAYER_NOT_FOUND');expect(codes).toContain('SEMANTIC_POLYGON_INVALID');expect(codes).toContain('SEMANTIC_PARENT_NOT_FOUND');expect(codes).toContain('SEMANTIC_POINT_OUTSIDE_PARENT');expect(codes).toContain('SEMANTIC_RELATION_TARGET_NOT_FOUND');});

test('street/alley/hallway continuity rejects blocking topology unless explicitly allowed',()=>{const core=global.LuminousVttSemanticMap,m=map();m.topology=[global.LuminousVttTopology.normalizeElement({id:'bad_wall',type:'wall',from:{col:3,row:1},to:{col:3,row:2},z:[0]})];const street={id:'street',spatialType:'street',functionalType:'circulation',access:'public',zLayer:0,geometry:{type:'rect',minCol:1,minRow:1,maxCol:5,maxRow:2},tags:['required_continuity']};let result=core.validateSemantics({areas:[street]},m);expect(result.errors.find(e=>e.code==='SEMANTIC_PHYSICAL_CONFLICT')?.topologyId).toBe('bad_wall');result=core.validateSemantics({areas:[{...street,allowTopologyIds:['bad_wall']}]},m);expect(result.errors.some(e=>e.code==='SEMANTIC_PHYSICAL_CONFLICT')).toBe(false);});

test('semantic map definition persists and blocks deleting a floor that owns semantic entities',()=>{global.LuminousVttMapAuthoring=fresh('js/vtt/map-authoring.js');fresh('js/vtt/semantic-map-authoring-patch.js');const authoring=global.LuminousVttMapAuthoring,m=map();m.semantics={areas:[area('shop')],points:[{id:'front',type:'entrance',zLayer:0,position:{col:1,row:2},parentId:'shop'}],relations:[]};const definition=authoring.definitionFromMapData(m);expect(definition.semantics.areas[0].functionalType).toBe('shop');const target={...map(),semantics:{areas:[],points:[],relations:[]}};authoring.applyDefinition(target,definition,{keepSceneState:true});expect(target.semantics.points[0].id).toBe('front');const gate=authoring.canDeleteLevel(target,0);expect(gate.valid).toBe(false);expect(gate.dependencies.semanticAreas.map(x=>x.id)).toContain('shop');});

test('DM authoring exposes RECT/POLYGON/POINT marking and runtime exposes GOAP query calls',()=>{const html=fs.readFileSync(path.join(ROOT,'vtt.html'),'utf8'),ui=fs.readFileSync(path.join(ROOT,'js/vtt/semantic-map-authoring-bootstrap.js'),'utf8'),runtime=fs.readFileSync(path.join(ROOT,'js/vtt/semantic-map-bootstrap.js'),'utf8');expect(html).toContain('semantic-map-bootstrap.js');expect(html).toContain('semantic-map-authoring-bootstrap.js');expect(ui).toContain('AREA RECT');expect(ui).toContain('AREA POLY');expect(ui).toContain('POINT');expect(ui).toContain('required_continuity');expect(runtime).toContain('semanticAt:');expect(runtime).toContain('areasByFunction:');expect(runtime).toContain('childrenOf:');expect(runtime).toContain('relationsFrom:');expect(runtime).not.toContain('firebase');});

test('semantic modules parse as JavaScript',()=>{for(const file of ['js/vtt/semantic-map-core.js','js/vtt/semantic-map-authoring-patch.js','js/vtt/semantic-map-renderer-patch.js'])execFileSync(process.execPath,['--check',path.join(ROOT,file)],{stdio:'pipe'});for(const file of ['js/vtt/semantic-map-bootstrap.js','js/vtt/semantic-map-authoring-bootstrap.js'])execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,file),'utf8'),stdio:['pipe','pipe','pipe']});});