const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const ROOT = path.resolve(__dirname, '..');
const KEYS=['LuminousVttSemanticMap','LuminousVttBuildingSemantics'];
const ORIGINAL=new Map(KEYS.map(k=>[k,global[k]]));
const FILES=['js/vtt/semantic-map-core.js','js/vtt/building-semantic-core.js'];
function fresh(file){const r=require.resolve(path.join(ROOT,file));delete require.cache[r];return require(r);}
function reset(){for(const k of KEYS)delete global[k];global.LuminousVttSemanticMap=fresh(FILES[0]);global.LuminousVttBuildingSemantics=fresh(FILES[1]);}
function restore(){for(const f of FILES){try{delete require.cache[require.resolve(path.join(ROOT,f))];}catch(_){}}for(const k of KEYS){const v=ORIGINAL.get(k);if(v===undefined)delete global[k];else global[k]=v;}}
function mapBase(){return{grid:{cols:20,rows:20,size:70,distancePerCell:5},zLevels:{'0':{zLayer:0},'1':{zLayer:1}},topology:[{id:'front_door',type:'door',from:{col:1,row:1},to:{col:2,row:1},z:[0]},{id:'staff_door',type:'door',from:{col:4,row:2},to:{col:4,row:3},z:[0]},{id:'apt_door',type:'door',from:{col:4,row:8},to:{col:5,row:8},z:[1]}],verticalPortals:[{id:'stairs_a',type:'stairs',between:[0,1],from:{col:3,row:3},to:{col:3,row:8}}]};}
function validSemantics(){return{buildings:[{id:'building_a',label:'Building A',defaultAccess:'semi_public',verticalConnectorIds:['stairs_a']}],areas:[{id:'lobby',buildingId:'building_a',label:'Lobby',spatialType:'room',functionalType:'circulation',access:'public',zLayer:0,geometry:{minCol:1,minRow:1,maxCol:3,maxRow:3},roles:['reception'],capabilities:['wait']},{id:'storage',buildingId:'building_a',label:'Storage',spatialType:'room',functionalType:'storage',access:'service',zLayer:0,geometry:{minCol:4,minRow:1,maxCol:6,maxRow:3},roles:['shop_inventory'],capabilities:['store_items','retrieve_items']},{id:'hall_z1',buildingId:'building_a',label:'Hallway',spatialType:'hallway',functionalType:'circulation',access:'semi_public',zLayer:1,geometry:{minCol:1,minRow:7,maxCol:4,maxRow:8}},{id:'apt_101',buildingId:'building_a',label:'Apartment 101',spatialType:'room',functionalType:'apartment',access:'private',zLayer:1,geometry:{minCol:5,minRow:7,maxCol:8,maxRow:10},roles:['home'],capabilities:['reside','rest']},{id:'bedroom_101',parentId:'apt_101',label:'Bedroom',spatialType:'room',functionalType:'residential',access:'inherit',zLayer:1,geometry:{minCol:6,minRow:8,maxCol:7,maxRow:9},capabilities:['sleep']}],points:[{id:'entrance_a',buildingId:'building_a',parentId:'lobby',type:'entrance',label:'Main Entrance',access:'public',zLayer:0,position:{col:1,row:1},physicalRefId:'front_door'}],relations:[{id:'lobby_storage',type:'connects',fromId:'lobby',toId:'storage',physicalRefId:'staff_door'},{id:'lobby_hall',type:'connects',fromId:'lobby',toId:'hall_z1',physicalRefId:'stairs_a'},{id:'hall_apt',type:'connects',fromId:'hall_z1',toId:'apt_101',physicalRefId:'apt_door'}]};}
test.beforeEach(reset);test.afterEach(restore);

test('semantic schema preserves building ownership, roles, capabilities and inherit access',()=>{const semantic=global.LuminousVttSemanticMap,s=semantic.normalizeSemantics(validSemantics());expect(s.schemaVersion).toBe(2);expect(s.buildings).toHaveLength(1);const storage=s.areas.find(a=>a.id==='storage');expect(storage.buildingId).toBe('building_a');expect(storage.roles).toContain('shop_inventory');expect(storage.capabilities).toContain('store_items');expect(s.areas.find(a=>a.id==='bedroom_101').access).toBe('inherit');});

test('building model derives ownership through parent hierarchy and levels across Z',()=>{const core=global.LuminousVttBuildingSemantics,s=validSemantics(),map=mapBase();expect(core.inheritedBuildingId(s,'bedroom_101')).toBe('building_a');expect(core.buildingOf(s,'bedroom_101').id).toBe('building_a');expect(core.buildingLevels(s,'building_a',map)).toEqual([0,1]);expect(core.areasOnBuildingLevel(s,'building_a',1).map(a=>a.id)).toEqual(expect.arrayContaining(['hall_z1','apt_101','bedroom_101']));});

test('access inheritance resolves parent then building default and exposes public/private zones',()=>{const core=global.LuminousVttBuildingSemantics,s=validSemantics();expect(core.effectiveAccess(s,'bedroom_101')).toBe('private');const zones=core.accessZones(s,'building_a');expect(zones.public.map(a=>a.id)).toContain('lobby');expect(zones.private.map(a=>a.id)).toContain('apt_101');expect(zones.service.map(a=>a.id)).toContain('storage');});

test('GOAP-facing role and capability queries are independent from functional type',()=>{const core=global.LuminousVttBuildingSemantics,s=validSemantics();expect(core.entitiesByRole(s,'shop_inventory').map(e=>e.id)).toEqual(['storage']);expect(core.entitiesByCapability(s,'rest').map(e=>e.id)).toContain('apt_101');expect(core.entitiesByCapability(s,'sleep').map(e=>e.id)).toContain('bedroom_101');});

test('building entrances and vertical connectors resolve to existing physical references',()=>{const core=global.LuminousVttBuildingSemantics,s=validSemantics(),map=mapBase();expect(core.entrancesOfBuilding(s,'building_a').map(p=>p.id)).toEqual(['entrance_a']);expect(core.verticalConnectorsOfBuilding(s,'building_a',map).map(p=>p.id)).toEqual(['stairs_a']);expect(core.validateBuildingSemantics(s,map).valid).toBe(true);});

test('building requires public-facing and controlled zones by default',()=>{const core=global.LuminousVttBuildingSemantics,map=mapBase(),s=validSemantics();s.areas=s.areas.filter(a=>!['storage','apt_101','bedroom_101'].includes(a.id));const result=core.validateBuildingSemantics(s,map);expect(result.errors.some(e=>e.code==='BUILDING_CONTROLLED_ZONE_REQUIRED')).toBe(true);});

test('building requires a public entrance backed by a real topology door',()=>{const core=global.LuminousVttBuildingSemantics,map=mapBase(),s=validSemantics();s.points[0].physicalRefId='missing_door';let result=core.validateBuildingSemantics(s,map);expect(result.errors.some(e=>e.code==='BUILDING_ENTRANCE_PHYSICAL_REF_NOT_FOUND')).toBe(true);s.points[0].physicalRefId='stairs_a';result=core.validateBuildingSemantics(s,map);expect(result.errors.some(e=>e.code==='BUILDING_ENTRANCE_MUST_REFERENCE_DOOR')).toBe(true);});

test('multi-floor semantic building must own at least one vertical connector',()=>{const core=global.LuminousVttBuildingSemantics,map=mapBase(),s=validSemantics();s.buildings[0].verticalConnectorIds=[];const result=core.validateBuildingSemantics(s,map);expect(result.errors.some(e=>e.code==='BUILDING_VERTICAL_CONNECTOR_REQUIRED')).toBe(true);});

test('cross-access relations require a physical transition reference',()=>{const core=global.LuminousVttBuildingSemantics,map=mapBase(),s=validSemantics();delete s.relations[0].physicalRefId;const result=core.validateBuildingSemantics(s,map);expect(result.errors.some(e=>e.code==='BUILDING_ACCESS_TRANSITION_UNBACKED'&&e.relationId==='lobby_storage')).toBe(true);});

test('parent hierarchy cannot silently cross buildings',()=>{const core=global.LuminousVttBuildingSemantics,map=mapBase(),s=validSemantics();s.buildings.push({id:'building_b',label:'Building B',accessProfile:{requirePublicZone:false,requireControlledZone:false,requireEntrance:false,requirePublicEntrance:false}});s.areas.find(a=>a.id==='bedroom_101').buildingId='building_b';const result=core.validateBuildingSemantics(s,map);expect(result.errors.some(e=>e.code==='BUILDING_PARENT_OWNERSHIP_CONFLICT'&&e.entityId==='bedroom_101')).toBe(true);});

test('MapDefinition semantic persistence retains buildings through the semantic authoring patch contract',()=>{const source=fs.readFileSync(path.join(ROOT,'js/vtt/semantic-map-authoring-patch.js'),'utf8');expect(source).toContain('core.normalizeSemantics');const normalized=global.LuminousVttSemanticMap.normalizeSemantics(validSemantics());expect(normalized.buildings[0].id).toBe('building_a');});

test('runtime and authoring wire Building Semantics through the existing Semantic Map runtime without Firebase roots',()=>{const boot=fs.readFileSync(path.join(ROOT,'js/vtt/building-semantic-bootstrap.js'),'utf8'),author=fs.readFileSync(path.join(ROOT,'js/vtt/building-semantic-authoring-bootstrap.js'),'utf8'),semanticBoot=fs.readFileSync(path.join(ROOT,'js/vtt/semantic-map-bootstrap.js'),'utf8');expect(boot).toContain('buildingSemantics:api');expect(boot).toContain('entitiesByCapability');expect(author).toContain('ASSIGN SELECTED');expect(author).toContain('PUBLIC ZONE');expect(author).toContain('PRIVATE/SERVICE ZONE');expect(author).not.toContain('firebase');expect(semanticBoot).toContain("./building-semantic-bootstrap.js");expect(semanticBoot).toContain("./building-semantic-authoring-bootstrap.js");});

test('building semantic modules parse as JavaScript',()=>{for(const f of ['js/vtt/semantic-map-core.js','js/vtt/building-semantic-core.js'])execFileSync(process.execPath,['--check',path.join(ROOT,f)],{stdio:'pipe'});for(const f of ['js/vtt/building-semantic-bootstrap.js','js/vtt/building-semantic-authoring-bootstrap.js','js/vtt/semantic-map-bootstrap.js'])execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,f),'utf8'),stdio:['pipe','pipe','pipe']});});
