const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');
const KEYS = ['LuminousVttFloorOpenings','LuminousVttFloorOpeningSpatialPatch','LuminousVttFloorOpeningTerrainPatch','LuminousVttSpatialVision','LuminousVttSurfaceCore','LuminousVttMapAuthoring','LuminousVttSurfaceAuthoringPatch','LuminousVttStructureCore','LuminousVttStructureAuthoringPatch'];
const ORIGINAL = new Map(KEYS.map(key => [key, global[key]]));
function fresh(file){const resolved=require.resolve(path.join(ROOT,file));delete require.cache[resolved];return require(resolved);}
function reset(){for(const key of KEYS)delete global[key];}
function restore(){for(const key of KEYS){const value=ORIGINAL.get(key);if(value===undefined)delete global[key];else global[key]=value;}}
function mapBase(){return{id:'floor_openings',grid:{cols:8,rows:8,size:70,distancePerCell:5,distanceUnit:'ft'},defaultZStepFt:15,zLevels:{0:{zLayer:0,elevationFt:0,label:'Ground'},1:{zLayer:1,elevationFt:15,label:'Upper'}},surfaceLayers:{},movement:{terrain:{}},topology:[],structures:[],tokens:[],floorOpenings:[]};}

test.beforeEach(reset);
test.afterEach(restore);

test('floor opening core stores cell footprints, Z connection and support semantics',()=>{const core=fresh('js/vtt/floor-opening-core.js'),map=mapBase();const opening=core.createOpening({type:'stairwell',from:{col:2,row:2},to:{col:3,row:4},zLayer:1,toZLayer:0,mapData:map});expect(opening).toMatchObject({type:'stairwell',zLayer:1,toZLayer:0,between:[1,0],state:'open',fallThrough:true,allowsVisionThrough:true,allowsLightThrough:true});expect(opening.footprint).toEqual({minCol:2,minRow:2,maxCol:3,maxRow:4});expect(core.cellsFor(opening,map)).toHaveLength(6);map.floorOpenings=[opening];expect(core.supportAtCell(map,1,2,3).supported).toBe(false);expect(core.connects(opening,1,0)).toBe(true);});

test('closed trapdoor restores support and blocks cross-floor vision/light flags',()=>{const core=fresh('js/vtt/floor-opening-core.js'),map=mapBase();const trap=core.createOpening({type:'trapdoor',from:{col:2,row:2},to:{col:2,row:2},zLayer:1,toZLayer:0,mapData:map,state:'closed'});map.floorOpenings=[trap];expect(core.supportAtCell(map,1,2,2).supported).toBe(true);expect(core.allows(trap,'vision')).toBe(false);expect(core.allows(trap,'light')).toBe(false);expect(core.allows(trap,'fall')).toBe(false);});

test('unsupported floor cells project through existing terrain contract: walk avoids them, fly may cross',()=>{const core=fresh('js/vtt/floor-opening-core.js');global.LuminousVttFloorOpenings=core;const legacySurface=fresh('js/vtt/surface-core.js');global.LuminousVttSurfaceCore=legacySurface;const terrainPatch=fresh('js/vtt/floor-opening-terrain-patch.js');terrainPatch.install();const surface=global.LuminousVttSurfaceCore,map=mapBase();map.floorOpenings=[core.createOpening({type:'hole',from:{col:2,row:1},to:{col:2,row:1},zLayer:0,toZLayer:-1,mapData:map})];surface.ensureMapState(map);const pathfinding=fresh('js/vtt/pathfinding.js'),token={id:'walker',x:35,y:105,zLayer:0,radius:10};const center=pathfinding.pointForCell({col:2,row:1},map,0);expect(pathfinding.pointPassable(token,center,map,0,{movementMode:'walk'}).valid).toBe(false);expect(pathfinding.pointPassable(token,center,map,0,{movementMode:'fly'}).valid).toBe(true);const route=pathfinding.findPath({token,start:{col:0,row:1},target:{col:4,row:1},mapData:map,zLayer:0,movementMode:'walk',blockTokens:false});expect(route.valid).toBe(true);expect(route.cells).not.toContainEqual({col:2,row:1});});

test('surface edits beneath an active hole survive overlay resync and reappear when the hole is removed',()=>{const core=fresh('js/vtt/floor-opening-core.js');global.LuminousVttFloorOpenings=core;const legacySurface=fresh('js/vtt/surface-core.js');global.LuminousVttSurfaceCore=legacySurface;fresh('js/vtt/floor-opening-terrain-patch.js');const patched=global.LuminousVttSurfaceCore,map=mapBase();map.floorOpenings=[core.createOpening({type:'hole',from:{col:2,row:1},to:{col:2,row:1},zLayer:0,toZLayer:-1,mapData:map})];patched.ensureMapState(map);expect(map.movement.terrain['0']['2_1']._floorOpening).toBe(true);legacySurface.setCell(map,0,2,1,'mud');patched.syncFloorOpeningTerrain(map);expect(map.movement.terrain['0']['2_1']._floorOpening).toBe(true);map.floorOpenings=[];patched.syncFloorOpeningTerrain(map);expect(map.movement.terrain['0']['2_1']).toMatchObject({_surface:true,surfaceMaterialId:'mud',multiplier:2});});

test('spatial vision/light can traverse layers through footprint intersections, but not a closed trapdoor',()=>{const core=fresh('js/vtt/floor-opening-core.js');global.LuminousVttFloorOpenings=core;global.LuminousVttSpatialVision=fresh('js/vtt/spatial-vision.js');fresh('js/vtt/floor-opening-spatial-patch.js');const spatial=global.LuminousVttSpatialVision,map={...mapBase(),grid:{cols:8,rows:8,size:10,distancePerCell:5,distanceUnit:'ft'}};const hole=core.createOpening({type:'atrium',from:{col:2,row:2},to:{col:3,row:3},zLayer:1,toZLayer:0,mapData:map});map.floorOpenings=[hole];const viewer={x:5,y:25,zLayer:1,elevationFt:15},target={x:45,y:25};expect(spatial.canTraverseLayers(viewer,target,0,map,'vision')).toBe(true);expect(spatial.canTraverseLayers(viewer,target,0,map,'light')).toBe(true);map.floorOpenings=[core.createOpening({type:'trapdoor',from:{col:2,row:2},to:{col:3,row:3},zLayer:1,toZLayer:0,mapData:map,state:'closed'})];expect(spatial.canTraverseLayers(viewer,target,0,map,'vision')).toBe(false);});

test('MapDefinition round-trip preserves floor openings and floor deletion detects them',()=>{global.LuminousVttMapAuthoring=fresh('js/vtt/map-authoring.js');global.LuminousVttSurfaceCore=fresh('js/vtt/surface-core.js');fresh('js/vtt/surface-authoring-patch.js');global.LuminousVttStructureCore=fresh('js/vtt/structure-core.js');fresh('js/vtt/structure-authoring-patch.js');const core=fresh('js/vtt/floor-opening-core.js'),authoring=global.LuminousVttMapAuthoring,map=mapBase();map.floorOpenings=[core.createOpening({type:'stairwell',from:{col:2,row:2},to:{col:3,row:3},zLayer:1,toZLayer:0,mapData:map})];const definition=authoring.definitionFromMapData(map);expect(definition.floorOpenings).toHaveLength(1);const restored=mapBase();authoring.applyDefinition(restored,definition);expect(restored.floorOpenings).toHaveLength(1);const gate=authoring.canDeleteLevel(restored,1);expect(gate.valid).toBe(false);expect(gate.dependencies.floorOpenings).toHaveLength(1);});

test('Structure bootstrap composes floor opening physics/editor after Surface and exposes all DM tools',()=>{const structure=fs.readFileSync(path.join(ROOT,'js/vtt/structure-bootstrap.js'),'utf8'),bootstrap=fs.readFileSync(path.join(ROOT,'js/vtt/floor-opening-bootstrap.js'),'utf8'),authoring=fs.readFileSync(path.join(ROOT,'js/vtt/structure-authoring-patch.js'),'utf8');expect(structure).toContain("import './floor-opening-core.js'");expect(structure).toContain('startFloorOpenings');expect(structure).toContain('FloorOpeningTerrainPatch');expect(bootstrap).toContain('data-floor-opening-tool="stairwell"');expect(bootstrap).toContain('data-floor-opening-tool="trapdoor"');expect(bootstrap).toContain('vtt:surface-changed');expect(authoring).toContain('floorOpenings');});

test('floor opening modules parse as JavaScript',()=>{for(const file of ['js/vtt/floor-opening-core.js','js/vtt/floor-opening-spatial-patch.js','js/vtt/floor-opening-terrain-patch.js'])execFileSync(process.execPath,['--check',path.join(ROOT,file)],{stdio:'pipe'});execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,'js/vtt/floor-opening-bootstrap.js'),'utf8'),stdio:['pipe','pipe','pipe']});});
