const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const ROOT = path.resolve(__dirname, '..');
const KEYS=['LuminousVttSpatialVision','LuminousVttVerticalPortal','LuminousVttElevator','LuminousVttElevatorPortalPatch','LuminousVttRamp','LuminousVttRampPortalPatch','LuminousVttStairRoute','LuminousVttRampRoutePatch','LuminousVttVerticalMovement','LuminousVttRampMovementPatch','LuminousVttStairBuilder','LuminousVttStairBuilderRoutePatch','LuminousVttFloorOpenings','LuminousVttSurfaceCore','LuminousVttMapAuthoring','LuminousVttSurfaceAuthoringPatch','LuminousVttStructureCore','LuminousVttStructureAuthoringPatch','LuminousVttHorizontalPlanes','LuminousVttHorizontalPlaneAuthoringPatch','LuminousVttVerticalAuthoringPatch'];
const ORIGINAL=new Map(KEYS.map(k=>[k,global[k]]));
function fresh(file){const r=require.resolve(path.join(ROOT,file));delete require.cache[r];return require(r);}
function reset(){for(const k of KEYS)delete global[k];}
function restore(){for(const k of KEYS){const v=ORIGINAL.get(k);if(v===undefined)delete global[k];else global[k]=v;}}
function mapBase(){return{id:'ramp_test',grid:{cols:12,rows:12,size:10,distancePerCell:5,distanceUnit:'ft'},defaultZStepFt:15,zLevels:{0:{zLayer:0,elevationFt:0,label:'Ground'},1:{zLayer:1,elevationFt:15,label:'Upper'},2:{zLayer:2,elevationFt:30,label:'Top'}},surfaceLayers:{},movement:{terrain:{}},topology:[],verticalPortals:[],floorOpenings:[],structures:[],tokens:[]};}
function loadRamp(){global.LuminousVttSpatialVision=fresh('js/vtt/spatial-vision.js');global.LuminousVttVerticalPortal=fresh('js/vtt/vertical-portal.js');global.LuminousVttRamp=fresh('js/vtt/ramp-core.js');fresh('js/vtt/ramp-portal-patch.js').install();return{core:global.LuminousVttRamp,portal:global.LuminousVttVerticalPortal};}
function validRamp(core,map){return core.createRampPortal({from:{col:1,row:2},to:{col:7,row:2},fromZ:0,toZ:1,mapData:map,widthFt:5,maxGrade:.5});}
test.beforeEach(reset);test.afterEach(restore);

test('ramp is a first-class vertical portal with continuous 3D grade metrics',()=>{const{core,portal}=loadRamp(),map=mapBase(),ramp=validRamp(core,map);expect(ramp.type).toBe('ramp');expect(ramp.movementMode).toBe('walk');expect(ramp.horizontalRunFt).toBeCloseTo(30,6);expect(ramp.riseFt).toBeCloseTo(15,6);expect(ramp.grade).toBeCloseTo(.5,6);expect(ramp.gradePercent).toBeCloseTo(50,6);expect(ramp.pathLengthFt).toBeCloseTo(Math.hypot(30,15),6);expect(core.validate(ramp,map).valid).toBe(true);expect(portal.portalOnLayer(ramp,0)).toBe(true);expect(portal.portalOnLayer(ramp,1)).toBe(true);expect(portal.labelFor(ramp)).toBe('RAMPA');});

test('ramp rejects non-adjacent floors and slopes above configured grade',()=>{const{core}=loadRamp(),map=mapBase();const steep=core.createRampPortal({from:{col:1,row:2},to:{col:5,row:2},fromZ:0,toZ:1,mapData:map,maxGrade:.5});const steepGate=core.validate(steep,map);expect(steepGate.valid).toBe(false);expect(steepGate.reason).toBe('RAMP_TOO_STEEP');expect(steepGate.requiredRunFt).toBeCloseTo(30,6);const skipped=core.createRampPortal({from:{col:1,row:2},to:{col:10,row:2},fromZ:0,toZ:2,mapData:map,maxGrade:1});expect(core.validate(skipped,map).reason).toBe('RAMP_ADJACENT_FLOORS_REQUIRED');});

test('ramp route dispatcher is continuous and Stair Builder enrichment still composes afterward',()=>{const{core}=loadRamp(),map=mapBase(),ramp=validRamp(core,map);global.LuminousVttStairRoute=fresh('js/vtt/stair-route.js');fresh('js/vtt/ramp-route-patch.js').install();const before=global.LuminousVttStairRoute.routeFor(ramp,map);expect(before.layout).toBe('ramp');expect(before.points).toHaveLength(2);expect(before.pathLengthFt).toBeCloseTo(Math.hypot(30,15),6);global.LuminousVttStairBuilder=fresh('js/vtt/stair-builder.js');fresh('js/vtt/stair-builder-route-patch.js').install();const after=global.LuminousVttStairRoute.routeFor(ramp,map);expect(after.layout).toBe('ramp');expect(after.pathLengthFt).toBeCloseTo(before.pathLengthFt,6);});

test('VerticalMovement spends real 3D distance on ramp, supports partial progress/resume, and keeps walk mode',()=>{const{core}=loadRamp(),map=mapBase(),ramp=validRamp(core,map);global.LuminousVttStairRoute=fresh('js/vtt/stair-route.js');fresh('js/vtt/ramp-route-patch.js').install();global.LuminousVttVerticalMovement=fresh('js/vtt/vertical-movement.js');fresh('js/vtt/ramp-movement-patch.js').install();map.verticalPortals=[ramp];const movement=global.LuminousVttVerticalMovement,route=global.LuminousVttStairRoute.routeFor(ramp,map),token={id:'hero',x:10,y:20,zLayer:0,z:[0],gridPosition:{col:1,row:2,z:0},elevationFt:0,movementRemainingFt:10};const first=movement.traverse(token,{portal:ramp,route},map);expect(first.valid).toBe(true);expect(first.complete).toBe(false);expect(first.progressFt).toBeCloseTo(10,6);expect(token.zLayer).toBe(0);expect(token.elevationFt).toBeGreaterThan(0);expect(token.elevationFt).toBeLessThan(15);expect(token.verticalMovement.movementMode).toBe('walk');token.movementRemainingFt=30;const resumed=movement.transitionOnDrop(token,{x:token.x,y:token.y},map);expect(resumed.valid).toBe(true);expect(resumed.complete).toBe(true);expect(token.zLayer).toBe(1);expect(token.elevationFt).toBe(15);expect(token.lastVerticalTravel.costSpentFt).toBeCloseTo(route.pathLengthFt,6);});

test('RampMovement dynamically sees later Stair Builder route enrichment and never admits elevator portals',()=>{const{core}=loadRamp(),map=mapBase(),ramp=validRamp(core,map);global.LuminousVttStairRoute=fresh('js/vtt/stair-route.js');fresh('js/vtt/ramp-route-patch.js').install();global.LuminousVttVerticalMovement=fresh('js/vtt/vertical-movement.js');fresh('js/vtt/ramp-movement-patch.js').install();global.LuminousVttStairBuilder=fresh('js/vtt/stair-builder.js');fresh('js/vtt/stair-builder-route-patch.js').install();const stairs=global.LuminousVttStairBuilder.buildPortal({from:{col:1,row:4},to:{col:7,row:4},fromZ:0,toZ:1,mapData:map,layout:'straight'});map.verticalPortals=[ramp,stairs,{id:'lift',type:'elevator',between:[0,1],state:'open',allowsMovement:true}];const candidates=global.LuminousVttVerticalMovement.transitionCandidates(map,0);expect(candidates.map(c=>c.portal.type).sort()).toEqual(['ramp','stairs']);const stairCandidate=candidates.find(c=>c.portal.type==='stairs');expect(stairCandidate.route.points.length).toBeGreaterThan(2);});

test('derived ramp slab opening is deterministic, passes sight/light, and remains physically supported',()=>{const{core}=loadRamp(),map=mapBase(),ramp=validRamp(core,map),spec=core.openingSpec(ramp,map);expect(spec.id).toBe(`floor_ramp_${ramp.id}_1_0`);expect(spec).toMatchObject({type:'stairwell',between:[1,0],allowsMovementThrough:true,allowsVisionThrough:true,allowsLightThrough:true,fallThrough:false,walkable:true});global.LuminousVttFloorOpenings=fresh('js/vtt/floor-opening-core.js');map.floorOpenings=[global.LuminousVttFloorOpenings.normalizeOpening(spec,map)];const cell=map.floorOpenings[0].footprint;expect(global.LuminousVttFloorOpenings.supportAtCell(map,1,cell.minCol,cell.minRow).supported).toBe(true);global.LuminousVttSurfaceCore=fresh('js/vtt/surface-core.js');fresh('js/vtt/floor-opening-terrain-patch.js').install();global.LuminousVttSurfaceCore.ensureMapState(map);expect(map.movement.terrain['1']?.[`${cell.minCol}_${cell.minRow}`]?._floorOpening).not.toBe(true);});

test('MapDefinition round-trip preserves ramp metadata and its derived opening',()=>{const{core}=loadRamp(),map=mapBase(),ramp=validRamp(core,map);global.LuminousVttMapAuthoring=fresh('js/vtt/map-authoring.js');global.LuminousVttSurfaceCore=fresh('js/vtt/surface-core.js');fresh('js/vtt/surface-authoring-patch.js');global.LuminousVttStructureCore=fresh('js/vtt/structure-core.js');fresh('js/vtt/structure-authoring-patch.js');global.LuminousVttStairBuilder=fresh('js/vtt/stair-builder.js');fresh('js/vtt/vertical-authoring-patch.js').install();global.LuminousVttFloorOpenings=fresh('js/vtt/floor-opening-core.js');map.verticalPortals=[ramp];map.floorOpenings=[global.LuminousVttFloorOpenings.normalizeOpening(core.openingSpec(ramp,map),map)];const authoring=global.LuminousVttMapAuthoring,definition=authoring.definitionFromMapData(map);expect(definition.verticalPortals[0]).toMatchObject({type:'ramp',widthFt:5,maxGrade:.5,movementMode:'walk'});expect(definition.floorOpenings[0].id).toBe(`floor_ramp_${ramp.id}_1_0`);const restored=mapBase();authoring.applyDefinition(restored,definition);expect(restored.verticalPortals[0].type).toBe('ramp');expect(restored.verticalPortals[0].maxGrade).toBe(.5);expect(restored.floorOpenings).toHaveLength(1);expect(authoring.canDeleteLevel(restored,1).valid).toBe(false);});

test('DM authoring is axis-aligned, adjacent-floor only, persists a deterministic opening, and arbitrates other map tools',()=>{const html=fs.readFileSync(path.join(ROOT,'vtt.html'),'utf8'),authoring=fs.readFileSync(path.join(ROOT,'js/vtt/ramp-authoring-bootstrap.js'),'utf8');expect(authoring).toContain("axis(drawStart,candidate)");expect(authoring).toContain('adjacentTargets()');expect(authoring).toContain('RAMP_TOO_STEEP');expect(authoring).toContain('openingSpec(portal,mapData)');expect(authoring).toContain("LuminousVttElevatorAuthoringRuntime?.setTool?.('select')");expect(authoring).toContain('data-ramp-tool="ramp"');expect(html.indexOf('ramp-portal-patch.js')).toBeLessThan(html.indexOf('vertical-portal-state.js'));expect(html.indexOf('ramp-route-patch.js')).toBeLessThan(html.indexOf('vertical-movement.js'));expect(html.indexOf('ramp-movement-patch.js')).toBeLessThan(html.indexOf('main.js'));expect(html).toContain('ramp-autostart.js');expect(html).toContain('ramp-authoring-bootstrap.js');});

test('ramp modules parse as JavaScript',()=>{for(const file of ['js/vtt/ramp-core.js','js/vtt/ramp-portal-patch.js','js/vtt/ramp-route-patch.js','js/vtt/ramp-movement-patch.js','js/vtt/ramp-renderer-patch.js'])execFileSync(process.execPath,['--check',path.join(ROOT,file)],{stdio:'pipe'});for(const file of ['js/vtt/ramp-autostart.js','js/vtt/ramp-authoring-bootstrap.js'])execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,file),'utf8'),stdio:['pipe','pipe','pipe']});});
