const { test, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const GLOBAL_KEYS = ['LuminousVttVerticalPortal','LuminousVttStairBuilder','LuminousVttStairRoute','LuminousVttStairBuilderPortalPatch','LuminousVttStairBuilderRoutePatch','LuminousVttStairBuilderRendererPatch','LuminousVttMapAuthoring','LuminousVttSurfaceCore','LuminousVttSurfaceAuthoringPatch','LuminousVttStructureCore','LuminousVttStructureAuthoringPatch','LuminousVttVerticalAuthoringPatch'];
const ORIGINAL_GLOBALS = new Map(GLOBAL_KEYS.map((key) => [key, global[key]]));
function fresh(modulePath){const resolved=require.resolve(path.join(ROOT,modulePath));delete require.cache[resolved];return require(resolved);}
function resetGlobals(){for(const key of GLOBAL_KEYS)delete global[key];}
function restoreGlobals(){for(const key of GLOBAL_KEYS){const value=ORIGINAL_GLOBALS.get(key);if(value===undefined)delete global[key];else global[key]=value;}}
function mapBase(){return{id:'stair_builder_test',grid:{cols:20,rows:20,size:70,distancePerCell:5,distanceUnit:'ft'},defaultZStepFt:15,zLevels:{0:{zLayer:0,elevationFt:0,label:'Street'},1:{zLayer:1,elevationFt:15,label:'Upper'}},verticalPortals:[],topology:[],structures:[],surfaceLayers:{}};}
function loadBuilderRuntime(){global.LuminousVttVerticalPortal=fresh('js/vtt/vertical-portal.js');global.LuminousVttStairBuilder=fresh('js/vtt/stair-builder.js');fresh('js/vtt/stair-builder-portal-patch.js');global.LuminousVttStairRoute=fresh('js/vtt/stair-route.js');fresh('js/vtt/stair-builder-route-patch.js');return{portal:global.LuminousVttVerticalPortal,builder:global.LuminousVttStairBuilder,route:global.LuminousVttStairRoute};}

test.beforeEach(()=>resetGlobals());
test.afterEach(()=>restoreGlobals());

test('straight stair builder creates canonical definition metadata and explicit step progression',()=>{const{builder}=loadBuilderRuntime(),map=mapBase();const portal=builder.buildPortal({from:{col:2,row:2},to:{col:2,row:6},fromZ:0,toZ:1,mapData:map,layout:'straight',widthFt:5});expect(portal).toMatchObject({type:'stairs',layout:'straight',definitionId:'stairs:straight',widthFt:5});expect(portal.builder).toMatchObject({schemaVersion:1,stepCount:20,riseFt:15,horizontalRunFt:20,riserHeightFt:.75,treadDepthFt:1,railings:true});const points=builder.straightStepPoints(portal,map);expect(points).toHaveLength(21);expect(points[0]).toMatchObject({elevationFt:0,zLayer:0,stepIndex:0});expect(points.at(-1)).toMatchObject({elevationFt:15,zLayer:1,stepIndex:20});for(let i=1;i<points.length;i+=1)expect(points[i].elevationFt).toBeGreaterThan(points[i-1].elevationFt);});

test('builder-aware straight route preserves exact 3D movement length while exposing every tread point',()=>{const{builder,route}=loadBuilderRuntime(),map=mapBase();const portal=builder.buildPortal({from:{col:2,row:2},to:{col:2,row:6},fromZ:0,toZ:1,mapData:map});const built=route.routeFor(portal,map);expect(built.points).toHaveLength(21);expect(built.pathLengthFt).toBeCloseTo(25,5);expect(route.routeEntryForLayer(built,0).elevationFt).toBe(0);expect(route.routeEntryForLayer(built,1).elevationFt).toBe(15);const halfway=route.pointAtDistance(built,0,12.5,map);expect(halfway.elevationFt).toBeCloseTo(7.5,4);});

test('legacy stair portals remain valid and do not require builder metadata',()=>{const{portal,route}=loadBuilderRuntime(),map=mapBase();const legacy=portal.normalizePortal({id:'legacy',type:'stairs',between:[0,1],from:{col:2,row:2},to:{col:2,row:6},layout:'straight',widthFt:5,allowsMovement:true,state:'open'},map);const built=route.routeFor(legacy,map);expect(legacy.builder).toBeNull();expect(built.points).toHaveLength(2);expect(built.pathLengthFt).toBeCloseTo(25,5);});

test('stair construction geometry exposes footprint, entry/exit landings, treads and recommended railings',()=>{const{builder}=loadBuilderRuntime(),map=mapBase();const portal=builder.buildPortal({from:{col:2,row:2},to:{col:2,row:6},fromZ:0,toZ:1,mapData:map,widthFt:5});const geometry=builder.geometryFor(portal,map);expect(geometry.widthPx).toBeCloseTo(70,5);expect(geometry.footprint).toMatchObject({shape:'bounds'});expect(geometry.footprint.width).toBeCloseTo(70,5);expect(geometry.landings).toHaveLength(2);expect(geometry.entry.cell).toEqual({col:2,row:2});expect(geometry.exit.cell).toEqual({col:2,row:6});expect(geometry.treads).toHaveLength(21);expect(geometry.recommendedRailings).toHaveLength(2);});

test('existing vertical movement can stop and resume on a builder stair without a teleport',()=>{const{builder}=loadBuilderRuntime(),movement=fresh('js/vtt/vertical-movement.js'),map=mapBase();const portal=builder.buildPortal({from:{col:2,row:2},to:{col:2,row:6},fromZ:0,toZ:1,mapData:map});map.verticalPortals=[portal];const token={id:'walker',x:140,y:140,zLayer:0,z:[0],elevationFt:0,movementRemainingFt:10};const first=movement.transitionOnDrop(token,{x:140,y:140},map);expect(first.valid).toBe(true);expect(first.complete).toBe(false);expect(token.verticalMovement.routeId).toBe(portal.id);expect(token.elevationFt).toBeGreaterThan(0);const previous=token.verticalMovement.progressFt;token.movementRemainingFt=20;const second=movement.transitionOnDrop(token,{x:token.x,y:token.y},map);expect(second.valid).toBe(true);expect(second.resumed).toBe(true);expect(second.complete).toBe(true);expect(token.zLayer).toBe(1);expect(token.verticalMovement).toBeUndefined();expect(token.lastVerticalTravel.progressFt).toBeGreaterThan(previous);});

test('MapDefinition round-trip retains vertical portals and stair builder metadata through existing authoring patches',()=>{fresh('js/vtt/map-authoring.js');fresh('js/vtt/surface-core.js');fresh('js/vtt/surface-authoring-patch.js');fresh('js/vtt/structure-core.js');fresh('js/vtt/structure-authoring-patch.js');const{builder}=loadBuilderRuntime();const verticalPatch=fresh('js/vtt/vertical-authoring-patch.js');verticalPatch.install();const authoring=global.LuminousVttMapAuthoring,map=mapBase();map.verticalPortals=[builder.buildPortal({from:{col:2,row:2},to:{col:2,row:6},fromZ:0,toZ:1,mapData:map})];const definition=authoring.definitionFromMapData(map);expect(definition.verticalPortals).toHaveLength(1);expect(definition.verticalPortals[0]).toMatchObject({type:'stairs',definitionId:'stairs:straight'});expect(definition.verticalPortals[0].builder.stepCount).toBe(20);const restored=mapBase();restored.verticalPortals=[];authoring.applyDefinition(restored,definition);expect(restored.verticalPortals).toHaveLength(1);expect(restored.verticalPortals[0].builder.stepCount).toBe(20);const gate=authoring.canDeleteLevel(restored,1);expect(gate.valid).toBe(false);expect(gate.dependencies.portals).toHaveLength(1);});

test('stair renderer patch overlays construction footprint and tread guides without replacing base renderer',()=>{const{builder}=loadBuilderRuntime(),rendererPatch=fresh('js/vtt/stair-builder-renderer-patch.js'),map=mapBase();const portal=builder.buildPortal({from:{col:2,row:2},to:{col:2,row:6},fromZ:0,toZ:1,mapData:map});const counts={base:0,fill:0,line:0};const ctx={save(){},restore(){},fillRect(){counts.fill+=1;},setLineDash(){},beginPath(){},moveTo(){},lineTo(){counts.line+=1;},stroke(){},set globalAlpha(v){},set strokeStyle(v){},set fillStyle(v){},set lineWidth(v){}};const renderer={ctx,drawStairRouteGuide(){counts.base+=1;return true;}};const stop=rendererPatch.install(renderer,map);expect(renderer.drawStairRouteGuide(portal,0,{stroke:'#fff'},false)).toBe(true);expect(counts.base).toBe(1);expect(counts.fill).toBeGreaterThan(0);expect(counts.line).toBeGreaterThan(20);stop();});

test('vertical controller routes new stairs through StairBuilder while keeping the established Z tool contract',()=>{const controller=fs.readFileSync(path.join(ROOT,'js/vtt/vertical-portal-controller.js'),'utf8');expect(controller).toContain("import './stair-builder.js';");expect(controller).toContain("import './vertical-authoring-patch.js';");expect(controller).toContain('this.stairBuilder.buildPortal');expect(controller).toContain("const valid = ['select', 'opening', 'balcony_edge', 'stairs', 'erase']");expect(controller).toContain('this.stateBridge.savePortal(portal)');});
