const { test, expect } = require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..');
const FILES=['js/vtt/semantic-map-core.js','js/vtt/building-semantic-core.js','js/vtt/building-archetype-core.js'];
const KEYS=['LuminousVttSemanticMap','LuminousVttBuildingSemantics','LuminousVttBuildingArchetypes'];
const ORIGINAL=new Map(KEYS.map(k=>[k,global[k]]));
function fresh(file){const r=require.resolve(path.join(ROOT,file));delete require.cache[r];return require(r);}
function reset(){for(const k of KEYS)delete global[k];global.LuminousVttSemanticMap=fresh(FILES[0]);global.LuminousVttBuildingSemantics=fresh(FILES[1]);global.LuminousVttBuildingArchetypes=fresh(FILES[2]);}
function restore(){for(const f of FILES){try{delete require.cache[require.resolve(path.join(ROOT,f))];}catch(_){}}for(const k of KEYS){const v=ORIGINAL.get(k);if(v===undefined)delete global[k];else global[k]=v;}}
function map(){return{grid:{cols:30,rows:30,size:70,distancePerCell:5},zLevels:{'0':{zLayer:0},'1':{zLayer:1}},topology:[{id:'front_door',type:'door',from:{col:1,row:1},to:{col:2,row:1},z:[0]},{id:'staff_door',type:'door',from:{col:5,row:2},to:{col:5,row:3},z:[0]},{id:'apt0_door',type:'door',from:{col:5,row:10},to:{col:5,row:11},z:[0]},{id:'apt1_door',type:'door',from:{col:5,row:10},to:{col:5,row:11},z:[1]}],verticalPortals:[{id:'stairs_a',type:'stairs',between:[0,1],from:{col:3,row:10},to:{col:3,row:10}}]};}
function shop(){return{buildings:[{id:'shop_b',label:'Shop B',archetypeId:'shop',defaultAccess:'semi_public'}],areas:[{id:'shop_floor',buildingId:'shop_b',label:'Sales Floor',spatialType:'room',functionalType:'shop',access:'public',zLayer:0,geometry:{minCol:1,minRow:1,maxCol:4,maxRow:4},capabilities:['buy','sell']},{id:'shop_storage',buildingId:'shop_b',label:'Storage',spatialType:'room',functionalType:'storage',access:'service',zLayer:0,geometry:{minCol:5,minRow:1,maxCol:8,maxRow:4},roles:['shop_inventory'],capabilities:['store_items']}],points:[{id:'shop_entrance',buildingId:'shop_b',parentId:'shop_floor',type:'entrance',access:'public',zLayer:0,position:{col:1,row:2},physicalRefId:'front_door'},{id:'service_access',buildingId:'shop_b',parentId:'shop_storage',type:'service_access',access:'service',zLayer:0,position:{col:7,row:2}}],relations:[{id:'shop_to_storage',type:'connects',fromId:'shop_floor',toId:'shop_storage',physicalRefId:'staff_door',bidirectional:true},{id:'service_to_storage',type:'connects',fromId:'service_access',toId:'shop_storage',bidirectional:true}]};}
function apartments(){return{buildings:[{id:'apt_b',label:'Apartment B',archetypeId:'apartment_building',defaultAccess:'semi_public',verticalConnectorIds:['stairs_a']}],areas:[{id:'hall0',buildingId:'apt_b',spatialType:'hallway',functionalType:'circulation',access:'semi_public',zLayer:0,geometry:{minCol:1,minRow:9,maxCol:4,maxRow:11},allowTopologyIds:['apt0_door']},{id:'apt101',buildingId:'apt_b',spatialType:'room',functionalType:'apartment',access:'private',zLayer:0,geometry:{minCol:5,minRow:9,maxCol:8,maxRow:12}},{id:'hall1',buildingId:'apt_b',spatialType:'hallway',functionalType:'circulation',access:'semi_public',zLayer:1,geometry:{minCol:1,minRow:9,maxCol:4,maxRow:11},allowTopologyIds:['apt1_door']},{id:'apt201',buildingId:'apt_b',spatialType:'room',functionalType:'apartment',access:'private',zLayer:1,geometry:{minCol:5,minRow:9,maxCol:8,maxRow:12}}],points:[{id:'apt_entrance',buildingId:'apt_b',parentId:'hall0',type:'entrance',access:'public',zLayer:0,position:{col:1,row:10},physicalRefId:'front_door'}],relations:[{id:'hall0_apt101',type:'connects',fromId:'hall0',toId:'apt101',physicalRefId:'apt0_door',bidirectional:true},{id:'hall0_hall1',type:'connects',fromId:'hall0',toId:'hall1',physicalRefId:'stairs_a',bidirectional:true},{id:'hall1_apt201',type:'connects',fromId:'hall1',toId:'apt201',physicalRefId:'apt1_door',bidirectional:true}]};}
test.beforeEach(reset);test.afterEach(restore);

test('built-in catalog exposes generator contracts by requirement tier',()=>{const core=global.LuminousVttBuildingArchetypes;expect(core.listArchetypes().map(a=>a.id)).toEqual(expect.arrayContaining(['shop','apartment_building','workshop','warehouse']));const c=core.generatorContract('shop');expect(c.required.length).toBeGreaterThanOrEqual(4);expect(c.preferred.some(r=>r.id==='service_access')).toBe(true);expect(c.forbidden.some(r=>r.id==='public_storage_forbidden')).toBe(true);});

test('valid shop satisfies required storage, public frontage and internal reachability',()=>{const core=global.LuminousVttBuildingArchetypes,result=core.validateBuildingArchetype(shop(),'shop_b',map());expect(result.valid).toBe(true);expect(result.errors).toEqual([]);expect(result.completionScore).toBe(1);});

test('shop without storage fails a generic required component contract',()=>{const core=global.LuminousVttBuildingArchetypes,s=shop();s.areas=s.areas.filter(a=>a.id!=='shop_storage');s.points=s.points.filter(p=>p.id!=='service_access');s.relations=[];const result=core.validateBuildingArchetype(s,'shop_b',map());expect(result.valid).toBe(false);expect(result.errors.some(e=>e.code==='ARCHETYPE_REQUIRED_COMPONENT_MISSING'&&e.requirementId==='controlled_storage')).toBe(true);});

test('shop storage cannot be public even when storage exists',()=>{const core=global.LuminousVttBuildingArchetypes,s=shop();s.areas.find(a=>a.id==='shop_storage').access='public';const result=core.validateBuildingArchetype(s,'shop_b',map());expect(result.valid).toBe(false);expect(result.errors.some(e=>e.code==='ARCHETYPE_FORBIDDEN_COMPONENT_PRESENT'&&e.requirementId==='public_storage_forbidden')).toBe(true);});

test('required reachability catches isolated shop storage without inventing a route',()=>{const core=global.LuminousVttBuildingArchetypes,s=shop();s.relations=s.relations.filter(r=>r.id!=='shop_to_storage');const result=core.validateBuildingArchetype(s,'shop_b',map());expect(result.errors.some(e=>e.code==='ARCHETYPE_REQUIRED_REACHABILITY_MISSING'&&e.requirementId==='storage_reachable')).toBe(true);});

test('apartment archetype validates private dwellings, shared circulation and multi-Z vertical access',()=>{const core=global.LuminousVttBuildingArchetypes,s=apartments(),result=core.validateBuildingArchetype(s,'apt_b',map());expect(result.valid).toBe(true);expect(result.evaluations.find(e=>e.requirement.id==='vertical_access').satisfied).toBe(true);expect(result.evaluations.find(e=>e.requirement.id==='apartments_reachable').matchedIds.sort()).toEqual(['apt101','apt201']);});

test('multi-floor apartment without connector fails archetype vertical-access contract',()=>{const core=global.LuminousVttBuildingArchetypes,s=apartments();s.buildings[0].verticalConnectorIds=[];const result=core.validateBuildingArchetype(s,'apt_b',map());expect(result.errors.some(e=>e.code==='ARCHETYPE_VERTICAL_ACCESS_REQUIRED')).toBe(true);});

test('all-target reachability rejects one unreachable private apartment',()=>{const core=global.LuminousVttBuildingArchetypes,s=apartments();s.relations=s.relations.filter(r=>r.id!=='hall1_apt201');const result=core.validateBuildingArchetype(s,'apt_b',map());expect(result.errors.some(e=>e.code==='ARCHETYPE_REQUIRED_REACHABILITY_MISSING'&&e.requirementId==='apartments_reachable')).toBe(true);});

test('preferred requirements warn without invalidating a workshop',()=>{const core=global.LuminousVttBuildingArchetypes,s=shop();s.buildings[0]={...s.buildings[0],id:'work_b',archetypeId:'workshop'};s.areas=s.areas.map(a=>({...a,buildingId:'work_b'}));s.points=s.points.filter(p=>p.type==='entrance').map(p=>({...p,buildingId:'work_b'}));s.relations=[{id:'work_storage',type:'connects',fromId:'shop_floor',toId:'shop_storage',physicalRefId:'staff_door',bidirectional:true}];s.areas.find(a=>a.id==='shop_floor').functionalType='workshop';const result=core.validateBuildingArchetype(s,'work_b',map());expect(result.valid).toBe(true);expect(result.warnings.some(w=>w.code==='ARCHETYPE_PREFERRED_COMPONENT_MISSING'&&w.requirementId==='service_access')).toBe(true);expect(result.completionScore).toBeLessThan(1);});

test('warehouse requires a loading/service point and route to controlled storage',()=>{const core=global.LuminousVttBuildingArchetypes,s=shop();s.buildings[0].archetypeId='warehouse';s.areas=s.areas.filter(a=>a.id==='shop_storage');s.points=s.points.filter(p=>p.id==='service_access');s.relations=[{id:'load_storage',type:'connects',fromId:'service_access',toId:'shop_storage',bidirectional:true}];let result=core.validateBuildingArchetype(s,'shop_b',map());expect(result.valid).toBe(true);s.points=[];s.relations=[];result=core.validateBuildingArchetype(s,'shop_b',map());expect(result.errors.some(e=>e.requirementId==='loading_access')).toBe(true);});

test('custom archetypes use the same generic cardinality and forbidden validator',()=>{const core=global.LuminousVttBuildingArchetypes;core.registerArchetype({id:'security_post',requirements:[{id:'security_room',level:'required',kind:'presence',selector:{kind:'area',functionalType:'security'},min:1,max:1},{id:'no_public_storage',level:'forbidden',kind:'presence',selector:{kind:'area',functionalType:'storage',access:'public'},max:0}]});const s=shop();s.buildings[0].archetypeId='security_post';s.areas.find(a=>a.id==='shop_floor').functionalType='security';let result=core.validateBuildingArchetype(s,'shop_b',map());expect(result.valid).toBe(true);s.areas.push({...s.areas[0],id:'security_2'});result=core.validateBuildingArchetype(s,'shop_b',map());expect(result.errors.some(e=>e.code==='ARCHETYPE_CARDINALITY_EXCEEDED')).toBe(true);});

test('validateAll combines Building Semantic validity with archetype validity and leaves unassigned buildings as warnings',()=>{const core=global.LuminousVttBuildingArchetypes,s=shop(),m=map();let result=core.validateAllBuildingArchetypes(s,m);expect(result.valid).toBe(true);expect(result.summary.archetyped).toBe(1);s.buildings[0].archetypeId=null;result=core.validateAllBuildingArchetypes(s,m);expect(result.valid).toBe(true);expect(result.warnings.some(w=>w.code==='BUILDING_ARCHETYPE_UNASSIGNED')).toBe(true);});

test('runtime and DM authoring expose archetype selection, validation and generator contracts',()=>{const runtime=fs.readFileSync(path.join(ROOT,'js/vtt/building-archetype-bootstrap.js'),'utf8'),author=fs.readFileSync(path.join(ROOT,'js/vtt/building-archetype-authoring-bootstrap.js'),'utf8'),semanticBoot=fs.readFileSync(path.join(ROOT,'js/vtt/semantic-map-bootstrap.js'),'utf8');expect(runtime).toContain('generatorContract');expect(runtime).toContain('validateBuilding');expect(runtime).toContain('validateAll');expect(author).toContain('BUILDING TYPE');expect(author).toContain('VALIDATE');expect(author).not.toContain('firebase');expect(semanticBoot).toContain('startBuildingArchetypes');expect(semanticBoot).toContain('startBuildingArchetypeAuthoring');});

test('building archetype modules parse as JavaScript',()=>{execFileSync(process.execPath,['--check',path.join(ROOT,'js/vtt/building-archetype-core.js')],{stdio:'pipe'});for(const f of ['js/vtt/building-archetype-bootstrap.js','js/vtt/building-archetype-authoring-bootstrap.js','js/vtt/semantic-map-bootstrap.js'])execFileSync(process.execPath,['--input-type=module','--check'],{input:fs.readFileSync(path.join(ROOT,f),'utf8'),stdio:['pipe','pipe','pipe']});});
