(()=>{'use strict';
const $=id=>document.getElementById(id),engine=$('engine');
const lessons={
fundamentals:[
{id:'hud',title:'HUD de unidad',type:'Fundamento',one:'Antes de entender una Skill, aprende a leer la unidad.',watch:'HP y Stagger Thresholds viven en el heptágono. Speed y Action Slot están arriba. SP está en el orbe lateral.',meaning:'Cada pieza del HUD representa una regla de combate. En el Dummy no ocultamos información.',dont:'El número grande de HP no es el Stagger Threshold: las marcas sobre la línea de HP son los Thresholds.',steps:['La escena deja solo a Don y al Training Dummy.','Se resaltan HP, Speed/Action Slot y SP.','Nada del Dummy queda oculto.'],demo:'hud'},
{id:'sp',title:'SP y Heads',type:'Fundamento',one:'SP cambia la probabilidad de Heads de las Coins.',watch:'Mira el orbe de SP de Don y la Coin que aparece junto a ella.',meaning:'Heads % = 50 + SP. Por eso +25 SP equivale a 75% Heads.',dont:'SP no es HP. Perder SP no significa haber recibido daño físico.',steps:['Don comienza en 0 SP = 50% Heads.','Sube a +25 SP = 75%.','Se muestra una Coin Heads con el arte del alpha.'],demo:'sp'},
{id:'threshold',title:'Stagger Threshold',type:'Fundamento',one:'Un Stagger Threshold es una marca de HP que puede activar Stagger al cruzarse.',watch:'Mira las tres marcas sobre la línea de HP del Dummy.',meaning:'Las marcas representan porcentajes del Max HP. El ejemplo cruza el Threshold de 70%.',dont:'El Threshold no es otra barra de vida y moverlo no equivale a hacer daño.',steps:['Dummy queda apenas arriba del 70%.','Recibe daño y cruza la marca.','La marca se consume y aparece STAGGER.'],demo:'threshold'}],
combat:[
{id:'coin',title:'Coin',type:'Combate',one:'Una Coin determina cuánto Power añade una Skill cuando sale Heads.',watch:'Mira la Coin, el Power y el Coin Power dentro del HUD de Skill.',meaning:'Heads añade Coin Power en una Coin positiva; Tails no lo añade.',dont:'Heads no significa automáticamente “acertar”. Primero cambia el Power.',steps:['Skill base 5, Coin Power +3.','La Coin gira.','Heads deja el Power en 8.'],demo:'coin'},
{id:'clash',title:'Clash',type:'Combate',one:'Un Clash enfrenta dos Skills antes de que exista daño.',watch:'Mira cómo ambas unidades avanzan al punto medio y aparece el HUD flotante de Skill en cada una.',meaning:'Se comparan Powers. El lado que pierde una ronda pierde una Coin; el daño viene después.',dont:'Clash no es Hit.',steps:['Ambas unidades avanzan.','Aparecen los dos HUD flotantes.','Se resuelve una Coin por lado.','El perdedor pierde una Coin y retrocede.'],demo:'clash'},
{id:'onhit',title:'Hit y [On Hit]',type:'Combate',one:'Hit es el golpe que conectó; [On Hit] es una regla que ocurre después.',watch:'Primero baja HP; después aparece Sinking.',meaning:'El orden visual importa: daño del Hit primero, trigger después.',dont:'[On Hit] no ocurre durante el Clash.',steps:['Don conecta un Hit.','El Dummy pierde HP.','Después se aplica Sinking 10 / 2.'],demo:'onhit'}],
statuses:[
{id:'burn',title:'Burn (Quemadura)',type:'Estado negativo',one:'Burn espera a Turn End: hace Fixed Damage igual a Potency y pierde 1 Count.',watch:'Mira Burn y el HP del Dummy.',meaning:'Potency dice cuánto daño; Count cuántas activaciones quedan.',dont:'Burn no necesita Coin. Eso es Bleed.',steps:['Burn 12 / 3.','HP no cambia al aplicarlo.','Turn End: -12 HP y Count 3 → 2.'],demo:'burn'},
{id:'bleed',title:'Bleed (Sangrado)',type:'Estado negativo',one:'Bleed daña a la unidad que tiene Bleed cuando esa unidad resuelve una Coin de ataque.',watch:'Bleed está en Don. Mira su HP durante SU Coin; luego el Hit al Dummy.',meaning:'Fixed Damage = Potency y consume 1 Count.',dont:'No confundas Bleed sobre Don con el daño de la Skill al Dummy.',steps:['Don recibe Bleed 8 / 3.','Don lanza una Coin.','Bleed daña a Don.','Después la Skill golpea al Dummy.'],demo:'bleed'},
{id:'sinking',title:'Sinking (Hundimiento)',type:'Estado negativo',one:'Sinking reacciona después de recibir un Hit y reduce SP.',watch:'Mira primero HP y luego el orbe SP.',meaning:'Potency se convierte en SP Damage y Count baja.',dont:'Sinking no reemplaza el daño del Hit.',steps:['Dummy +25 SP, Sinking 10 / 2.','Recibe Hit.','SP 25 → 15 y Count 2 → 1.'],demo:'sinking'},
{id:'tremor',title:'Tremor (Temblor)',type:'Estado negativo',one:'Tremor Burst mueve Stagger Thresholds; no baja HP por sí solo.',watch:'Mira las marcas, no el número de HP.',meaning:'Burst usa Potency para acercar Thresholds al HP actual y consume Count.',dont:'Mover un Threshold no es daño.',steps:['Tremor 25 / 2.','HP no cambia.','Burst mueve las marcas y Count baja.'],demo:'tremor'},
{id:'poise',title:'Poise (Aplomo)',type:'Estado positivo',one:'Poise puede producir Critical Hit; el crítico debe verse distinto a Burn o Bleed.',watch:'Mira Poise, la Coin y CRITICAL ×1.2.',meaning:'La demo fuerza el Crit para enseñar la señal visual y el aumento de daño.',dont:'Critical no es ganar un Clash.',steps:['Don recibe Poise 20 / 3.','La Skill conecta.','Aparece CRITICAL ×1.2 y 24 de daño.','Poise Count baja.'],demo:'poise'}],
glossary:[{id:'terms',title:'Vocabulario mínimo',type:'Glosario',one:'Power, Coin, Clash, Hit y Trigger son las cinco palabras que debes reconocer primero.',watch:'Usa la escena como referencia.',meaning:'Power compite o golpea. Coin modifica Power. Clash compara Skills. Hit es el golpe que conectó. Trigger indica cuándo se ejecuta una regla.',dont:'Potency y Count no significan exactamente lo mismo para todos los estados.',steps:['Power: valor de resolución.','Coin: tirada individual.','Clash: oposición.','Hit: golpe conectado.','Trigger: momento de activación.'],demo:'hud'}]};
let section='fundamentals',lessonIndex=0,stageReady=false;
function current(){return lessons[section][lessonIndex]}
function coach(title,copy){$('coach').innerHTML=`<b>${title}</b><span>${copy}</span>`}
function renderTabs(){document.querySelectorAll('.section-tab').forEach(b=>b.classList.toggle('active',b.dataset.section===section));const host=$('lesson-list');host.innerHTML=lessons[section].map((l,i)=>`<button class="lesson-chip${i===lessonIndex?' active':''}" data-i="${i}">${l.title}</button>`).join('');host.querySelectorAll('.lesson-chip').forEach(b=>b.addEventListener('click',()=>{lessonIndex=Number(b.dataset.i);renderLesson();resetStage()}))}
function renderLesson(){const l=current();$('lesson-index').textContent=String(lessonIndex+1).padStart(2,'0');$('lesson-type').textContent=l.type;$('lesson-title').textContent=l.title;$('one-line').textContent=l.one;$('watch').textContent=l.watch;$('meaning').textContent=l.meaning;$('dont-confuse').textContent=l.dont;$('steps').innerHTML=l.steps.map(x=>`<li>${x}</li>`).join('');$('source-note').textContent='Hotfix de campo · escena aislada basada en HUD/Coins/Clash del alpha v0.7.3.';$('stage-label').textContent=l.title;renderTabs();coach(`Seleccionaste ${l.title}`,l.watch)}
function stage(){try{return engine.contentWindow?.CodexStage||null}catch{return null}}
function resetStage(){const api=stage();if(api?.ready){api.reset();stageReady=true}else{stageReady=false;coach('Cargando escena','La escena de entrenamiento todavía está iniciando.')}}
async function play(){const api=stage();if(!api?.ready){coach('Escena no disponible','Pulsa Reiniciar escena; si persiste, reporta este estado.');return}stageReady=true;$('play-demo').disabled=true;try{await api.play(current().demo)}catch(error){console.error('[Game Codex]',error);coach('Error de demo',error?.message||String(error))}finally{$('play-demo').disabled=false}}
window.addEventListener('message',event=>{const data=event.data||{};if(data.type==='codex-stage-ready'){stageReady=true;coach('Escena lista','Puedes ejecutar la lección con Ver en combate.')}if(data.type==='codex-stage-event')coach(data.title||'Evento',data.copy||'')});
engine.addEventListener('load',()=>setTimeout(resetStage,50));
document.querySelectorAll('.section-tab').forEach(b=>b.addEventListener('click',()=>{section=b.dataset.section;lessonIndex=0;renderLesson();resetStage()}));
$('reset-demo').addEventListener('click',resetStage);$('play-demo').addEventListener('click',play);renderLesson();
})();