(()=>{'use strict';
const $=id=>document.getElementById(id),engine=$('engine');
const lessons={
fundamentals:[
{id:'hud',title:'HUD de unidad',type:'Fundamento',one:'El HUD de una unidad te dice de un vistazo qué puede hacer y qué tan cerca está de quedar Staggered.',watch:'Mira el heptágono del piso, la línea de HP, las marcas blancas, el número de Speed, el Action Slot, el HP numérico, el orbe de SP y la tira de estados.',meaning:'El motor usa el mismo HUD para aliados y enemigos. No es decoración: cada pieza corresponde a una regla que puede cambiar durante el turno.',dont:'No confundas el número grande de HP con la línea de HP: las marcas de Stagger viven sobre la trayectoria del HP.',steps:['Se aíslan Don Quixote y el Training Dummy.','Se dejan visibles HP, SP, Speed, Action Slot, Thresholds y estados.','La cámara queda en vista completa para poder comparar ambos HUD.'],demo:'hud',source:'Fuente: spawnCombatant() + HUD diegetic-floor/top-ui-panel/floating-hp-group/floating-sp-group/status-effect-strip del alpha v0.7.3.'},
{id:'sp',title:'SP y Heads',type:'Fundamento',one:'SP no es vida: cambia la probabilidad de obtener Heads en tus Coins.',watch:'Mira el orbe de SP de Don y luego las Coins del Skill HUD cuando se resuelve una acción.',meaning:'El motor calcula Heads % a partir del SP de la unidad. Por eso subir o bajar SP cambia cuántas veces una Skill obtiene su Coin Power.',dont:'Perder SP no baja HP. Puede hacer que tus Skills sean menos consistentes sin haberte herido.',steps:['Don empieza en 0 SP.','El demo cambia a +25 SP.','Después ejecuta una Skill de 1 Coin con el HUD real para mostrar la tirada.'],demo:'sp',source:'Fuente: LuminousCombatHUD.setSP / coinHeadsChance y LuminousCoinEngine del alpha v0.7.3.'},
{id:'threshold',title:'Stagger Threshold',type:'Fundamento',one:'Las marcas blancas sobre la línea de HP son puntos que, al cruzarse hacia abajo, activan una etapa de Stagger.',watch:'Fíjate en las tres marcas sobre el HP del Dummy y en cómo desaparece una cuando se cruza.',meaning:'Los Thresholds son porcentajes del Max HP. El motor comprueba el cruce durante la animación de daño; una marca consumida no vuelve a activarse.',dont:'Stagger Threshold no es una segunda barra de vida y Tremor no “hace daño” al moverla.',steps:['El Dummy se coloca justo por encima del primer Threshold.','Recibe daño real mediante LuminousCombatHUD.damage.','Al cruzar la marca, el motor muestra su Stagger UI y consume el Threshold.'],demo:'threshold',source:'Fuente: triggerStaggerThreshold() y scheduleCrossedStaggerThresholds() del alpha v0.7.3.'}
],
combat:[
{id:'coin',title:'Coin',type:'Combate',one:'Una Coin es una tirada dentro de una Skill; Heads y Tails cambian el Power según el Coin Power de esa Skill.',watch:'Mira el Skill HUD flotante: nombre, Power, Coin Power, Coins restantes y la Coin que está resolviendo.',meaning:'En Skills de Coin positiva, Heads añade Coin Power. Las Coins también pueden tener sus propios efectos [On Hit], [Heads Hit], [Tails Hit] o [On Crit].',dont:'Heads no significa automáticamente “acierto” y Tails no significa automáticamente “fallo”. Primero determina Power; luego el motor resuelve Clash o Hit.',steps:['Se ejecuta una Skill real de una Coin.','El HUD muestra la Coin actual y su resultado.','Después la Coin restante pasa al Hit contra el Dummy.'],demo:'coin',source:'Fuente: animateSkillCoinRoll(), setFloatingCoinDetail() y resolveRemainingCoinHits() del alpha v0.7.3.'},
{id:'clash',title:'Clash',type:'Combate',one:'Un Clash ocurre cuando dos Skills se enfrentan: ambas unidades se acercan, tiran sus Coins y el lado con menor Power pierde una Coin.',watch:'Mira cómo Don y el Dummy se mueven al punto de Clash y cómo aparece un Skill HUD flotante junto a cada unidad.',meaning:'El motor repite rondas de Clash hasta que un lado se queda sin Coins. El ganador conserva las Coins que le queden y luego las usa para golpear.',dont:'El Clash no es el daño. Primero decide quién gana la oposición; después comienza la secuencia de Hits.',steps:['Ambas unidades avanzan con moveClashUnitsToMidpoint().','Los dos Skill HUD muestran Power y Coins.','El perdedor va consumiendo Coins.','El ganador hace sus Hits restantes y ambos vuelven a su posición de combate.'],demo:'clash',source:'Fuente: resolveSkillClash(), moveClashUnitsToMidpoint(), animateClashContact() y clash-float-hud del alpha v0.7.3.'},
{id:'onhit',title:'Hit y [On Hit]',type:'Combate',one:'Un Hit es el golpe que ya conectó; [On Hit] es un efecto que el motor ejecuta después del daño de esa Coin.',watch:'Primero observa el popup de daño del Hit; después mira aparecer el estado aplicado por el efecto [On Hit].',meaning:'El orden importa: el motor hace daño, procesa estados que reaccionan al ser golpeado y después aplica los efectos [On Hit] de la Coin.',dont:'[On Hit] no es el momento del Clash ni el lanzamiento de la Coin.',steps:['Don usa una Skill con [On Hit] Sinking.','La Coin conecta y hace daño.','Después se aplica Sinking al Dummy.'],demo:'onhit',source:'Fuente: resolveRemainingCoinHits(): damageCombatant → triggerGettingHitStatuses → applySkillStatusEffects([On Hit]).'}
],
statuses:[
{id:'burn',title:'Burn (Quemadura)',type:'Estado negativo',one:'Burn espera al final del turno: entonces hace daño fijo igual a Potency y pierde 1 Count.',watch:'Mira el icono de Burn en el Dummy y su HP. Al activar Turn End, el daño aparece con el icono del estado.',meaning:'Potency responde “cuánto daño”; Count responde “cuántas activaciones quedan”. Aplicarlo no causa daño inmediatamente.',dont:'No funciona como Bleed: Burn no necesita que la unidad lance una Coin.',steps:['Se aplica Burn 12 / 3 con el runtime real.','No cambia el HP todavía.','Se ejecuta processStatusRoundEnd().','El Dummy recibe 12 Fixed Damage y Burn pierde 1 Count.'],demo:'burn',source:'Fuente: STATUS_CORE_REGISTRY.burn y processStatusRoundEnd() del alpha v0.7.3.'},
{id:'bleed',title:'Bleed (Sangrado)',type:'Estado negativo',one:'Bleed daña a la unidad que tiene Bleed cuando resuelve una Coin de ataque.',watch:'En esta demo Bleed está en Don. Mira su HP durante la tirada de su propia Coin y luego mira, por separado, el Hit al Dummy.',meaning:'El daño de Bleed es fijo, igual a Potency, y consume 1 Count. El alpha evita que ese daño cruce Stagger Thresholds.',dont:'No confundas el daño de Bleed sobre el atacante con el daño de la Skill sobre el objetivo.',steps:['Don recibe Bleed 8 / 3.','Don ejecuta una Skill real de una Coin.','Durante la resolución de esa Coin, Bleed daña a Don.','Después la misma Skill continúa y golpea al Dummy.'],demo:'bleed',source:'Fuente: triggerBleedOnCoinFlip() dentro de animateSkillCoinRoll() del alpha v0.7.3.'},
{id:'sinking',title:'Sinking (Hundimiento)',type:'Estado negativo',one:'Sinking reacciona después de que la unidad recibe un Hit: si tiene SP, reduce SP igual a Potency y consume Count.',watch:'Mira primero el daño normal al HP del Dummy y después el cambio separado en su orbe de SP.',meaning:'Esto conecta directamente con la lección de SP: bajar SP también cambia la probabilidad de Heads de esa unidad.',dont:'Sinking no reemplaza el daño normal del Hit. En el motor ocurre después del daño y antes de los nuevos estados [On Hit].',steps:['Dummy empieza con 25 SP y Sinking 10 / 2.','Don conecta un Hit real.','Después del daño, Sinking baja SP 25 → 15 y pierde 1 Count.'],demo:'sinking',source:'Fuente: triggerGettingHitStatuses() → triggerSinkingOnHit() dentro de resolveRemainingCoinHits().'},
{id:'tremor',title:'Tremor (Temblor)',type:'Estado negativo',one:'Tremor no baja HP por sí solo: Tremor Burst usa Potency para mover los Stagger Thresholds restantes.',watch:'Mira las marcas blancas del HP del Dummy, no el número de HP.',meaning:'El Burst convierte Potency a una fracción del Max HP y eleva las marcas. Si una marca alcanza el porcentaje de HP actual, puede provocar Stagger sin daño.',dont:'Mover un Threshold no es daño y no debe verse como un popup de HP.',steps:['Se aplica Tremor 25 / 2.','El HP se mantiene igual.','Se ejecuta tremorBurst().','Las marcas se desplazan y Tremor pierde 1 Count.'],demo:'tremor',source:'Fuente: triggerTremorBurst() del alpha v0.7.3.'},
{id:'poise',title:'Poise (Aplomo)',type:'Estado positivo',one:'Poise añade probabilidad de Critical Hit según Potency; un crítico usa el multiplicador crítico del motor y consume Count.',watch:'Mira Poise en Don, el Skill HUD y el popup de daño del Hit. La demo usa Potency 20 para que el crítico sea 100% y pueda verse sin azar.',meaning:'En el alpha, Crit Chance = Potency × 5%, limitado a 100%. El daño crítico base usa ×1.2.',dont:'Poise no aumenta automáticamente Final Power y un crítico no es lo mismo que ganar un Clash.',steps:['Don recibe Poise 20 / 3.','Ejecuta una Skill real contra el Dummy.','El Hit es crítico con la lógica del motor.','Poise consume 1 Count.'],demo:'poise',source:'Fuente: statusCritChance(), rollCriticalHit() y damageCombatant() del alpha v0.7.3.'}
],
glossary:[{id:'terms',title:'Vocabulario mínimo',type:'Glosario',one:'Antes de leer una Skill, identifica cuatro palabras: Power, Coin, Hit y Trigger.',watch:'Usa el HUD del Dummy como referencia visual mientras lees las definiciones.',meaning:'Power = valor que compite o golpea. Coin = tirada de una Skill. Hit = una Coin que ya conectó. Trigger = momento que activa un efecto, como [On Hit] o Turn End.',dont:'Potency y Count pertenecen a muchos estados, pero no significan lo mismo en todos: Potency suele medir intensidad y Count suele controlar duración/activaciones.',steps:['Power: número de resolución de una Skill.','Coin: tirada individual de la Skill.','Hit: Coin que conectó.','Trigger: momento exacto donde se ejecuta una regla.'],demo:'hud',source:'Glosario construido usando los nombres y orden de resolución presentes en el alpha v0.7.3.'}]};
let section='fundamentals',lessonIndex=0,frameReady=false;
function current(){return lessons[section][lessonIndex]}
function coach(title,copy){$('coach').innerHTML=`<b>${title}</b><span>${copy}</span>`}
function renderTabs(){document.querySelectorAll('.section-tab').forEach(b=>b.classList.toggle('active',b.dataset.section===section));const host=$('lesson-list');host.innerHTML=lessons[section].map((l,i)=>`<button class="lesson-chip${i===lessonIndex?' active':''}" data-i="${i}">${l.title}</button>`).join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>{lessonIndex=+b.dataset.i;renderLesson();resetScene()})}
function renderLesson(){const l=current();$('lesson-index').textContent=String(lessonIndex+1).padStart(2,'0');$('lesson-type').textContent=l.type;$('lesson-title').textContent=l.title;$('one-line').textContent=l.one;$('watch').textContent=l.watch;$('meaning').textContent=l.meaning;$('dont-confuse').textContent=l.dont;$('steps').innerHTML=l.steps.map(x=>`<li>${x}</li>`).join('');$('source-note').textContent=l.source;$('stage-label').textContent=l.title;renderTabs();coach(`Seleccionaste ${l.title}`,l.watch)}
function frame(){return engine.contentWindow}function doc(){return engine.contentDocument}
function injectTrainingMode(){const d=doc(),w=frame();if(!d||!w)return;const host=d.getElementById('game-container');host?.classList.remove('webgl2-renderer-ready','webgl2-background-ready');const canvas=d.getElementById('webgl2-combat-canvas');if(canvas)canvas.style.display='none';const bg=d.getElementById('webgl2-dom-background');if(bg)bg.style.opacity='1';d.querySelectorAll('.sprite-img.webgl2-texture-backed').forEach(x=>x.classList.remove('webgl2-texture-backed'));d.querySelectorAll('.sprite-container').forEach(token=>{token.style.display=['token-don','token-enemy_1'].includes(token.id)?'':'none'});d.getElementById('token-enemy_1')?.classList.remove('enemy-unscanned');const style=d.createElement('style');style.id='codex-training-style';style.textContent=`#target-intent-overlay,.prototype-controls,.enemy-scan-panel,.clash-forecast,.targeting-hint,.turn-transition,#webgl2-renderer-state{display:none!important}#battlefield,#webgl2-dom-background{--camera-x:0px!important;--camera-y:0px!important;--camera-scale:1!important;transform:none!important;transition:none!important}#webgl2-combat-canvas{display:none!important}.sprite-img{opacity:1!important}.sprite-container.enemy.enemy-unscanned .hp-fill-line,.sprite-container.enemy.enemy-unscanned .stagger-threshold{opacity:1!important}`;d.head.appendChild(style);const field=d.getElementById('battlefield'),back=d.getElementById('webgl2-dom-background');const lock=()=>{[field,back].forEach(x=>{if(!x)return;x.style.setProperty('--camera-x','0px','important');x.style.setProperty('--camera-y','0px','important');x.style.setProperty('--camera-scale','1','important')})};lock();new MutationObserver(lock).observe(field,{attributes:true,attributeFilter:['style','class']});if(typeof w.closeAllFloatingClashHuds==='function')w.closeAllFloatingClashHuds();frameReady=true}
function resetScene(after){frameReady=false;engine.onload=()=>setTimeout(()=>{injectTrainingMode();after?.()},100);engine.src='engine-alpha.html?reset='+Date.now()}
function makeEntry(ownerId,targetId,{name='Training Skill',basePower=4,coinPower=2,coinAmount=1,damageType='Slash',effects=[],coins=[],sinAffinity='wrath',tremorBurst=false}={}){return{ownerId,ownerName:ownerId==='don'?'Don Quixote':'Training Dummy',controller:'ai',localIndex:0,plan:{type:'auto',targetId,data:{name,basePower,coinPower,coinAmount,coinType:'positive',damageType,sinAffinity,effects,coins,tremorBurst}}}}
async function withFixedRandom(seq,fn){const w=frame(),old=w.Math.random,values=[...seq];w.Math.random=()=>values.length?values.shift():.05;try{return await fn()}finally{w.Math.random=old}}
async function demoHud(){coach('HUD de unidad','Mira el heptágono, Speed/Action Slot arriba, HP y SP abajo y las marcas blancas sobre la línea de HP.')}
async function demoSp(){const w=frame();w.LuminousCombatHUD.setSP('don',25);coach('SP +25','El orbe de Don cambió. Ahora la tirada usa una probabilidad de Heads mayor.');await new Promise(r=>setTimeout(r,700));const e=makeEntry('don','enemy_1',{name:'SP Training',basePower:4,coinPower:3,coinAmount:1});await withFixedRandom([.1,.1,.1],()=>w.resolveUnopposedCoinAction(e))}
async function demoThreshold(){const w=frame(),hud=w.LuminousCombatHUD;hud.setHP('enemy_1',118);await new Promise(r=>setTimeout(r,400));coach('Antes del Threshold','El Dummy está apenas por encima de la primera marca.');hud.damage('enemy_1',22,{attackerId:'don',damageType:'Slash'});coach('Cruce de Threshold','Mira la marca consumirse y la UI de Stagger aparecer con la lógica real del motor.')}
async function demoCoin(){const w=frame(),e=makeEntry('don','enemy_1',{name:'Training Coin',basePower:5,coinPower:3,coinAmount:1});coach('Skill HUD real','Mira nombre, Power, Coin Power y la Coin activa junto a Don.');await withFixedRandom([.1,.1,.1],()=>w.resolveUnopposedCoinAction(e))}
async function demoClash(){const w=frame(),a=makeEntry('don','enemy_1',{name:'Galloping Training',basePower:5,coinPower:3,coinAmount:2}),b=makeEntry('enemy_1','don',{name:'Dummy Countercut',basePower:3,coinPower:1,coinAmount:2});coach('CLASH','Ahora mira a las unidades: se acercan físicamente y cada una abre su clash-float-hud.');await withFixedRandom([.05,.05,.9,.9,.05,.05,.9,.9,.05,.05],()=>w.LuminousCombatHUD.resolveSkillClash(a,b))}
async function demoOnHit(){const w=frame(),effect={trigger:'[On Hit]',target:'target',type:'status',status:'sinking',potency:3,count:1},e=makeEntry('don','enemy_1',{name:'On Hit Training',basePower:5,coinPower:2,coinAmount:1,effects:[effect]});coach('Orden de un Hit','Primero mira el daño. Sinking debe aparecer después, porque [On Hit] se procesa tras el Hit.');await withFixedRandom([.05,.05,.05],()=>w.resolveUnopposedCoinAction(e))}
async function demoBurn(){const w=frame(),hud=w.LuminousCombatHUD;hud.applyStatus('enemy_1','burn',{mode:'set',potency:12,count:3});coach('Burn aplicado','Todavía no debe perder HP. Burn espera a Turn End.');await new Promise(r=>setTimeout(r,850));coach('TURN END → BURN','Ahora se ejecuta el mismo processStatusRoundEnd() del alpha.');w.processStatusRoundEnd(1)}
async function demoBleed(){const w=frame(),hud=w.LuminousCombatHUD;hud.applyStatus('don','bleed',{mode:'set',potency:8,count:3});const e=makeEntry('don','enemy_1',{name:'Bleed Training',basePower:5,coinPower:2,coinAmount:1});coach('Bleed está en Don','Durante SU Coin verás daño en Don; después verás por separado el Hit sobre el Dummy.');await withFixedRandom([.05,.05,.05],()=>w.resolveUnopposedCoinAction(e))}
async function demoSinking(){const w=frame(),hud=w.LuminousCombatHUD;hud.setSP('enemy_1',25);hud.applyStatus('enemy_1','sinking',{mode:'set',potency:10,count:2});const e=makeEntry('don','enemy_1',{name:'Sinking Training',basePower:5,coinPower:2,coinAmount:1});coach('HP primero, SP después','Mira el Hit de la Skill y después el orbe SP del Dummy: Sinking reacciona al ser golpeado.');await withFixedRandom([.05,.05,.05],()=>w.resolveUnopposedCoinAction(e))}
async function demoTremor(){const w=frame(),hud=w.LuminousCombatHUD;hud.setHP('enemy_1',130);hud.applyStatus('enemy_1','tremor',{mode:'set',potency:25,count:2});coach('Tremor aplicado','El HP no cambia. Mira las marcas blancas.');await new Promise(r=>setTimeout(r,850));hud.tremorBurst('enemy_1','don');coach('TREMOR BURST','Las marcas se movieron usando Potency / Max HP; el HP permanece igual.')}
async function demoPoise(){const w=frame(),hud=w.LuminousCombatHUD;hud.applyStatus('don','poise',{mode:'set',potency:20,count:3});const e=makeEntry('don','enemy_1',{name:'Poise Training',basePower:8,coinPower:4,coinAmount:1});coach('Poise 20 = 100% Crit','El Hit usará el crítico real del motor; mira el popup de daño y el Count de Poise.');await withFixedRandom([.05,.05,.05],()=>w.resolveUnopposedCoinAction(e))}
const demos={hud:demoHud,sp:demoSp,threshold:demoThreshold,coin:demoCoin,clash:demoClash,onhit:demoOnHit,burn:demoBurn,bleed:demoBleed,sinking:demoSinking,tremor:demoTremor,poise:demoPoise};
async function play(){const l=current();$('play-demo').disabled=true;try{if(!frameReady){resetScene(()=>setTimeout(()=>demos[l.demo]?.(),180));return}await demos[l.demo]?.()}catch(e){console.error(e);coach('La demostración no pudo resolverse',String(e?.message||e))}finally{$('play-demo').disabled=false}}
document.querySelectorAll('.section-tab').forEach(b=>b.onclick=()=>{section=b.dataset.section;lessonIndex=0;renderLesson();resetScene()});$('reset-demo').onclick=()=>resetScene();$('play-demo').onclick=play;engine.onload=()=>setTimeout(()=>{injectTrainingMode();renderLesson()},100);renderLesson();
})();