(function (global) {
  "use strict";
  const api = global.LuminousBackgroundNarratives || (typeof require === "function" ? require("./catalog.js") : null);
  if (!api) throw new Error("LuminousBackgroundNarratives debe cargarse antes del catálogo Civil/Labor.");

  api.register([
    {
      id: "nest_heir", name: "Heredero de familia del Nest", category: "civilian",
      overview: "Naciste dentro de una familia acomodada del Nest, no como heredero del Nest mismo: los Nests pertenecen al dominio de sus Wings. Creciste rodeado de etiqueta, expectativas familiares, personal de servicio y la seguridad relativa de vivir detrás de las barreras que separan el Nest de las Backstreets.",
      trait: { name: "Born Behind the Wall", description: "Reduce en X el Threshold de Checks de etiqueta, precedencia, círculos acomodados o costumbres del Nest cuando tu educación sea relevante." },
      feature: { name: "Position of Privilege", description: "Sabes cómo presentarte ante familias acomodadas, solicitar una audiencia y reconocer la clase de formalidad que se espera de alguien de tu estrato.", limits: "No garantiza que tu apellido siga teniendo poder, que una familia te reciba ni que conserves acceso al Nest." },
      loreTerms: ["city", "nest", "wing", "feather"], loreSources: ["city"],
      ideals: [
        "Legado|Quieres que el nombre y la historia de tu familia sigan teniendo peso, aunque seas tú quien decida qué merece conservarse de ese legado",
        "Mérito|Haber nacido con ventajas te obliga a demostrar que tus logros no dependen únicamente del apellido, dinero o conexiones que recibiste",
        "Deber|Consideras que el privilegio crea responsabilidades hacia quienes dependen de tus decisiones, incluso si tu familia nunca compartió esa idea",
        "Libertad|Rechazas que tu casa decida tu profesión, tus vínculos o tu futuro; quieres demostrar que puedes existir fuera de su guion",
        "Ambición|Conociste de cerca a personas con influencia y no te conformas con heredar una posición menor: quieres construir un nombre propio",
        "Reforma|Viste las ventajas y crueldades que puede esconder una vida protegida y crees que alguien con acceso debe cambiar aquello que otros no pueden tocar",
        "Familia|Aunque critiques sus métodos, tu casa sigue siendo parte central de tu identidad y proteger a sus miembros continúa siendo una prioridad",
      ],
      bonds: [
        "Aprobación familiar|Todavía buscas la aprobación de un familiar cuya opinión definió durante años qué significaba para ti tener éxito",
        "Quien me crió|Una persona de servicio, tutor o cuidador te enseñó más sobre la vida que muchos miembros de tu propia familia",
        "Obligación pendiente|Existe una promesa, deuda o responsabilidad de tu casa que abandonaste sin resolver cuando comenzaste tu vida actual",
        "Herencia personal|Conservas una carta, joya, prenda u otro objeto asociado a tu familia que vale más por lo que representa que por su precio",
        "Rivalidad familiar|Otra rama, heredero o familia mantiene una rivalidad que puede seguir afectándote incluso lejos del Nest",
        "Alguien quedó atrás|Una persona importante continúa viviendo bajo las reglas del Nest y prometiste regresar, ayudarla o sacarla de allí",
        "Mi antiguo hogar|Una residencia, jardín, salón o lugar privado de tu infancia sigue representando para ti la idea de hogar, para bien o para mal",
      ],
      flaws: [
        "Puertas abiertas|Estás demasiado acostumbrado a que el apellido, vestimenta o educación consigan una oportunidad de hablar antes de tener que demostrar nada",
        "Condescendencia aprendida|Puedes tratar como inferiores a personas de Backstreets o trabajos humildes aun cuando conscientemente rechazas el clasismo de tu entorno",
        "Cortesía igual a lealtad|Te educaron en un mundo donde la hostilidad suele esconderse detrás de modales impecables y a veces confundes buenas formas con confianza real",
        "Dependencia del privilegio|Te cuesta admitir cuánto de tu antigua seguridad provenía de recursos, contactos y protección que nunca tuviste que construir por ti mismo",
        "Honor familiar|Una afrenta a tu casa o apellido puede provocarte incluso cuando racionalmente sabes que no deberías defenderlos",
        "Ciego a las Backstreets|Sabes mucho menos de pobreza, violencia cotidiana y supervivencia fuera del Nest de lo que tu educación te hace creer",
        "Miedo al escándalo|Ocultas errores y problemas demasiado tiempo porque aprendiste que la reputación familiar podía ser más importante que reconocer un fracaso",
      ],
    },
    {
      id: "wing_executive_family", name: "Descendiente de familia ejecutiva de Wing", category: "civilian",
      overview: "Tu familia estaba vinculada a niveles ejecutivos de una Wing. No significa que conocieras su Singularity ni todos sus secretos, pero creciste viendo cómo se habla, negocia y compite en ambientes donde una decisión corporativa puede afectar a miles de empleados y Feathers.",
      trait: { name: "Corporate Pedigree", description: "Reduce en X el Threshold de Checks sobre jerarquía corporativa, protocolo ejecutivo y lectura de ambientes de alto nivel cuando tu crianza resulte aplicable." },
      feature: { name: "Corporate Upbringing", description: "Reconoces títulos, formas de tratamiento, prioridades y señales de estatus propias de élites corporativas.", limits: "No otorga secretos de Singularity, credenciales vigentes ni autoridad sobre la Wing." },
      loreTerms: ["wing", "nest", "feather"], loreSources: ["city"],
      ideals: [
        "Competencia|Crees que una posición elevada sólo se justifica si quien la ocupa obtiene resultados y entiende las consecuencias de sus decisiones",
        "Lealtad institucional|Una organización enorme sólo funciona cuando cada parte cumple su responsabilidad, incluso si no recibe reconocimiento personal",
        "Independencia|Te niegas a convertirte en una extensión de la carrera, los aliados o las expectativas que tu familia preparó para ti",
        "Ambición|Viste de cerca cómo viven quienes toman decisiones y quieres alcanzar una posición desde la cual nadie pueda tratarte como un accesorio familiar",
        "Responsabilidad|Sabes que una firma ejecutiva puede decidir empleos, recursos y seguridad; por eso crees que el poder debe responder por sus efectos",
        "Pragmatismo|Las Wings sobreviven porque eliminan ineficiencias y responden a incentivos; tú valoras soluciones que funcionen aunque no sean elegantes",
        "Verdad|Crecer entre información compartimentada te dejó la necesidad de descubrir qué decisiones se tomaban realmente detrás del lenguaje corporativo",
      ],
      bonds: [
        "Familia dentro de una Wing|Un familiar continúa en una estructura corporativa y su carrera puede convertirse en ayuda, presión o riesgo para ti",
        "Empleado leal|Una persona que trabajaba para tu familia te protegió o te trató con una honestidad que rara vez encontrabas entre ejecutivos",
        "Daño corporativo|Una decisión tomada por tu familia o por su departamento perjudicó a alguien cuyo destino todavía pesa sobre ti",
        "Rival de mi generación|Otro descendiente, aprendiz ejecutivo o heredero corporativo fue comparado contigo durante años y esa competencia nunca terminó del todo",
        "Expectativa pendiente|Tu familia preparó una carrera, matrimonio, puesto o examen para ti que abandonaste antes de cumplirlo",
        "Correspondencia privada|Conservas mensajes, notas o documentos personales que muestran cómo era tu familia lejos de la imagen pública",
        "El departamento que fue mi mundo|Una división, instalación u oficina concreta fue el centro de tu infancia y aún conoces personas que trabajan allí",
      ],
      flaws: [
        "Todo es una negociación|Te cuesta aceptar gestos que no tengan intercambio, ventaja o motivo estratégico porque así aprendiste a interpretar las relaciones adultas",
        "Desconfianza de lo gratuito|Cuando alguien ofrece ayuda sin pedir nada, tu primer impulso es buscar la cláusula oculta o el beneficio que no te han explicado",
        "Protejo la marca familiar|Puedes ocultar información o minimizar un problema con tal de impedir que el nombre de tu familia quede asociado a un escándalo",
        "Acceso no es comprensión|Haber escuchado conversaciones importantes puede hacerte creer que entiendes tecnologías o decisiones para las que nunca recibiste formación real",
        "Protocolo como medida de valor|Puedes juzgar duramente a quien desconoce etiqueta ejecutiva aunque su experiencia práctica sea muy superior a la tuya",
        "Control de daños|Tu instinto es contener un problema antes que admitirlo, lo que a veces convierte un error pequeño en algo mucho peor",
        "Necesidad de superarles|Una parte de ti mide cada logro contra la sombra de tu familia y puede arriesgar demasiado sólo para demostrar que llegaste más lejos",
      ],
    },
    {
      id: "comfortable_feather", name: "Feather acomodado", category: "civilian",
      overview: "Viviste como Feather con una posición relativamente estable dentro de un Nest. Conoces la rutina de servicios, trabajo, vivienda y expectativas de seguridad que hacen que muchas personas de las Backstreets arriesguen todo por obtener un permiso de migración al Nest.",
      trait: { name: "Nest Etiquette", description: "Obtienes +X Power en Checks Sociales relacionados con la vida cotidiana, costumbres y expectativas de un Nest que razonablemente conozcas." },
      feature: { name: "Life Behind the Walls", description: "Sabes cómo moverte entre servicios, residencias, comercios y ambientes cotidianos de Feathers establecidos.", limits: "No concede ciudadanía actual, visas ni conocimiento de todos los Nests, cuyas reglas pueden variar por Wing." },
      loreTerms: ["nest", "feather", "wing"], loreSources: ["city"],
      ideals: [
        "Estabilidad|Valoras una vida predecible porque sabes cuánto trabajo cuesta conservar una posición segura dentro del sistema de una Wing",
        "Progreso|Crees que las instituciones y la tecnología pueden mejorar la vida cotidiana si quienes las administran no olvidan a la gente común",
        "Gratitud|No das por sentado que haber vivido seguro te hacía superior; prefieres recordar las oportunidades que otras personas nunca recibieron",
        "Independencia|Después de depender de un Nest para vivienda, empleo y seguridad, quieres demostrar que puedes decidir tu vida sin esa protección",
        "Orden|Te resulta natural valorar reglas claras y servicios confiables porque creciste viendo cómo la estabilidad distingue al Nest de muchas Backstreets",
        "Curiosidad exterior|La vida protegida te dejó fascinado por aquello que existía fuera de las barreras y que sólo conocías por rumores o noticias",
        "Moderación|Conocer comodidad y precariedad te convence de que el privilegio debe utilizarse con cuidado y no como prueba de superioridad",
      ],
      bonds: [
        "Mi antiguo hogar|Una residencia concreta del Nest sigue siendo la imagen con la que comparas cualquier lugar al que llamas hogar",
        "Feather importante|Una persona que continúa en el Nest es familia, amistad, amor o responsabilidad que todavía te conecta con esa vida",
        "Vecino o compañero|Alguien con quien compartías la rutina del Nest se convirtió en tu verdadera familia elegida",
        "Rutina perdida|Extrañas un trayecto, comercio, comedor, plaza o pequeña costumbre cotidiana que sólo apreciaste después de perderla",
        "Favor que preservó mi estatus|Alguien intervino cuando tu trabajo, residencia o permiso estaba en peligro y todavía consideras que debes devolver ese favor",
        "Quiero regresar|Hay un lugar del Nest al que deseas volver aunque ya no sepas si encontrarás allí lo que recuerdas",
        "Alguien fuera dependía de mí|Una persona de Backstreets recibía dinero, ayuda o información de ti y sólo después comprendiste cuánto significaba",
      ],
      flaws: [
        "Comodidades invisibles|Esperas agua, energía, transporte o seguridad con una regularidad que no siempre existe fuera de un Nest bien mantenido",
        "Necesidad de reglas|Cuando nadie parece tener autoridad formal, te sientes inseguro y buscas crear una estructura incluso donde no hace falta",
        "Subestimo Backstreets|Puedes interpretar como desorden o incompetencia comportamientos que en realidad son adaptaciones necesarias para sobrevivir sin protección de Wing",
        "Prejuicios de clase|Conservas hábitos o expresiones que revelan la división entre Feather y habitante de Backstreets aunque intentes ser respetuoso",
        "Obsesión con recuperar estabilidad|Puedes sacrificar oportunidades o relaciones por la promesa de volver a una vida segura semejante a la que perdiste",
        "Racionalización|Te cuesta admitir qué injusticias aceptaste mientras tu propia vida siguiera siendo cómoda y estable",
        "Dependencia institucional|A veces esperas que una organización resuelva problemas que ahora requieren iniciativa personal o negociación informal",
      ],
    },
    {
      id: "wing_administrator", name: "Empleado administrativo de Wing", category: "civilian",
      overview: "Trabajaste en la maquinaria burocrática de una Wing: solicitudes, expedientes, permisos, comunicaciones internas o procesos semejantes. No tenías por qué conocer la Singularity ni secretos estratégicos; tu especialidad era lograr que la institución pudiera procesar personas y decisiones sin detenerse.",
      trait: { name: "Paperwork Never Dies", description: "Reduce en X el Threshold de Checks para interpretar expedientes, permisos, formularios o procedimientos burocráticos corporativos similares a los que manejabas." },
      feature: { name: "Know the Department", description: "Aunque no puedas aprobar un trámite, normalmente sabes qué clase de departamento, funcionario o registro debería intervenir.", limits: "Cada Wing posee procedimientos propios; experiencia en una no concede acceso ni dominio automático sobre otra." },
      loreTerms: ["wing", "nest"], loreSources: ["city"],
      ideals: [
        "Procedimiento|Crees que un proceso claro protege a empleados y ciudadanos de decisiones arbitrarias, incluso cuando la burocracia resulte lenta",
        "Eficiencia|Una regla sólo tiene valor si permite que el trabajo avance; buscas reducir pasos inútiles y enviar cada problema a quien puede resolverlo",
        "Responsabilidad|Quien firma, archiva o aprueba algo debe recordar que detrás del expediente existe una persona que sufrirá las consecuencias",
        "Transparencia|Después de trabajar entre formularios y lenguaje interno, valoras explicar qué está ocurriendo y quién tomó realmente una decisión",
        "Estabilidad institucional|Prefieres sistemas previsibles a decisiones improvisadas porque has visto cuánto daño causa una organización que deja de funcionar",
        "Servicio|Para ti, administrar significa hacer posible el trabajo de otros, no demostrar autoridad sobre quien necesita un trámite",
        "Conocer las reglas para no depender de ellas|Aprendiste procedimientos para poder navegar instituciones sin quedar completamente a merced de quien controla una ventanilla",
      ],
      bonds: [
        "Antiguo compañero|Un colega sigue dentro de la Wing y conoce una versión de ti asociada a años de trabajo cotidiano",
        "Expediente inconcluso|Dejaste un caso, solicitud o investigación administrativa abierta y nunca supiste qué ocurrió con la persona afectada",
        "Un trámite cambió una vida|Una aprobación, rechazo o error en el que participaste tuvo consecuencias personales que todavía recuerdas",
        "Documento conservado|Guardas una copia, formulario o nota que técnicamente debiste destruir o entregar al abandonar tu puesto",
        "Supervisor|Una figura de autoridad marcó tu forma de trabajar, ya fuera como mentor, abusador o ejemplo de lo que nunca quieres convertirte",
        "Mi departamento|Una unidad administrativa fue durante años tu comunidad cotidiana y sus antiguos miembros siguen siendo referencias para ti",
        "Irregularidad sin explicación|Encontraste números, firmas o movimientos que no encajaban y abandonaste la Wing sin descubrir qué significaban",
      ],
      flaws: [
        "Busco un procedimiento para todo|Cuando aparece un problema nuevo puedes perder tiempo intentando encontrar reglas que simplemente no existen",
        "Necesidad de autorización|Te cuesta asumir responsabilidad sin que alguien de rango superior confirme que tienes permiso para actuar",
        "Pedantería burocrática|Corriges términos, formularios o formatos incluso cuando la precisión administrativa no es lo importante del momento",
        "Personas convertidas en casos|Años de expedientes pueden hacerte hablar de vidas humanas como números, solicitudes o incidencias",
        "Confianza excesiva en documentos|Un sello o registro oficial te resulta más convincente de lo que debería en una Ciudad donde la información también puede manipularse",
        "No puedo ignorar inconsistencias|Una fecha, número o firma fuera de lugar puede distraerte de un problema mucho más urgente",
        "No hacer preguntas|Aprendiste que ciertas cosas no correspondían a tu departamento y ese reflejo de silencio puede aparecer cuando deberías investigar",
      ],
    },
    {
      id: "civil_researcher", name: "Académico / investigador civil", category: "civilian",
      overview: "Tu carrera estuvo dedicada a estudiar, comparar fuentes y producir conocimiento fuera de una función militar o de Fixer. En la Ciudad, ese trabajo puede ocurrir en academias, laboratorios civiles, archivos o instituciones privadas; tu Background define el campo concreto que realmente estudiaste.",
      trait: { name: "Research Method", description: "Obtienes +X Power al investigar documentación, contrastar fuentes o trabajar dentro de tu especialidad académica declarada." },
      feature: { name: "Know Where to Look", description: "Cuando no conoces una respuesta, puedes identificar qué tipo de archivo, especialista o institución sería una fuente razonable para buscarla.", limits: "Saber dónde investigar no significa poseer la información, acceso al archivo ni autoridad científica universal." },
      loreTerms: ["city"], loreSources: ["city"],
      ideals: [
        "Verdad|Prefieres una conclusión incómoda respaldada por evidencia a una explicación cómoda que nadie se atreve a comprobar",
        "Rigor|Un resultado sólo merece confianza si puedes explicar cómo llegaste a él y qué límites tiene la información disponible",
        "Curiosidad|Consideras valioso investigar incluso cuando la respuesta no promete dinero, rango ni una aplicación inmediata",
        "Aplicación práctica|El conocimiento debería resolver problemas reales y mejorar decisiones, no existir únicamente para impresionar a otros académicos",
        "Preservación|En una Ciudad donde organizaciones y lugares desaparecen, conservar registros y conocimiento puede ser una forma de salvar algo de ellos",
        "Escepticismo|Las afirmaciones extraordinarias necesitan evidencia, especialmente cuando una organización poderosa tiene interés en que sean aceptadas",
        "Legado intelectual|Quieres dejar detrás métodos, notas o descubrimientos que otra persona pueda utilizar mucho después de que tú ya no estés",
      ],
      bonds: [
        "Mentor|Una persona te enseñó a investigar y su aprobación, desaparición o desacuerdo todavía influye en tu trabajo",
        "Investigación inconclusa|Abandonaste un proyecto antes de responder la pregunta que originalmente consumía tu tiempo",
        "Colega|Un compañero compartió años de trabajo contigo y conoce tanto tus mejores hallazgos como tus peores errores",
        "Archivo o laboratorio|Un lugar concreto contenía recursos esenciales para tu carrera y todavía deseas regresar o recuperar algo de allí",
        "Promesa de una respuesta|Le aseguraste a alguien que descubrirías la verdad sobre un problema y aún no has podido cumplirlo",
        "Notas incompletas|Conservas documentos que sólo tú sabes interpretar completamente y que podrían adquirir importancia inesperada",
        "Consecuencias de mis conclusiones|Una persona, comunidad o institución fue afectada por algo que publicaste, revelaste o recomendaste",
      ],
      flaws: [
        "No sé detener la investigación|Sigues buscando una explicación completa incluso cuando la información adicional ya no justifica el riesgo",
        "Desprecio por lo anecdótico|Puedes ignorar testimonios útiles porque no cumplen el estándar formal de evidencia al que estás acostumbrado",
        "Necesidad de tener razón|Una crítica a tu conclusión puede sentirse como una crítica a tu inteligencia y hacerte defender demasiado una hipótesis",
        "Curiosidad peligrosa|La pregunta correcta puede importarte más que las consecuencias de abrir, tocar o examinar algo que debería permanecer aislado",
        "Explico demasiado|Cuando dominas un tema puedes convertir una respuesta sencilla en una conferencia que nadie pidió",
        "Desconfianza de respuestas simples|A veces asumes que una explicación directa debe esconder algo porque has pasado demasiado tiempo buscando problemas complejos",
        "Conocer no es controlar|Comprender un fenómeno puede hacerte creer que también sabes manipularlo con seguridad, aunque jamás hayas tenido esa experiencia práctica",
      ],
    },
    {
      id: "nest_student", name: "Estudiante de academia del Nest", category: "civilian",
      overview: "Recibiste educación formal en una academia del Nest. Tu formación pudo prepararte para una profesión, una Wing, un examen o una disciplina concreta; no significa que todas las academias enseñen lo mismo ni que hayas completado tus estudios.",
      trait: { name: "Formal Education", description: "Obtienes +X Power en Checks académicos directamente relacionados con el campo que estudiaste." },
      feature: { name: "Academic Circles", description: "Entiendes cómo se organizan clases, evaluaciones, tutores y redes estudiantiles, y puedes reconocer instituciones semejantes.", limits: "No garantiza un título vigente ni acceso a academias ajenas." },
      loreTerms: ["nest", "wing"], loreSources: ["city"],
      ideals: [
        "Excelencia|Quieres demostrar que el tiempo y recursos dedicados a tu educación se convierten en competencia real, no sólo en credenciales",
        "Curiosidad|La academia te mostró cuántas cosas ignorabas y ahora aprender es una motivación que existe incluso fuera de cualquier examen",
        "Competencia|Compararte con otros estudiantes te enseñó a medir tu progreso y todavía buscas situaciones donde puedas demostrar lo que sabes",
        "Compañerismo|Las personas con las que estudiaste fueron más importantes que las notas y crees que aprender funciona mejor cuando se comparte",
        "Libertad|La educación debía abrirte posibilidades, no encerrarte en la carrera que profesores o familia eligieron para ti",
        "Disciplina|Confías en el hábito, la práctica y el estudio constante más que en talento sin entrenamiento",
        "Propósito|Quieres utilizar lo que aprendiste para algo que justifique los sacrificios necesarios para acceder a esa educación",
      ],
      bonds: [
        "Compañero de estudios|Una amistad o rivalidad nacida entre clases y exámenes continúa siendo importante para ti",
        "Profesor|Un instructor creyó en ti, te humilló o te empujó hacia un campo que todavía define tu vida",
        "Estudios abandonados|Hay un curso, título o especialización que nunca terminaste y que todavía consideras parte de una vida posible",
        "Rival académico|Otra persona siempre parecía estar un paso delante de ti y la comparación continúa motivándote o persiguiéndote",
        "Mi academia|La institución donde estudiaste conserva archivos, personas y recuerdos que pueden volver a ser relevantes",
        "El examen que cambió todo|Una prueba aprobada o fallada decidió una oportunidad concreta y todavía interpretas tu vida a partir de ese resultado",
        "Proyecto sin terminar|Un trabajo de clase o investigación comenzó como obligación y terminó convirtiéndose en algo demasiado importante para abandonar",
      ],
      flaws: [
        "Todo es competencia|Puedes transformar cooperación y ocio en otra oportunidad para demostrar que eres mejor o más preparado",
        "Miedo al fracaso|Una mala evaluación te enseñó a asociar error con pérdida de futuro y a veces evitas intentar algo que no dominas",
        "Educación igual a inteligencia|Puedes subestimar a quien aprendió por experiencia en lugar de hacerlo dentro de una institución formal",
        "Teoría antes que realidad|Una explicación académica te resulta tan familiar que puedes insistir en ella aunque la situación práctica muestre otra cosa",
        "Estudio como evasión|Investigar y prepararte puede convertirse en una forma elegante de posponer decisiones que te asustan",
        "Necesidad de aprobación|Todavía buscas mentalmente la nota, elogio o corrección de una figura de autoridad antes de confiar en tu propio criterio",
        "El libro debería tener razón|Cuando un hecho contradice lo que aprendiste puedes tardar demasiado en aceptar que tu formación estaba incompleta o desactualizada",
      ],
    },
    {
      id: "docugrapher", name: "Docugrapher / trabajador de información", category: "civilian",
      overview: "Trabajaste reuniendo, organizando, verificando o comercializando información como profesión. En la Ciudad, la información puede valer tanto como equipo o protección; tu experiencia consiste en seguir registros y fuentes, no en saber automáticamente todos los secretos que existen.",
      trait: { name: "Follow the Paper Trail", description: "Obtienes +X Power al localizar, organizar, comparar o verificar registros e información documental." },
      feature: { name: "Information Profession", description: "Reconoces archivos, proveedores, intermediarios y prácticas utilizadas para almacenar o vender información de forma profesional.", limits: "No concede acceso gratuito a datos privados ni convierte una fuente potencial en fuente cooperativa." },
      loreTerms: ["city"], loreSources: ["city"],
      ideals: [
        "Registro|Lo que no se conserva puede desaparecer de la memoria colectiva, por eso consideras importante dejar constancia de hechos verificables",
        "Precisión|Una fecha o nombre incorrectos pueden cambiar por completo el valor de un expediente y por eso prefieres corregir antes que improvisar",
        "Acceso|La información sólo puede ayudar si alguien puede encontrarla, por lo que valoras sistemas que permitan recuperar conocimiento cuando haga falta",
        "Discreción|Trabajar con datos ajenos te enseñó que saber algo no te concede derecho a divulgarlo sin pensar en las consecuencias",
        "Verdad|Crees que una cadena de registros bien comprobada puede atravesar propaganda, rumores y versiones interesadas de un mismo hecho",
        "Valor de la información|No todo dato tiene el mismo precio ni la misma utilidad; aprender quién necesita qué fue parte central de tu oficio",
        "Memoria|En una Ciudad que destruye personas y organizaciones, conservar pruebas puede ser una forma de impedir que algo sea borrado por completo",
      ],
      bonds: [
        "Registro importante|Existe un expediente o colección de datos cuyo destino sigue preocupándote porque sabes lo que podría demostrar",
        "Fuente confiable|Una persona te proporcionó información durante años y aprendiste a reconocer cuándo estaba asumiendo un riesgo por ayudarte",
        "Cliente|Alguien contrató repetidamente tu trabajo y terminó convirtiéndose en algo más que una relación comercial",
        "Archivo perdido|Una biblioteca, depósito o base de datos desapareció antes de que pudieras copiar todo lo que necesitabas",
        "Información que hizo daño|Un dato que entregaste produjo consecuencias que no habías previsto para una persona o comunidad",
        "Copia que conservé|Guardaste una duplicación que debías eliminar y todavía no sabes si fue prudencia o traición profesional",
        "Colega|Otra persona conocía tus métodos y rutas de información y puede reconocer inmediatamente la clase de trabajo que realizabas",
      ],
      flaws: [
        "No tolero inconsistencias|Una contradicción menor puede consumir tu atención incluso cuando hay problemas más urgentes alrededor",
        "No sé olvidar|Conservas datos que otras personas esperan que hayas destruido o dejado atrás porque borrar información te resulta físicamente difícil",
        "Privacidad secundaria|Puedes justificar revisar información personal porque te parece potencialmente relevante para una investigación",
        "Desconfío del testimonio|Si algo no deja registro verificable puedes darle menos peso del que merece aunque la fuente sea honesta",
        "Información como ventaja|A veces callas un dato útil simplemente porque conservarlo te hace sentir menos vulnerable dentro de una negociación",
        "Archivo compulsivo|Copias, ordenas y guardas cosas que probablemente nunca volverán a ser útiles porque temes necesitarlas después",
        "Conocer igual a controlar|Acumular información puede darte una falsa sensación de seguridad frente a situaciones que los datos no pueden resolver",
      ],
    },
    {
      id: "nest_merchant", name: "Comerciante de Nest", category: "civilian",
      overview: "Mantuviste un negocio o carrera comercial dentro de un Nest, donde reputación, permisos, proveedores y clientes pueden ser tan importantes como la mercancía. Tu experiencia se centra en comercio formal y clientes acostumbrados a la infraestructura de una Wing.",
      trait: { name: "Nest Commerce", description: "Obtienes +X Power en valoración, negociación y comercio formal cuando conoces el mercado o producto implicado." },
      feature: { name: "Commercial Network", description: "Sabes cómo localizar proveedores, comerciantes, distribuidores y servicios legítimos en entornos semejantes a los de tu carrera.", limits: "No concede inventario, crédito ilimitado ni contactos en todos los Nests." },
      loreTerms: ["nest", "wing", "feather"], loreSources: ["city"],
      ideals: [
        "Prosperidad|Un buen negocio debería crecer lo suficiente para sostener a quienes dependen de él y sobrevivir a los cambios del mercado",
        "Reputación|En mercados formales una mala fama puede cerrar más puertas que una pérdida puntual, por lo que proteges la confianza ganada",
        "Ambición|Ves cada nuevo cliente o proveedor como una posibilidad de convertir un negocio pequeño en algo mucho más influyente",
        "Equidad|Un intercambio duradero necesita que ambas partes crean haber recibido algo valioso, no sólo que una de ellas haya sido engañada",
        "Pragmatismo|La mercancía, los márgenes y las condiciones cambian; te interesa lo que permite que el negocio continúe funcionando mañana",
        "Familia|Tu comercio existía para sostener a una familia, socios o empleados y esa responsabilidad sigue dando forma a tus decisiones",
        "Independencia|Prefieres depender de tu capacidad para negociar y producir valor antes que de un salario que una Wing puede retirarte",
      ],
      bonds: [
        "Proveedor|Una persona o empresa fue esencial para mantener tu negocio y desarrollaste con ella una confianza difícil de reemplazar",
        "Cliente habitual|Alguien regresó tantas veces que dejó de ser sólo una venta y conoce una parte importante de tu vida anterior",
        "Deuda comercial|Debes dinero, mercancía o un favor a alguien que hizo posible que tu negocio sobreviviera una crisis",
        "Negocio perdido|Una tienda, puesto o empresa que construiste ya no te pertenece y aún piensas en recuperarla o saber qué ocurrió con ella",
        "Mercancía memorable|Un producto raro, peligroso o sentimental pasó por tus manos y su historia todavía puede seguirte",
        "Competidor|Otra persona disputó tu mercado durante años y la rivalidad produjo respeto, resentimiento o ambas cosas",
        "Empleados dependientes|Hubo personas cuya estabilidad dependía de tus decisiones comerciales y no sabes qué ocurrió con todas ellas",
      ],
      flaws: [
        "Todo tiene precio|Intentas convertir favores, afecto y compromisos en intercambios medibles porque así aprendiste a reducir incertidumbre",
        "No rechazo oportunidades|Una posibilidad de beneficio excepcional puede hacerte ignorar señales de que el negocio es demasiado peligroso",
        "Juzgo por solvencia|Puedes confundir capacidad de pago con responsabilidad, educación o valor personal",
        "Negocio antes que sinceridad|Cuando una conversación se vuelve incómoda tu instinto es negociar condiciones en vez de decir claramente lo que sientes",
        "Riesgo de inversión|Puedes perseguir una pérdida porque admitir que una inversión fracasó te resulta peor que arriesgar todavía más",
        "Reputación obsesiva|Una acusación pública puede provocarte más que una pérdida real porque temes el efecto en todas tus relaciones comerciales",
        "Utilidad igual a afecto|A veces dudas de que alguien quiera tenerte cerca si no estás ofreciendo dinero, contactos o una solución útil",
      ],
    },
    {
      id: "backstreets_merchant", name: "Comerciante de Backstreets", category: "civilian",
      overview: "Vendiste o intercambiaste bienes en las Backstreets, donde los mercados pueden ser informales, cambiar de control y depender de relaciones con vecinos, Syndicates o proveedores locales. Aprendiste a valorar no sólo el producto, sino el riesgo de moverlo y a quién conviene preguntarle.",
      trait: { name: "Street Market Sense", description: "Reduce en X el Threshold de Checks para valorar, comprar, vender o negociar en mercados informales de Backstreets que se parezcan a los que conocías." },
      feature: { name: "Market Regular", description: "Sabes cómo localizar vendedores, intermediarios y puntos de intercambio sin comportarte como un completo forastero.", limits: "No convierte un mercado criminal en seguro ni garantiza que un vendedor confíe en ti." },
      loreTerms: ["backstreets", "syndicate"], loreSources: ["backstreets"],
      ideals: [
        "Supervivencia|Un negocio vale primero por mantener comida, techo y suministros disponibles cuando el barrio atraviesa otra crisis",
        "Reputación|En mercados sin contratos sólidos, que la gente crea que cumples tu palabra puede ser más valioso que cualquier anuncio",
        "Ingenio|Si un proveedor desaparece o una calle cambia de control, encuentras otra forma de conseguir lo necesario en vez de esperar condiciones perfectas",
        "Comunidad|Tu clientela eran vecinos antes que números y crees que un comerciante también forma parte de la red que mantiene vivo al barrio",
        "Ganancia|El riesgo de Backstreets debe pagarse; no te avergüenza buscar beneficio mientras entiendas exactamente qué estás arriesgando",
        "Independencia|No quieres que una Wing, Office o Syndicate decida si puedes trabajar mañana, aunque sepas que la independencia absoluta es difícil",
        "Reciprocidad|Favores, información y crédito informal mantienen mercados funcionando cuando el dinero por sí solo no basta",
      ],
      bonds: [
        "Mi mercado|Un callejón, plaza o conjunto de puestos fue durante años tu lugar de trabajo y comunidad cotidiana",
        "Proveedor informal|Alguien conseguía mercancía difícil de encontrar y la relación sobrevivió a más de una crisis o cambio de territorio",
        "Cliente habitual|Una persona dependía de lo que vendías y terminó confiándote problemas que no tenían nada que ver con comprar",
        "Mercancía perdida|Un cargamento desapareció por robo, conflicto o desastre y todavía existe una deuda asociada a él",
        "Barrio abastecido|En algún momento tu negocio fue una de las pocas fuentes confiables de un recurso que la comunidad necesitaba",
        "Competidor|Otro comerciante conocía tus precios, contactos y debilidades; quizá también fue la persona que mejor entendía tu trabajo",
        "Mi primer puesto|El lugar pequeño donde comenzaste representa para ti haber conseguido algo propio en un entorno que no regalaba estabilidad",
      ],
      flaws: [
        "Mercancía dudosa|Puedes aceptar demasiado rápido un producto de procedencia sospechosa si crees que nadie más hará preguntas",
        "Desconfío de quien no regatea|Una persona que acepta el primer precio te parece ingenua, desesperada o peligrosa y te cuesta simplemente agradecer la venta",
        "No abandono mercancía|Arriesgas seguridad intentando recuperar bienes porque cada objeto perdido puede representar semanas de supervivencia",
        "Explotar desesperación|Sabes exactamente cuándo alguien necesita comprar y a veces utilizas esa urgencia de una forma que luego prefieres justificar",
        "Todo se negocia|Te cuesta aceptar límites, principios o decisiones que otra persona declara fuera de cualquier intercambio",
        "Contabilidad mental|Recuerdas favores y pequeñas deudas durante demasiado tiempo, incluso cuando la otra persona ya los considera olvidados",
        "Nunca olvido una estafa|Que alguien te engañe comercialmente se vuelve personal y puede hacerte perseguir una compensación mucho después de que deje de ser racional",
      ],
    },
    {
      id: "city_charlatan", name: "Estafador de la Ciudad", category: "civilian",
      overview: "Viviste de vender historias, identidades o promesas falsas. Tu oficio no requiere pertenecer a un Syndicate: aprendiste a estudiar expectativas sociales y construir una mentira que la víctima estuviera preparada para creer.",
      trait: { name: "Sell the Lie", description: "Obtienes +X Power en Deception cuando construyes una estafa, identidad falsa o mentira social preparada para el contexto." },
      feature: { name: "Confidence Game", description: "Reconoces estructuras de fraude, blancos potenciales y señales de que otra persona está intentando ejecutar una estafa semejante.", limits: "No vuelve verdadera una identidad falsa ni obliga a una víctima a ignorar evidencia." },
      loreTerms: ["city"], loreSources: ["city"],
      ideals: [
        "Libertad|Prefieres vivir de tu ingenio a aceptar una posición donde una organización pueda decidir tu valor o descartarte",
        "Ingenio|Para ti, entender qué quiere creer una persona y construir una historia convincente es una habilidad tan real como cualquier oficio técnico",
        "Supervivencia|Engañar fue una herramienta para comer y seguir moviéndote; juzgas las mentiras por sus consecuencias más que por una regla absoluta",
        "No violencia|Si puedes salir de una situación haciendo que alguien te crea, consideras ese resultado mejor que resolverla mediante fuerza",
        "Redistribución|Te resulta más fácil justificar una estafa cuando el blanco tiene recursos que nunca notará perder y tú sabes quién sí los necesita",
        "Redención|Conoces demasiado bien el daño que una mentira puede causar y quieres utilizar tu capacidad para impedir que otros cometan las mismas estafas",
        "Ambición|No quieres seguir sobreviviendo con trucos pequeños; sueñas con la estafa o identidad que te permita cambiar completamente de posición",
      ],
      bonds: [
        "Una víctima|Alguien a quien engañaste sufrió consecuencias que no esperabas y su recuerdo continúa definiendo qué límites estás dispuesto a cruzar",
        "Compañero de estafas|Una persona conocía tus señales, papeles y salidas y podía mantener una mentira contigo sin necesidad de explicaciones",
        "La persona a la que nunca engañé|Existe alguien frente a quien siempre dijiste la verdad y ese vínculo se convirtió en la única parte de tu vida que no era actuación",
        "Identidad falsa|Uno de tus nombres inventados duró tanto tiempo que todavía existen personas que creen que esa persona eres tú",
        "Daño colateral|Una estafa dirigida a un blanco concreto terminó perjudicando a alguien que nunca debía formar parte del plan",
        "Mi maestro|Alguien te enseñó a leer personas y construir mentiras; todavía no sabes si te protegió o simplemente te convirtió en una herramienta",
        "Estafa abierta|Hay dinero, un cliente, una identidad o una promesa falsa que quedó sin cerrar y que podría regresar en cualquier momento",
      ],
      flaws: [
        "Mentira automática|Inventas explicaciones incluso cuando decir la verdad sería más sencillo porque ocultar información se convirtió en reflejo",
        "Disfruto manipular|A veces ejecutas una mentira sólo para comprobar que puedes hacerlo, aun cuando no obtienes ningún beneficio real",
        "Subestimo ingenuos|Puedes confundir falta de experiencia con falta de inteligencia y no notar cuándo una supuesta víctima está aprendiendo de ti",
        "No confío en nadie|Como sabes lo fácil que es fabricar una historia, te cuesta creer incluso a personas que están intentando ser honestas",
        "Vivo en papeles|Cambiar de voz, nombre o actitud para conseguir algo puede hacerte perder claridad sobre qué comportamientos son realmente tuyos",
        "Siempre puedo improvisar|Confías tanto en hablar para salir de problemas que entras en situaciones que una persona prudente evitaría desde el principio",
        "Una mentira tapa otra|Cuando descubren una inconsistencia, tu impulso es añadir detalles nuevos en lugar de admitir el engaño y limitar el daño",
      ],
    },
    {
      id: "gambler", name: "Jugador profesional", category: "civilian",
      overview: "Pasaste suficiente tiempo alrededor de apuestas para distinguir emoción, cálculo, trampa y desesperación. La Ciudad posee ambientes de juego muy diferentes; tu Background representa experiencia profesional con apuestas, no conocimiento automático de las reglas de todos los casinos.",
      trait: { name: "Read the Table", description: "Reduce en X el Threshold para leer jugadores, detectar patrones de apuestas o identificar señales de trampa en juegos que entiendes." },
      feature: { name: "Gambling Circles", description: "Sabes cómo reconocer lugares, intermediarios y clientes vinculados al juego y qué preguntas hacer antes de sentarte a una mesa.", limits: "No garantiza ganancias ni inmunidad frente a Singularities, Taboos o reglas especiales de un establecimiento." },
      loreTerms: ["city"], loreSources: ["city"],
      ideals: [
        "Riesgo|Crees que una vida sin aceptar incertidumbre nunca produce oportunidades extraordinarias y estás dispuesto a apostar cuando entiendes las probabilidades",
        "Control|El azar existe, pero disciplina, lectura de personas y gestión de recursos determinan quién permanece en la mesa a largo plazo",
        "Disciplina|Un profesional sabe retirarse, conservar capital y no dejar que una emoción decida la siguiente apuesta",
        "Ambición|La siguiente gran oportunidad podría cambiar tu posición en la Ciudad y no quieres vivir toda la vida jugando únicamente apuestas pequeñas",
        "Libertad|Prefieres que una decisión arriesgada sea tuya antes que vivir bajo un salario y reglas decididas por otra organización",
        "Juego limpio|Aceptas perder cuando todos respetan las reglas, pero una trampa destruye el único pacto que hace posible competir",
        "Desapego|Dinero, victorias y derrotas deben circular; apegarte demasiado a una sola mesa hace que dejes de verla con claridad",
      ],
      bonds: [
        "Una mesa o casino|Existe un lugar donde todos conocían tu nombre y donde una sola noche podría haber cambiado completamente tu vida",
        "Rival|Otra persona conoce tus tells, tus hábitos y la clase de riesgos que aceptas porque pasó demasiadas horas jugando frente a ti",
        "Deuda|Una apuesta, préstamo o favor sigue pendiente y quien lo reclama probablemente recuerda la cantidad mejor que tú",
        "Gran victoria|Una vez ganaste más de lo que esperabas y todavía conservas algo comprado, perdido o prometido aquella noche",
        "Derrota que dañó a otro|Arriesgaste recursos que no sólo te pertenecían y alguien más pagó el precio de tu decisión",
        "Amuleto|Conservas una ficha, carta, moneda u objeto que asocias irracionalmente con una etapa decisiva de tu carrera",
        "Promesa de no volver|Existe un juego, establecimiento o clase de apuesta que juraste no repetir porque sabes exactamente qué versión de ti aparece allí",
      ],
      flaws: [
        "Persigo pérdidas|Cuando pierdes quieres recuperar inmediatamente lo anterior y terminas arriesgando más de lo que habrías aceptado al principio",
        "Todo parece una apuesta|Enmarcas decisiones importantes como probabilidades y puedes olvidar que otras personas no quieren arriesgar su vida contigo",
        "Ilusión de control|Leer bien una mesa muchas veces te hace creer que puedes controlar situaciones donde el azar o información oculta dominan realmente",
        "Provoco para leer|Puedes irritar o presionar a alguien sólo para observar su reacción, aunque la relación sea más importante que obtener información",
        "Recursos ajenos|Tu confianza puede hacerte utilizar dinero, equipo o seguridad del grupo como parte de un riesgo que nadie más aceptó",
        "Racha de arrogancia|Varias victorias seguidas te convencen de que estás viendo algo que los demás no pueden ver y reduces tus propias precauciones",
        "No sé retirarme|Abandonar una mesa, discusión o plan cuando todavía existe una posibilidad de ganar se siente como admitir derrota antes de tiempo",
      ],
    },
    {
      id: "urban_performer", name: "Artista / performer urbano", category: "civilian",
      overview: "Viviste de actuar ante otras personas: música, interpretación, danza, narración u otra forma escénica apropiada a tu historia. Aprendiste a leer una audiencia, sostener su atención y trabajar dentro de redes donde el siguiente empleo depende tanto de reputación como de talento.",
      trait: { name: "Work the Crowd", description: "Obtienes +X Power en Performance cuando una audiencia y tu disciplina artística concreta sean relevantes." },
      feature: { name: "Performer Network", description: "Sabes buscar escenarios, empleos, otros artistas y rumores dentro de ambientes de entretenimiento compatibles con tu experiencia.", limits: "No vuelve amistosa a una audiencia hostil ni concede fama automática fuera de los lugares donde trabajaste." },
      loreTerms: ["city", "backstreets"], loreSources: ["city", "backstreets"],
      ideals: [
        "Expresión|El arte existe para decir aquello que una conversación ordinaria no consigue comunicar con la misma fuerza",
        "Libertad|Un escenario te permitió convertir tu cuerpo, voz o técnica en algo que ninguna organización podía definir por completo",
        "Conexión|Una actuación vale porque durante unos minutos personas que no se conocen comparten atención, emoción y memoria",
        "Oficio|El talento sin ensayo no basta; respetas horarios, práctica, equipo y trabajo invisible que permite que una función exista",
        "Belleza|Incluso en una Ciudad cruel crees que crear algo memorable tiene valor aunque no resuelva ningún problema práctico",
        "Fama|Quieres que tu nombre viaje más lejos que tú y que una audiencia te reconozca antes de que tengas que presentarte",
        "Verdad emocional|Una actuación puede ser ficción y aun así expresar una emoción más honesta que muchas conversaciones reales",
      ],
      bonds: [
        "Troupe|Un grupo de artistas compartió escenario, ingresos, problemas y viajes contigo hasta convertirse en una familia profesional",
        "Escenario|Un local, calle o sala concreta fue el lugar donde aprendiste quién eras frente a una audiencia",
        "Espectador|Una persona que asistía a tus funciones terminó influyendo en tu vida mucho más de lo que cualquier artista espera de un desconocido",
        "Instrumento o vestuario|Conservas una pieza de equipo escénico asociada a una etapa que ya terminó",
        "Actuación desastrosa|Una función salió tan mal que afectó tu reputación, seguridad o relación con alguien importante",
        "Rival|Otro artista compitió contigo por trabajos y atención, y quizá fue también quien más te obligó a mejorar",
        "Obra dedicada|Existe una canción, rutina, personaje u obra que creaste pensando en alguien que todavía podría reconocerla",
      ],
      flaws: [
        "Necesito atención|Estar ignorado te resulta incómodo y puedes convertir una situación que no trata sobre ti en otra oportunidad de destacar",
        "Uso emociones como material|Una parte de ti observa incluso el dolor propio o ajeno pensando cómo podría convertirse en una historia o interpretación",
        "No sé dejar el papel|Adoptar una actitud escénica para sobrevivir socialmente puede hacerte continuar actuando cuando una relación necesita sinceridad",
        "Riesgo por una buena función|Una actuación memorable puede parecerte razón suficiente para aceptar condiciones o públicos que una persona prudente rechazaría",
        "Crítica personal|Aunque entiendas profesionalmente la crítica, una evaluación negativa puede sentirse como rechazo a tu identidad completa",
        "La historia antes que la precisión|A veces prefieres una versión que funciona ante la audiencia aunque simplifique demasiado lo que realmente ocurrió",
        "Miedo a ser olvidado|La posibilidad de desaparecer sin dejar ninguna obra o recuerdo puede empujarte a buscar atención de formas poco saludables",
      ],
    },
    {
      id: "chef", name: "Chef / restaurateur", category: "civilian",
      overview: "Trabajaste preparando comida profesionalmente o administrando un establecimiento dedicado a ella. En una Ciudad con culturas distritales muy distintas, tu especialidad culinaria importa: conoces ingredientes, proveedores, ritmos de cocina y la manera en que un local se convierte en punto de reunión.",
      trait: { name: "Professional Kitchen", description: "Obtienes +X Power en Checks de cocina, ingredientes, conservación y evaluación culinaria dentro de tu experiencia." },
      feature: { name: "Kitchen Professional", description: "Puedes reconocer cocinas profesionales, proveedores y otros trabajadores del oficio y hablar con ellos como colega cuando el contexto lo permita.", limits: "No implica conocer todas las cocinas de la Ciudad ni vuelve seguros ingredientes anómalos o desconocidos." },
      loreTerms: ["city", "backstreets"], loreSources: ["backstreets"],
      ideals: [
        "Hospitalidad|Servir comida es una forma concreta de decir que alguien puede bajar la guardia durante unos minutos bajo tu techo",
        "Excelencia|Una cocina profesional demuestra respeto mediante consistencia: cada plato debe sostener el estándar incluso cuando el turno sea horrible",
        "Tradición|Recetas y técnicas transmiten la historia de personas y lugares, y cambiarlas sin comprenderlas puede borrar algo importante",
        "Innovación|Una receta existe para evolucionar cuando nuevos ingredientes, herramientas o clientes exigen otra solución",
        "Comunidad|Un establecimiento no sólo vende comida; puede convertirse en un lugar donde trabajadores y vecinos saben que encontrarán caras conocidas",
        "Profesionalismo|La presión de una cocina no justifica negligencia: preparación, limpieza y coordinación mantienen a todos trabajando",
        "Independencia|Quieres que tu nombre esté asociado a algo que creaste y no únicamente a la Wing, Office o propietario que te contrató",
      ],
      bonds: [
        "Compañero de cocina|Compartiste suficientes turnos difíciles con alguien para conocer su ritmo, lenguaje y carácter sin necesidad de hablar demasiado",
        "Receta|Una preparación heredada, creada o prometida representa a una persona o etapa que no quieres perder",
        "Restaurante perdido|Un local que construiste o ayudaste a sostener cerró, cambió de dueño o quedó fuera de tu alcance",
        "Proveedor|Una persona conseguía ingredientes confiables y conocía aspectos de tu negocio que ningún cliente veía",
        "Plato prometido|Le dijiste a alguien que algún día prepararías algo para esa persona y todavía recuerdas exactamente qué era",
        "Comida que cambió algo|Una cena, servicio o celebración produjo una reconciliación, discusión o encuentro que sigue siendo importante",
        "Herramienta querida|Conservas un cuchillo, utensilio o pieza de equipo que representa años de trabajo profesional",
      ],
      flaws: [
        "No tolero críticas|Cuando alguien critica tu comida puedes escuchar un ataque a tu oficio incluso si la observación es razonable",
        "Odio desperdiciar|Tirar comida o materiales utilizables te cuesta tanto que puedes conservar cosas más tiempo del prudente",
        "Dirijo todo como cocina|Bajo presión das órdenes cortas y esperas respuestas inmediatas aunque la situación no tenga una jerarquía de brigada",
        "Juzgo por hábitos alimentarios|La forma en que alguien come, cocina o trata a personal de servicio influye demasiado rápido en tu opinión sobre esa persona",
        "Trabajo hasta romperme|Estás acostumbrado a continuar durante turnos agotadores y puedes ignorar necesidades físicas hasta que dejan de ser opcionales",
        "Mi método es el correcto|La experiencia puede volverte rígido frente a técnicas distintas que funcionan perfectamente en otra cocina o cultura",
        "Todo problema es preparación|Cuando algo sale mal tu primer impulso es buscar quién no preparó suficiente, aun cuando el problema era imposible de prever",
      ],
    },
    {
      id: "common_artisan", name: "Artesano común", category: "labor",
      overview: "Aprendiste un oficio manual concreto: carpintería, metal, textiles, reparación u otra práctica apropiada a tu historia. No eres automáticamente un Workshop Fixer; tu fortaleza es la experiencia repetida con materiales, herramientas y clientes de tu propio oficio.",
      trait: { name: "Practiced Hands", description: "Obtienes +X Power al fabricar, reparar o valorar materiales dentro del oficio que declaraste al crear el personaje." },
      feature: { name: "Trade Knowledge", description: "Sabes qué herramientas, materiales y profesionales suelen necesitarse y cómo reconocer trabajo competente dentro de tu especialidad.", limits: "No concede certificación Tres ni conocimiento de tecnología de Workshop fuera de tu formación." },
      loreTerms: ["city", "workshop"], loreSources: ["workshops"],
      ideals: [
        "Calidad|Una pieza bien hecha debe seguir funcionando después de que el cliente deje de pensar en quién la construyó",
        "Paciencia|Los materiales imponen su ritmo y apresurar un trabajo delicado suele crear una reparación más cara después",
        "Independencia|Dominar un oficio significa poder intercambiar habilidad real por recursos sin depender completamente de una gran organización",
        "Tradición|Técnicas transmitidas por maestros y compañeros merecen preservarse antes de cambiarlas sólo por parecer antiguas",
        "Utilidad|Prefieres crear algo que resuelva un problema cotidiano a una obra impresionante que nadie pueda mantener",
        "Honestidad profesional|Un artesano debe decir cuándo algo está mal hecho, incluso si admitirlo cuesta dinero o reputación",
        "Dejar algo bien hecho|La mejor parte del oficio es saber que una estructura, herramienta u objeto continuará sirviendo después de que tú te marches",
      ],
      bonds: [
        "Mi maestro|La persona que te enseñó el oficio sigue siendo la medida con la que comparas tu propio trabajo",
        "Mi taller|Un espacio de trabajo concreto representa años de esfuerzo, herramientas y rutinas que todavía consideras hogar",
        "Herramienta heredada|Conservas una herramienta cuyo valor real está en quién la usó antes y lo que aprendiste con ella",
        "Mi mejor obra|Existe un objeto o estructura que consideras la demostración más clara de lo que eres capaz de hacer",
        "Cliente recurrente|Una persona confió en tu oficio durante años y terminó conociéndote mejor de lo que esperabas de una relación comercial",
        "Aprendiz|En algún momento enseñaste a alguien y todavía sientes responsabilidad por lo que esa persona hace con tus técnicas",
        "Encargo inconcluso|Un trabajo quedó sin terminar y aún existe alguien esperando, reclamando o recordando aquello que prometiste construir",
      ],
      flaws: [
        "Perfeccionismo|Puedes gastar recursos y tiempo intentando corregir detalles que ya no afectan realmente la función del trabajo",
        "Desprecio por trabajo mediocre|Juzgas muy rápido a una persona por una reparación mala sin saber qué herramientas, tiempo o condiciones tuvo disponibles",
        "Herramientas viejas|Te aferras a equipo conocido aunque exista una alternativa mejor porque conoces cada defecto de lo que ya usas",
        "El oficio define a la persona|Preguntar qué sabe construir alguien puede importarte demasiado al decidir cuánto respetarlo",
        "Trabajo excesivo|Cuando tienes las manos ocupadas te resulta más fácil ignorar cansancio, emociones y problemas que no puedes reparar físicamente",
        "No interfieras|Reaccionas mal cuando alguien toca tu trabajo, cambia tu método o intenta ayudarte sin entender lo que estás haciendo",
        "Todo debería poder repararse|Te cuesta aceptar que un objeto, relación o situación puede haber llegado a un punto donde insistir sólo causa más daño",
      ],
    },
    {
      id: "industrial_worker", name: "Trabajador industrial", category: "labor",
      overview: "Trabajaste en una fábrica, planta, línea de producción u otra instalación industrial. Conoces turnos, riesgos, mantenimiento básico y la disciplina necesaria para repetir procesos durante horas sin olvidar que una máquina mal tratada puede herir a todo un equipo.",
      trait: { name: "Factory Routine", description: "Obtienes +X Power en Checks sobre maquinaria, procedimientos y riesgos industriales semejantes a los de tu experiencia." },
      feature: { name: "Factory Hand", description: "Reconoces la lógica de turnos, zonas de seguridad, supervisión y cultura laboral de una instalación industrial.", limits: "No te convierte en ingeniero ni concede conocimiento de Singularities o maquinaria clasificada." },
      loreTerms: ["city", "wing"], loreSources: ["city"],
      ideals: [
        "Solidaridad laboral|Una línea sólo funciona porque muchas personas dependen unas de otras y abandonar a un compañero puede poner a todos en peligro",
        "Eficiencia|Los movimientos, herramientas y tiempos correctos reducen errores; respetas procesos que eliminan trabajo inútil sin sacrificar seguridad",
        "Seguridad|Ningún objetivo de producción justifica tratar una lesión evitable como coste normal del turno",
        "Resistencia|Aprendiste que muchas jornadas se superan continuando paso a paso incluso cuando no existe una solución elegante al cansancio",
        "Estabilidad|Un salario predecible y un puesto que mañana siga existiendo pueden significar más que prestigio en una Ciudad inestable",
        "Dignidad del trabajo|Que una tarea sea repetitiva o física no la vuelve menos esencial que las decisiones tomadas en una oficina ejecutiva",
        "No ser una pieza reemplazable|Haber visto cómo una empresa sustituye trabajadores te impulsa a construir una vida donde tu valor no dependa de una línea de producción",
      ],
      bonds: [
        "Mi cuadrilla|Las personas de tu turno aprendieron a cubrir errores y ritmos mutuamente hasta convertirse en una pequeña comunidad",
        "Supervisor|Una figura de mando protegió a la plantilla o la explotó de una forma que todavía define cómo reaccionas ante jefes",
        "La fábrica|Una instalación concreta fue el escenario de una parte enorme de tu vida y aún conoces sus sonidos, rutas y horarios",
        "Accidente|Un fallo de máquina o procedimiento hirió a alguien y cambió tu relación con el trabajo industrial",
        "Compañero lesionado|Una persona no pudo seguir trabajando después de un incidente y todavía sientes que la empresa, el equipo o tú le deben algo",
        "La máquina que conocía|Había una pieza de equipo cuyo comportamiento podías reconocer por sonido o vibración antes que cualquier técnico externo",
        "Personas sostenidas por mi salario|Familia o dependientes construyeron su estabilidad alrededor de tu trabajo y perderlo tuvo consecuencias para todos",
      ],
      flaws: [
        "Normalizo riesgo|Años de señales, ruido y accidentes menores pueden hacerte aceptar condiciones que alguien externo identificaría inmediatamente como peligrosas",
        "Trabajo herido|Estás acostumbrado a terminar el turno y puedes ocultar dolor o fatiga hasta convertir un problema pequeño en una incapacidad real",
        "Desconfío de gerencia|Una orden de alguien que no pisa la planta te parece sospechosa por defecto aunque pueda tener información que tú no tienes",
        "Todo es producción|Bajo presión intentas medir personas por ritmo, resultados y utilidad como si el grupo fuera una línea que necesita cuota",
        "No sé descansar|La inactividad puede hacerte sentir culpable porque aprendiste a asociar valor personal con seguir produciendo",
        "Aguanto hasta explotar|Tolerar condiciones malas durante demasiado tiempo puede hacer que tu reacción final sea mucho más fuerte de lo necesario",
        "Procedimiento familiar|Confías demasiado en prácticas de tu antigua planta y puedes aplicarlas a maquinaria o instalaciones que funcionan con reglas diferentes",
      ],
    },
    {
      id: "backstreets_heavy_worker", name: "Trabajador pesado de Backstreets", category: "labor",
      overview: "Ganaste la vida moviendo carga, demoliendo, construyendo o realizando trabajo físico duro en las Backstreets. Tu experiencia no es simplemente ser fuerte: aprendiste a usar palancas, ritmo, postura y trabajo en equipo para sobrevivir a jornadas donde una mala decisión lesiona a alguien.",
      trait: { name: "Hard Labor", description: "Obtienes +X Power en Athletics cuando la tarea sea carga, arrastre, demolición, construcción u otro trabajo físico profesional de tu experiencia." },
      feature: { name: "Working Hands", description: "Puedes reconocer cuadrillas, capataces, herramientas y lugares donde se contrata mano de obra común.", limits: "No concede fuerza sobrenatural ni sustituye equipo especializado." },
      loreTerms: ["backstreets"], loreSources: ["backstreets"],
      ideals: [
        "Esfuerzo|Crees que la constancia y la técnica importan más que presumir fuerza cuando el trabajo debe repetirse cada día",
        "Comunidad|Una cuadrilla sobrevive cubriéndose mutuamente y ninguna carga vale dejar a un compañero debajo de ella",
        "Supervivencia|El trabajo puede ser injusto, pero aprender a dosificar energía y conservar el cuerpo permite llegar al siguiente día",
        "Dignidad|Rechazas que alguien trate el trabajo físico como señal de menor inteligencia o valor social",
        "Fiabilidad|Quieres ser la persona que aparece, termina la tarea y no abandona a los demás cuando el turno se vuelve peligroso",
        "Fuerza para otros|Tener capacidad física sólo vale si puedes utilizarla para levantar, proteger o ayudar a quien no puede hacerlo solo",
        "Independencia|Un cuerpo entrenado y un oficio transportable significan que siempre puedes buscar otro trabajo aunque pierdas un empleador",
      ],
      bonds: [
        "Mi cuadrilla|Personas con las que compartiste turnos y cargas conocen tus límites mejor que muchos amigos íntimos",
        "Capataz justo|Una figura de autoridad trató a la gente como trabajadores y no como material reemplazable, algo suficientemente raro para que lo recuerdes",
        "Quien dependía de mí|Tu salario mantenía a otra persona y aún sientes responsabilidad por lo que ocurrió cuando dejaste el trabajo",
        "Lugar construido|Ayudaste físicamente a levantar, reparar o demoler algo que todavía existe y que puedes señalar diciendo que tus manos estuvieron allí",
        "Lesión antigua|Una herida relacionada con el oficio te recuerda una jornada, compañero o error que cambió la manera en que trabajas",
        "Compañero muerto|Alguien no regresó de un turno peligroso y su ausencia sigue siendo la medida de lo que consideras un riesgo aceptable",
        "Primera paga|Conservas el recuerdo u objeto comprado con el primer dinero que sentiste verdaderamente ganado por tu propio esfuerzo",
      ],
      flaws: [
        "Fuerza primero|Ante un obstáculo físico intentas moverlo, romperlo o empujarlo antes de considerar una solución más delicada",
        "Ignoro límites|Estar acostumbrado al dolor y cansancio puede hacerte continuar cuando tu cuerpo ya está avisando que debes detenerte",
        "Desprecio trabajo de escritorio|Puedes asumir que quien no realiza trabajo físico no entiende esfuerzo real, aunque sus responsabilidades sean diferentes",
        "Cargo problemas ajenos|Te resulta natural aceptar la parte más pesada de una tarea y puedes terminar tomando responsabilidades que nadie te pidió",
        "Acepto demasiado peligro|Si un trabajo paga bien o el grupo necesita dinero, tiendes a normalizar condiciones que deberías rechazar",
        "Me cuesta pedir ayuda|La identidad de ser quien puede cargar con algo hace que admitir que necesitas apoyo se sienta como fracaso",
        "Descansar es ser inútil|Cuando no estás haciendo algo físicamente productivo puedes sentir que no estás aportando nada al grupo",
      ],
    },
    {
      id: "farmer", name: "Agricultor", category: "labor",
      overview: "Trabajaste produciendo alimentos mediante cultivos o labores agrícolas. El Background no presupone una Wing concreta: tu granja pudo estar dentro o fuera de un Nest, pero tu experiencia se centra en ciclos de producción, suelo, clima controlable o no, almacenamiento y la comunidad que depende de la cosecha.",
      trait: { name: "Cultivator", description: "Obtienes +X Power en Checks sobre agricultura, cultivos, suelo y producción alimentaria dentro de tu experiencia." },
      feature: { name: "Agricultural Life", description: "Reconoces necesidades de productores, herramientas, almacenamiento y problemas comunes de comunidades agrícolas.", limits: "No garantiza conocimiento de técnicas corporativas propietarias ni de todos los cultivos de la Ciudad." },
      loreTerms: ["city", "wing"], loreSources: ["city"],
      ideals: [
        "Paciencia|Una cosecha no puede apresurarse más allá de ciertos límites y aprendiste a trabajar hoy por resultados que quizá lleguen meses después",
        "Sustento|Producir comida es una responsabilidad concreta porque alguien terminará dependiendo de que la cosecha exista cuando llegue el momento",
        "Comunidad|Agricultores, transportistas y compradores forman una cadena donde una mala temporada puede afectar a muchas familias al mismo tiempo",
        "Tradición|Técnicas transmitidas durante generaciones contienen conocimiento que no siempre aparece en manuales o especificaciones",
        "Adaptación|Suelo, clima, plagas y mercado cambian; sobrevivir significa observar qué funciona ahora en lugar de obedecer una receta antigua",
        "Trabajo honesto|Valoras poder señalar un producto tangible y saber exactamente qué trabajo permitió que existiera",
        "Preservación|Una tierra, método o semilla útil merece protegerse porque perder capacidad de producir alimento crea dependencia inmediata",
      ],
      bonds: [
        "Mi parcela|Una extensión de tierra, instalación o cultivo concreto representa años de trabajo y una vida que quizá ya no existe",
        "Familia|El trabajo agrícola estaba unido a familiares o personas con quienes compartías cosechas, deudas y temporadas malas",
        "Cosecha perdida|Una plaga, desastre o decisión destruyó una temporada y cambió lo que tu comunidad podía permitirse",
        "Vecino|Otra familia o productor intercambiaba ayuda, herramientas y conocimiento contigo cuando ninguno podía resolver todo solo",
        "Herramienta|Conservas una pieza de trabajo agrícola reparada tantas veces que forma parte de tus recuerdos cotidianos",
        "Cultivo particular|Una variedad o producto concreto define tu especialidad y puede ser la razón por la que ciertas personas conocían tu nombre",
        "Quien dependía de nosotros|Un comprador, comunidad o familia necesitaba tu producción de una forma que iba más allá de una simple transacción comercial",
      ],
      flaws: [
        "Desconfío de citadinos|Puedes asumir que quien vive lejos de la producción no comprende de dónde vienen los recursos que consume",
        "Terquedad de método|Una técnica que funcionó durante años puede resultarte difícil de abandonar aunque el entorno haya cambiado",
        "No desperdiciar comida|Tirar alimentos te resulta tan ofensivo que puedes conservarlos o arriesgarte más de lo prudente para recuperarlos",
        "No abandono la tierra|Seguir trabajando un lugar improductivo puede convertirse en orgullo aunque mudarte sea la opción racional",
        "Valor igual a utilidad|Puedes juzgar actividades o personas según lo que producen de manera inmediata, ignorando trabajos menos visibles",
        "Salvar la cosecha|Cuando meses de trabajo están en peligro aceptas riesgos físicos o económicos que no aceptarías por casi ninguna otra cosa",
        "Mi ritmo es el natural|Te cuesta adaptarte a ambientes donde decisiones, viajes o trabajo ocurren con una urgencia constante y sin ciclos previsibles",
      ],
    },
  ]);
})(typeof window !== "undefined" ? window : globalThis);
