(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.LuminousVttElevator=api;})(typeof window!=='undefined'?window:globalThis,function(root){'use strict';
const SCHEMA_VERSION=1,DEFAULT_SPEED_FPS=12,DEFAULT_DOOR_TIME_MS=650;
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,clean=v=>String(v??'').trim(),clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
function elevationForLayer(mapData={},zLayer=0){const spatial=root?.LuminousVttSpatialVision;if(spatial?.elevationForLayer)return spatial.elevationForLayer(mapData,zLayer);const record=mapData.zLevels?.[String(zLayer)]||mapData.zLevels?.[zLayer];if(Number.isFinite(Number(record?.elevationFt)))return Number(record.elevationFt);return Number(zLayer||0)*Math.max(1,finite(mapData.defaultZStepFt,15));}
function availableLayers(mapData={}){const levels=mapData.zLevels||{};const rows=Array.isArray(levels)?levels.map(x=>Number(x?.zLayer??x?.z)):Object.entries(levels).map(([k,v])=>Number(v?.zLayer??v?.z??k));return[...new Set(rows.filter(Number.isFinite))].sort((a,b)=>a-b);}
function normalizeStops(rawStops,mapData={},fromZ=0,toZ=1){let stops=Array.isArray(rawStops)?rawStops.map(Number).filter(Number.isFinite):[];if(!stops.length){const lo=Math.min(Number(fromZ)||0,Number(toZ)||0),hi=Math.max(Number(fromZ)||0,Number(toZ)||0),known=availableLayers(mapData).filter(z=>z>=lo&&z<=hi);stops=known.length?known:[lo,hi];}stops=[...new Set(stops.map(z=>Math.trunc(z)))].sort((a,b)=>a-b);if(stops.length<2){const z=stops[0]??(Number(fromZ)||0);stops=[z,z+1];}return stops;}
function gridBounds(mapData={}){return{cols:Math.max(1,Math.trunc(finite(mapData.grid?.cols,1))),rows:Math.max(1,Math.trunc(finite(mapData.grid?.rows,1))),size:Math.max(1,finite(mapData.grid?.size,70))};}
function footprintFromVertices(from={},to={},mapData={}){const g=gridBounds(mapData),aCol=Math.max(0,Math.min(g.cols,Math.trunc(finite(from.col)))),aRow=Math.max(0,Math.min(g.rows,Math.trunc(finite(from.row)))),bCol=Math.max(0,Math.min(g.cols,Math.trunc(finite(to.col)))),bRow=Math.max(0,Math.min(g.rows,Math.trunc(finite(to.row))));let minCol=Math.min(aCol,bCol),maxCol=Math.max(aCol,bCol),minRow=Math.min(aRow,bRow),maxRow=Math.max(aRow,bRow);if(maxCol===minCol)maxCol=Math.min(g.cols,minCol+1);if(maxRow===minRow)maxRow=Math.min(g.rows,minRow+1);if(maxCol===minCol&&minCol>0)minCol-=1;if(maxRow===minRow&&minRow>0)minRow-=1;return{minCol,minRow,maxColExclusive:maxCol,maxRowExclusive:maxRow};}
function normalizeFootprint(raw={},mapData={}){if(raw&&Number.isFinite(Number(raw.minCol))){const g=gridBounds(mapData);const minCol=Math.max(0,Math.min(g.cols-1,Math.trunc(finite(raw.minCol)))),minRow=Math.max(0,Math.min(g.rows-1,Math.trunc(finite(raw.minRow)))),maxColExclusive=Math.max(minCol+1,Math.min(g.cols,Math.trunc(finite(raw.maxColExclusive??raw.maxCol??(minCol+1))))),maxRowExclusive=Math.max(minRow+1,Math.min(g.rows,Math.trunc(finite(raw.maxRowExclusive??raw.maxRow??(minRow+1)))));return{minCol,minRow,maxColExclusive,maxRowExclusive};}return footprintFromVertices(raw.from||raw.a||{},raw.to||raw.b||{},mapData);}
function footprintRect(raw={},mapData={}){const f=raw.footprint?normalizeFootprint(raw.footprint,mapData):footprintFromVertices(raw.from,raw.to,mapData),{size}=gridBounds(mapData);return{x:f.minCol*size,y:f.minRow*size,width:(f.maxColExclusive-f.minCol)*size,height:(f.maxRowExclusive-f.minRow)*size};}
function footprintCells(raw={},mapData={}){const f=raw.footprint?normalizeFootprint(raw.footprint,mapData):footprintFromVertices(raw.from,raw.to,mapData),out=[];for(let row=f.minRow;row<f.maxRowExclusive;row+=1)for(let col=f.minCol;col<f.maxColExclusive;col+=1)out.push({col,row});return out;}
function pointInFootprint(raw={},point={},mapData={}){const r=footprintRect(raw,mapData),x=finite(point.x),y=finite(point.y);return x>=r.x&&x<=r.x+r.width&&y>=r.y&&y<=r.y+r.height;}
function tokenLayer(token={}){if(Number.isFinite(Number(token.zLayer)))return Number(token.zLayer);if(Number.isFinite(Number(token.gridPosition?.z)))return Number(token.gridPosition.z);if(Array.isArray(token.z)&&token.z.length)return Number(token.z[0])||0;return 0;}
function cabinCenter(raw={},mapData={}){const r=footprintRect(raw,mapData);return{x:r.x+r.width/2,y:r.y+r.height/2};}
function normalizeElevator(raw={},mapData={},base={}){const fromZ=Number(raw.between?.[0]??base.between?.[0]??raw.fromZ??0)||0,toZ=Number(raw.between?.[1]??base.between?.[1]??raw.toZ??1)||1,stops=normalizeStops(raw.stops||raw.elevator?.stops,mapData,fromZ,toZ);let currentZ=Number(raw.currentZ??raw.elevator?.currentZ);if(!stops.includes(currentZ))currentZ=stops.includes(fromZ)?fromZ:stops[0];const targetCandidate=Number(raw.targetZ??raw.elevator?.targetZ),targetZ=stops.includes(targetCandidate)&&targetCandidate!==currentZ?targetCandidate:null;const motionState=(raw.motionState??raw.elevator?.motionState)==='moving'&&targetZ!=null?'moving':'idle',doorState=motionState==='moving'?'closed':((raw.doorState??raw.elevator?.doorState)==='closed'?'closed':'open'),footprint=normalizeFootprint(raw.footprint||raw.elevator?.footprint||{from:base.from||raw.from,to:base.to||raw.to},mapData),speedFtPerSecond=Math.max(1,finite(raw.speedFtPerSecond??raw.elevator?.speedFtPerSecond,DEFAULT_SPEED_FPS)),startedAt=Math.max(0,finite(raw.startedAt??raw.elevator?.startedAt,0)),arriveAt=Math.max(startedAt,finite(raw.arriveAt??raw.elevator?.arriveAt,0)),passengerIds=[...new Set((Array.isArray(raw.passengerIds??raw.elevator?.passengerIds)?(raw.passengerIds??raw.elevator?.passengerIds):[]).map(clean).filter(Boolean))];return{schemaVersion:SCHEMA_VERSION,stops,footprint,currentZ,targetZ,motionState,doorState,powered:(raw.powered??raw.elevator?.powered)!==false,circuitId:clean(raw.circuitId??raw.elevator?.circuitId),speedFtPerSecond,doorTimeMs:Math.max(0,finite(raw.doorTimeMs??raw.elevator?.doorTimeMs,DEFAULT_DOOR_TIME_MS)),startedAt,arriveAt,fromElevationFt:Number.isFinite(Number(raw.fromElevationFt??raw.elevator?.fromElevationFt))?Number(raw.fromElevationFt??raw.elevator?.fromElevationFt):elevationForLayer(mapData,currentZ),targetElevationFt:Number.isFinite(Number(raw.targetElevationFt??raw.elevator?.targetElevationFt))?Number(raw.targetElevationFt??raw.elevator?.targetElevationFt):(targetZ==null?elevationForLayer(mapData,currentZ):elevationForLayer(mapData,targetZ)),passengerIds,label:clean(raw.label??raw.elevator?.label)||'ELEVATOR'};}
function createElevatorPortal({from,to,fromZ=0,toZ=1,mapData={},id=null,stops=null,powered=true,speedFtPerSecond=DEFAULT_SPEED_FPS}={}){const portal=root?.LuminousVttVerticalPortal;if(!portal)throw new Error('VERTICAL_PORTAL_RUNTIME_REQUIRED');const seed=portal.createPortal({type:'opening',from,to,fromZ,toZ,mapData});const base={...seed,id:id||String(seed.id||'').replace('vertical_opening_','vertical_elevator_'),type:'elevator',from:seed.from,to:seed.to,between:[fromZ,toZ],state:'open',blocksVision:false,blocksLight:false,allowsMovement:true,movementMode:'elevator',layout:null,widthFt:0,costMultiplier:1,bidirectional:true};const elevator=normalizeElevator({stops,powered,speedFtPerSecond,footprint:{from:base.from,to:base.to},currentZ:fromZ},mapData,base);return{...base,between:[elevator.stops[0],elevator.stops[elevator.stops.length-1]],elevator,...elevator};}
function normalizeElevatorPortal(raw={},mapData={},base={}){const elevator=normalizeElevator(raw,mapData,base);return{...base,...raw,schemaVersion:Math.max(3,Number(base.schemaVersion)||0),type:'elevator',between:[elevator.stops[0],elevator.stops[elevator.stops.length-1]],state:'open',blocksVision:false,blocksLight:false,allowsMovement:true,movementMode:'elevator',bidirectional:true,elevator,...elevator};}
function portalOnLayer(raw={},zLayer,mapData={}){const e=normalizeElevator(raw,mapData,raw);return e.stops.includes(Number(zLayer));}
function currentElevation(raw={},mapData={},now=Date.now()){const e=normalizeElevator(raw,mapData,raw);if(e.motionState!=='moving'||e.targetZ==null||e.arriveAt<=e.startedAt)return elevationForLayer(mapData,e.currentZ);const t=Math.max(0,Math.min(1,(finite(now)-e.startedAt)/(e.arriveAt-e.startedAt)));return e.fromElevationFt+(e.targetElevationFt-e.fromElevationFt)*t;}
function beginTrip(raw={},targetZ,mapData={},now=Date.now(),passengerIds=[]){const e=normalizeElevator(raw,mapData,raw),target=Number(targetZ);if(!e.powered)return{valid:false,reason:'ELEVATOR_UNPOWERED',portal:e};if(e.motionState==='moving')return{valid:false,reason:'ELEVATOR_MOVING',portal:e};if(!e.stops.includes(target))return{valid:false,reason:'ELEVATOR_STOP_UNAVAILABLE',portal:e};if(target===e.currentZ)return{valid:true,alreadyThere:true,portal:{...raw,elevator:{...e,doorState:'open'},...e,doorState:'open'}};const fromElevationFt=elevationForLayer(mapData,e.currentZ),targetElevationFt=elevationForLayer(mapData,target),distanceFt=Math.abs(targetElevationFt-fromElevationFt),travelMs=Math.max(250,Math.ceil(distanceFt/e.speedFtPerSecond*1000));const next={...e,targetZ:target,motionState:'moving',doorState:'closed',startedAt:Number(now),arriveAt:Number(now)+travelMs,fromElevationFt,targetElevationFt,passengerIds:[...new Set((passengerIds||[]).map(clean).filter(Boolean))]};return{valid:true,travelMs,portal:{...raw,...next,elevator:clone(next)}};}
function completeTrip(raw={},mapData={},now=Date.now()){const e=normalizeElevator(raw,mapData,raw);if(e.motionState!=='moving'||e.targetZ==null)return{valid:false,reason:'ELEVATOR_NOT_MOVING',portal:raw};if(Number(now)+1<e.arriveAt)return{valid:false,reason:'ELEVATOR_IN_TRANSIT',portal:raw};const arrivedZ=e.targetZ,next={...e,currentZ:arrivedZ,targetZ:null,motionState:'idle',doorState:'open',startedAt:0,arriveAt:0,fromElevationFt:elevationForLayer(mapData,arrivedZ),targetElevationFt:elevationForLayer(mapData,arrivedZ),passengerIds:[]};return{valid:true,arrived:true,arrivedZ,passengerIds:e.passengerIds,portal:{...raw,...next,elevator:clone(next)}};}
function setDoor(raw={},doorState='open',mapData={}){const e=normalizeElevator(raw,mapData,raw);if(e.motionState==='moving')return{valid:false,reason:'ELEVATOR_MOVING',portal:raw};const next={...e,doorState:doorState==='closed'?'closed':'open'};return{valid:true,portal:{...raw,...next,elevator:clone(next)}};}
function tokensInCabin(raw={},tokens=[],mapData={}){const e=normalizeElevator(raw,mapData,raw);if(e.motionState!=='idle'||e.doorState!=='open')return[];return(Array.isArray(tokens)?tokens:[]).filter(token=>tokenLayer(token)===e.currentZ&&!token.verticalMovement&&pointInFootprint(e,token,mapData));}
function attachPassengers(tokens=[],portal={},mapData={}){const e=normalizeElevator(portal,mapData,portal),ids=new Set(e.passengerIds);for(const token of tokens||[]){if(!ids.has(clean(token.id)))continue;token.elevatorRide={elevatorId:clean(portal.id),fromZ:e.currentZ,toZ:e.targetZ,startedAt:e.startedAt,arriveAt:e.arriveAt};token.elevationFt=e.fromElevationFt;}return tokens;}
function updatePassengerElevation(tokens=[],portal={},mapData={},now=Date.now()){const e=normalizeElevator(portal,mapData,portal),ids=new Set(e.passengerIds),elevation=currentElevation(portal,mapData,now);for(const token of tokens||[]){if(!ids.has(clean(token.id)))continue;if(token.elevatorRide?.elevatorId!==clean(portal.id))token.elevatorRide={elevatorId:clean(portal.id),fromZ:e.currentZ,toZ:e.targetZ,startedAt:e.startedAt,arriveAt:e.arriveAt};token.elevationFt=elevation;}return elevation;}
function arrivePassengers(tokens=[],passengerIds=[],targetZ,mapData={}){const ids=new Set((passengerIds||[]).map(clean)),elevation=elevationForLayer(mapData,targetZ);for(const token of tokens||[]){if(!ids.has(clean(token.id)))continue;token.zLayer=Number(targetZ);token.z=[Number(targetZ)];token.elevationFt=elevation;token.gridPosition={...(token.gridPosition||{}),z:Number(targetZ)};token.lastVerticalTravel={routeId:token.elevatorRide?.elevatorId||null,fromZ:token.elevatorRide?.fromZ??null,toZ:Number(targetZ),movementMode:'elevator',costSpentFt:0};delete token.elevatorRide;}return tokens;}
function shaftOpeningSpecs(raw={},mapData={}){const e=normalizeElevator(raw,mapData,raw),f=e.footprint,out=[];for(let i=1;i<e.stops.length;i+=1){const lower=e.stops[i-1],upper=e.stops[i];out.push({id:`floor_shaft_${clean(raw.id)||'elevator'}_${upper}_${lower}`,type:'shaft',zLayer:upper,toZLayer:lower,between:[upper,lower],footprint:{minCol:f.minCol,minRow:f.minRow,maxCol:f.maxColExclusive-1,maxRow:f.maxRowExclusive-1},state:'open',allowsMovementThrough:false,allowsVisionThrough:true,allowsLightThrough:true,fallThrough:true,walkable:false,label:`ELEVATOR SHAFT · ${clean(raw.id)}`});}return out;}
function requiredFloorOpeningIds(raw={},mapData={}){return shaftOpeningSpecs(raw,mapData).map(x=>x.id);}
function withTerminalStop(raw={},fromZ,toZ,mapData={}){const e=normalizeElevator(raw,mapData,raw),stops=normalizeStops(null,mapData,fromZ,toZ),currentZ=stops.includes(e.currentZ)?e.currentZ:stops[0];return normalizeElevatorPortal({...raw,between:[fromZ,toZ],stops,currentZ,targetZ:null,motionState:'idle',doorState:'open'},mapData,raw);}
function hitTest(portals=[],point={},mapData={},zLayer=0){for(const raw of portals||[]){if(raw?.type!=='elevator')continue;const e=normalizeElevatorPortal(raw,mapData,raw);if(!e.stops.includes(Number(zLayer)))continue;if(pointInFootprint(e,point,mapData))return e;}return null;}
return Object.freeze({SCHEMA_VERSION,DEFAULT_SPEED_FPS,DEFAULT_DOOR_TIME_MS,elevationForLayer,availableLayers,normalizeStops,gridBounds,footprintFromVertices,normalizeFootprint,footprintRect,footprintCells,pointInFootprint,tokenLayer,cabinCenter,normalizeElevator,normalizeElevatorPortal,createElevatorPortal,portalOnLayer,currentElevation,beginTrip,completeTrip,setDoor,tokensInCabin,attachPassengers,updatePassengerElevation,arrivePassengers,shaftOpeningSpecs,requiredFloorOpeningIds,withTerminalStop,hitTest});});