(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.LuminousVttRamp=api;})(typeof window!=='undefined'?window:globalThis,function(root){'use strict';
const SCHEMA_VERSION=1,DEFAULT_WIDTH_FT=5,DEFAULT_MAX_GRADE=.5;
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,clean=v=>String(v??'').trim();
function elevationForLayer(mapData={},z=0){const spatial=root?.LuminousVttSpatialVision;if(spatial?.elevationForLayer)return spatial.elevationForLayer(mapData,z);const rec=mapData.zLevels?.[String(z)]||mapData.zLevels?.[z];if(Number.isFinite(Number(rec?.elevationFt)))return Number(rec.elevationFt);return Number(z||0)*Math.max(1,finite(mapData.defaultZStepFt,15));}
function feetPerPixel(mapData={}){return Math.max(.001,finite(mapData.grid?.distancePerCell,5))/Math.max(1,finite(mapData.grid?.size,70));}
function pointForVertex(v={},mapData={}){const spatial=root?.LuminousVttSpatialVision;if(spatial?.vertexToPoint)return spatial.vertexToPoint(v,mapData);const s=Math.max(1,finite(mapData.grid?.size,70));return{x:finite(v.col)*s,y:finite(v.row)*s};}
function layers(raw={}){const b=Array.isArray(raw.between)?raw.between:[raw.fromZ??0,raw.toZ??1];return[Number(b[0])||0,Number(b[1])||0];}
function layerOrder(mapData={}){const rows=Array.isArray(mapData.zLevels)?mapData.zLevels.map(x=>Number(x?.zLayer??x?.z)):Object.entries(mapData.zLevels||{}).map(([k,v])=>Number(v?.zLayer??v?.z??k));return[...new Set(rows.filter(Number.isFinite))].sort((a,b)=>elevationForLayer(mapData,a)-elevationForLayer(mapData,b));}
function adjacentLayers(mapData={},a,b){const order=layerOrder(mapData);const ia=order.indexOf(Number(a)),ib=order.indexOf(Number(b));return ia>=0&&ib>=0&&Math.abs(ia-ib)===1;}
function metrics(raw={},mapData={}){const [fromZ,toZ]=layers(raw),a=pointForVertex(raw.from,mapData),b=pointForVertex(raw.to,mapData),horizontalRunFt=Math.hypot(b.x-a.x,b.y-a.y)*feetPerPixel(mapData),riseFt=Math.abs(elevationForLayer(mapData,toZ)-elevationForLayer(mapData,fromZ)),pathLengthFt=Math.hypot(horizontalRunFt,riseFt),grade=horizontalRunFt>1e-9?riseFt/horizontalRunFt:Infinity;return{fromZ,toZ,a,b,horizontalRunFt,riseFt,pathLengthFt,grade,gradePercent:grade*100,angleDeg:Math.atan(grade)*180/Math.PI};}
function normalizeRampPortal(raw={},mapData={},base={}){const m=metrics({...base,...raw},mapData),widthFt=Math.max(2,finite(raw.widthFt??raw.ramp?.widthFt,DEFAULT_WIDTH_FT)),maxGrade=Math.max(.05,finite(raw.maxGrade??raw.ramp?.maxGrade,DEFAULT_MAX_GRADE)),costMultiplier=Math.max(1,finite(raw.costMultiplier??raw.ramp?.costMultiplier,1)),railings=(raw.railings??raw.ramp?.railings)!==false;const ramp={schemaVersion:SCHEMA_VERSION,widthFt,maxGrade,costMultiplier,railings,horizontalRunFt:m.horizontalRunFt,riseFt:m.riseFt,pathLengthFt:m.pathLengthFt,grade:m.grade,gradePercent:m.gradePercent,angleDeg:m.angleDeg,validSlope:Number.isFinite(m.grade)&&m.grade<=maxGrade+1e-9,adjacent:adjacentLayers(mapData,m.fromZ,m.toZ)};return{...base,...raw,schemaVersion:Math.max(3,Number(base.schemaVersion)||0),type:'ramp',between:[m.fromZ,m.toZ],state:raw.state==='closed'?'closed':'open',allowsMovement:raw.allowsMovement!==false,movementMode:'walk',layout:'ramp',widthFt,costMultiplier,bidirectional:raw.bidirectional!==false,blocksVision:false,blocksLight:false,ramp,...ramp};}
function validate(raw={},mapData={}){const r=normalizeRampPortal(raw,mapData,raw);if(!r.adjacent)return{valid:false,reason:'RAMP_ADJACENT_FLOORS_REQUIRED',ramp:r};if(r.horizontalRunFt<=1e-9)return{valid:false,reason:'RAMP_RUN_REQUIRED',ramp:r};if(!r.validSlope)return{valid:false,reason:'RAMP_TOO_STEEP',ramp:r,requiredRunFt:r.riseFt/r.maxGrade};return{valid:true,ramp:r};}
function createRampPortal({from,to,fromZ=0,toZ=1,mapData={},widthFt=DEFAULT_WIDTH_FT,maxGrade=DEFAULT_MAX_GRADE,costMultiplier=1,railings=true}={}){const portals=root?.LuminousVttVerticalPortal;if(!portals)throw new Error('VERTICAL_PORTAL_RUNTIME_REQUIRED');const base=portals.createPortal({type:'ramp',from,to,fromZ,toZ,mapData,widthFt});return normalizeRampPortal({...base,widthFt,maxGrade,costMultiplier,railings},mapData,base);}
function routeFor(raw={},mapData={}){const r=normalizeRampPortal(raw,mapData,raw),m=metrics(r,mapData);return{id:clean(r.id),portalId:clean(r.id),type:'ramp',layout:'ramp',widthFt:r.widthFt,fromZ:m.fromZ,toZ:m.toZ,points:[{x:m.a.x,y:m.a.y,elevationFt:elevationForLayer(mapData,m.fromZ),zLayer:m.fromZ},{x:m.b.x,y:m.b.y,elevationFt:elevationForLayer(mapData,m.toZ),zLayer:m.toZ}],pathLengthFt:m.pathLengthFt,movementMode:'walk',costMultiplier:r.costMultiplier,bidirectional:r.bidirectional,grade:r.grade,gradePercent:r.gradePercent,angleDeg:r.angleDeg};}
function perpendicular(a,b){const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;return{x:-dy/len,y:dx/len};}
function geometryFor(raw={},mapData={}){const r=normalizeRampPortal(raw,mapData,raw),route=routeFor(r,mapData),a=route.points[0],b=route.points[1],n=perpendicular(a,b),half=(r.widthFt/feetPerPixel(mapData))/2,corners=[{x:a.x+n.x*half,y:a.y+n.y*half},{x:b.x+n.x*half,y:b.y+n.y*half},{x:b.x-n.x*half,y:b.y-n.y*half},{x:a.x-n.x*half,y:a.y-n.y*half}];return{portal:r,route,corners,centerline:{from:a,to:b},railings:r.railings?[{from:corners[0],to:corners[1]},{from:corners[3],to:corners[2]}]:[]};}
function openingSpec(raw={},mapData={}){const r=normalizeRampPortal(raw,mapData,raw),g=geometryFor(r,mapData),size=Math.max(1,finite(mapData.grid?.size,70)),xs=g.corners.map(p=>p.x),ys=g.corners.map(p=>p.y),cols=Math.max(1,Math.trunc(finite(mapData.grid?.cols,1))),rows=Math.max(1,Math.trunc(finite(mapData.grid?.rows,1))),minCol=Math.max(0,Math.min(cols-1,Math.floor(Math.min(...xs)/size))),maxCol=Math.max(minCol,Math.min(cols-1,Math.floor((Math.max(...xs)-1e-6)/size))),minRow=Math.max(0,Math.min(rows-1,Math.floor(Math.min(...ys)/size))),maxRow=Math.max(minRow,Math.min(rows-1,Math.floor((Math.max(...ys)-1e-6)/size))),[fromZ,toZ]=layers(r),upper=elevationForLayer(mapData,fromZ)>=elevationForLayer(mapData,toZ)?fromZ:toZ,lower=upper===fromZ?toZ:fromZ;return{id:`floor_ramp_${clean(r.id)}_${upper}_${lower}`,type:'stairwell',zLayer:upper,toZLayer:lower,between:[upper,lower],footprint:{minCol,minRow,maxCol,maxRow},state:'open',allowsMovementThrough:true,allowsVisionThrough:true,allowsLightThrough:true,fallThrough:true,walkable:false,label:`RAMP OPENING · ${clean(r.id)}`};}
return Object.freeze({SCHEMA_VERSION,DEFAULT_WIDTH_FT,DEFAULT_MAX_GRADE,elevationForLayer,feetPerPixel,pointForVertex,layers,layerOrder,adjacentLayers,metrics,normalizeRampPortal,validate,createRampPortal,routeFor,geometryFor,openingSpec});});