(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.LuminousVttStairBuilder=api;})(typeof window!=='undefined'?window:globalThis,function(root){'use strict';
const SCHEMA_VERSION=1;
const DEFAULT_DEFINITIONS=Object.freeze({
 'stairs:straight':Object.freeze({id:'stairs:straight',name:'Straight Stair',layout:'straight',targetRiserFt:.75,targetTreadFt:1,landingDepthFt:3,railings:true}),
 'stairs:switchback':Object.freeze({id:'stairs:switchback',name:'Switchback Stair',layout:'switchback',targetRiserFt:.75,targetTreadFt:1,landingDepthFt:3,railings:true}),
 'stairs:spiral':Object.freeze({id:'stairs:spiral',name:'Spiral Stair',layout:'spiral',targetRiserFt:.75,targetTreadFt:1,landingDepthFt:2,railings:true}),
 'stairs:ladder':Object.freeze({id:'stairs:ladder',name:'Vertical Ladder',layout:'ladder',targetRiserFt:1,targetTreadFt:0,landingDepthFt:2,railings:false}),
});
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
function portalRuntime(){if(root?.LuminousVttVerticalPortal)return root.LuminousVttVerticalPortal;if(typeof require!=='undefined'){try{return require('./vertical-portal.js');}catch(_){}}return null;}
function routeRuntime(){if(root?.LuminousVttStairRoute)return root.LuminousVttStairRoute;if(typeof require!=='undefined'){try{return require('./stair-route.js');}catch(_){}}return null;}
function definitionFor(layout='straight',definitionId=null){const normalized=String(layout||'straight').toLowerCase();const explicit=definitionId&&DEFAULT_DEFINITIONS[String(definitionId)];if(explicit&&explicit.layout===normalized)return explicit;return DEFAULT_DEFINITIONS[`stairs:${normalized}`]||DEFAULT_DEFINITIONS['stairs:straight'];}
function elevationForLayer(mapData={},zLayer=0){const spatial=root?.LuminousVttSpatialVision;if(spatial?.elevationForLayer)return spatial.elevationForLayer(mapData,zLayer);const record=mapData.zLevels?.[String(zLayer)]||mapData.zLevels?.[zLayer];if(record&&Number.isFinite(Number(record.elevationFt)))return Number(record.elevationFt);return Number(zLayer||0)*Math.max(1,finite(mapData.defaultZStepFt,15));}
function feetPerPixel(mapData={}){const size=Math.max(1,finite(mapData.grid?.size,70));return Math.max(.001,finite(mapData.grid?.distancePerCell,5))/size;}
function vertexPoint(vertex={},mapData={}){const spatial=root?.LuminousVttSpatialVision;if(spatial?.vertexToPoint)return spatial.vertexToPoint(vertex,mapData);const size=Math.max(1,finite(mapData.grid?.size,70));return{x:finite(vertex.col)*size,y:finite(vertex.row)*size};}
function layersOf(portal={}){const values=Array.isArray(portal.between)?portal.between:[portal.fromZ??0,portal.toZ??1];return[Number(values[0])||0,Number(values[1])||0];}
function normalizeBuilder(raw={},portal={},mapData={}){const layout=String(portal.layout||raw.layout||'straight').toLowerCase();const def=definitionFor(layout,portal.definitionId||raw.definitionId);const [fromZ,toZ]=layersOf(portal);const low=elevationForLayer(mapData,fromZ),high=elevationForLayer(mapData,toZ);const a=vertexPoint(portal.from,mapData),b=vertexPoint(portal.to,mapData);const horizontalRunFt=Math.hypot(b.x-a.x,b.y-a.y)*feetPerPixel(mapData);const riseFt=Math.abs(high-low);const targetRiserFt=Math.max(.25,finite(raw.targetRiserFt,def.targetRiserFt));const targetTreadFt=layout==='ladder'?0:Math.max(.25,finite(raw.targetTreadFt,def.targetTreadFt));const byRise=Math.max(1,Math.ceil(riseFt/targetRiserFt));const byRun=targetTreadFt>0?Math.max(1,Math.ceil(horizontalRunFt/targetTreadFt)):1;const stepCount=layout==='straight'?Math.max(byRise,byRun):Math.max(1,Math.trunc(finite(raw.stepCount,byRise)));return{schemaVersion:SCHEMA_VERSION,definitionId:def.id,targetRiserFt,targetTreadFt,landingDepthFt:Math.max(0,finite(raw.landingDepthFt,def.landingDepthFt)),stepCount,riserHeightFt:stepCount?riseFt/stepCount:0,treadDepthFt:layout==='straight'&&stepCount?horizontalRunFt/stepCount:targetTreadFt,horizontalRunFt,riseFt,railings:raw.railings===undefined?def.railings:Boolean(raw.railings)};}
function normalizeStairPortal(raw={},mapData={}){const portals=portalRuntime();if(!portals)return null;const normalized=portals.normalizePortal(raw,mapData);if(normalized.type!=='stairs')return normalized;const def=definitionFor(normalized.layout,raw.definitionId||raw.builder?.definitionId);const builder=normalizeBuilder(raw.builder||{}, {...normalized,definitionId:def.id},mapData);return{...normalized,definitionId:def.id,builder};}
function buildPortal({from,to,fromZ=0,toZ=1,mapData={},layout='straight',widthFt=5,definitionId=null,builder=null}={}){const portals=portalRuntime();if(!portals)throw new Error('VERTICAL_PORTAL_RUNTIME_REQUIRED');const base=portals.createPortal({type:'stairs',from,to,fromZ,toZ,mapData,layout,widthFt});return normalizeStairPortal({...base,definitionId:definitionId||`stairs:${String(layout||'straight').toLowerCase()}`,builder:builder||{}},mapData);}
function straightStepPoints(portal={},mapData={},fromZ=null,toZ=null){const normalized=normalizeStairPortal(portal,mapData);if(!normalized||normalized.type!=='stairs'||normalized.layout!=='straight')return[];const layers=layersOf(normalized),source=fromZ==null?layers[0]:Number(fromZ),target=toZ==null?layers[1]:Number(toZ);const a=vertexPoint(normalized.from,mapData),b=vertexPoint(normalized.to,mapData),low=elevationForLayer(mapData,source),high=elevationForLayer(mapData,target),steps=Math.max(1,Math.trunc(finite(normalized.builder?.stepCount,1))),points=[];for(let i=0;i<=steps;i+=1){const t=i/steps;points.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,elevationFt:low+(high-low)*t,zLayer:i===0?source:i===steps?target:null,stepIndex:i});}return points;}
function boundsForPoints(points=[],paddingPx=0){if(!points.length)return{x:0,y:0,width:0,height:0};const xs=points.map(p=>finite(p.x)),ys=points.map(p=>finite(p.y)),minX=Math.min(...xs)-paddingPx,maxX=Math.max(...xs)+paddingPx,minY=Math.min(...ys)-paddingPx,maxY=Math.max(...ys)+paddingPx;return{x:minX,y:minY,width:maxX-minX,height:maxY-minY};}
function perpendicular(a={},b={}){const dx=finite(b.x)-finite(a.x),dy=finite(b.y)-finite(a.y),len=Math.hypot(dx,dy)||1;return{x:-dy/len,y:dx/len};}
function treadLines(points=[],widthPx=0){const out=[];for(let i=0;i<points.length;i+=1){const current=points[i],other=i<points.length-1?points[i+1]:points[i-1]||{x:current.x+1,y:current.y},n=perpendicular(current,other),half=widthPx/2;out.push({a:{x:current.x+n.x*half,y:current.y+n.y*half},b:{x:current.x-n.x*half,y:current.y-n.y*half},elevationFt:current.elevationFt,stepIndex:current.stepIndex??i});}return out;}
function railingLines(points=[],widthPx=0){if(points.length<2)return[];const first=points[0],last=points[points.length-1],n=perpendicular(first,last),half=widthPx/2;return[-1,1].map(side=>({side:side<0?'left':'right',from:{x:first.x+n.x*half*side,y:first.y+n.y*half*side},to:{x:last.x+n.x*half*side,y:last.y+n.y*half*side}}));}
function cellForPoint(point={},mapData={}){const size=Math.max(1,finite(mapData.grid?.size,70)),cols=Math.max(1,Math.trunc(finite(mapData.grid?.cols,1))),rows=Math.max(1,Math.trunc(finite(mapData.grid?.rows,1)));return{col:Math.max(0,Math.min(cols-1,Math.floor(finite(point.x)/size))),row:Math.max(0,Math.min(rows-1,Math.floor(finite(point.y)/size)))};}
function geometryFor(raw={},mapData={}){const portal=normalizeStairPortal(raw,mapData);if(!portal||portal.type!=='stairs')return null;const routes=routeRuntime(),route=routes?.routeFor?.(portal,mapData);if(!route?.points?.length)return null;const fpp=feetPerPixel(mapData),widthPx=Math.max(1,finite(portal.widthFt,5)/fpp),points=route.points.map(clone),bounds=boundsForPoints(points,widthPx/2),entry=points[0],exit=points[points.length-1],landDepthPx=Math.max(0,finite(portal.builder?.landingDepthFt,0)/fpp);const landings=[{kind:'entry',center:{x:entry.x,y:entry.y},zLayer:route.fromZ,depthPx:landDepthPx},{kind:'exit',center:{x:exit.x,y:exit.y},zLayer:route.toZ,depthPx:landDepthPx}];return{portal,route,widthPx,footprint:{shape:portal.layout==='ladder'?'circle':'bounds',...bounds},entry:{...entry,cell:cellForPoint(entry,mapData)},exit:{...exit,cell:cellForPoint(exit,mapData)},landings,treads:portal.layout==='straight'?treadLines(points,widthPx):[],recommendedRailings:portal.builder?.railings&&portal.layout==='straight'?railingLines(points,widthPx):[]};}
return Object.freeze({SCHEMA_VERSION,DEFAULT_DEFINITIONS,definitionFor,elevationForLayer,feetPerPixel,vertexPoint,layersOf,normalizeBuilder,normalizeStairPortal,buildPortal,straightStepPoints,boundsForPoints,treadLines,railingLines,cellForPoint,geometryFor});});