(function(root,factory){const api=factory(root);if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.LuminousVttStructureCore=api;})(typeof window!=='undefined'?window:globalThis,function(root){'use strict';
const TYPES=Object.freeze({PILLAR:'pillar',FENCE:'fence',RAILING:'railing',BARRIER:'barrier'});
const COVER=Object.freeze({NONE:'none',PARTIAL:'partial',MAJOR:'major',FULL:'full'});
const DEFAULT_DEFINITIONS=Object.freeze({
 'pillar:concrete':Object.freeze({id:'pillar:concrete',name:'Concrete Pillar',type:'pillar',geometry:'pillar',physical:Object.freeze({heightFt:10,diameterFt:2,thicknessFt:0,blocksMovement:true,blocksVision:true,coverQuality:'major',climbable:false,fallProtection:false}),visual:Object.freeze({color:'#777d82',width:6})}),
 'fence:chain':Object.freeze({id:'fence:chain',name:'Chain Fence',type:'fence',geometry:'edge',physical:Object.freeze({heightFt:6,diameterFt:0,thicknessFt:.2,blocksMovement:true,blocksVision:false,coverQuality:'none',climbable:true,fallProtection:true}),visual:Object.freeze({color:'#96a3aa',width:4,dash:[5,4]})}),
 'railing:metal':Object.freeze({id:'railing:metal',name:'Metal Railing',type:'railing',geometry:'edge',physical:Object.freeze({heightFt:3.5,diameterFt:0,thicknessFt:.15,blocksMovement:true,blocksVision:false,coverQuality:'partial',climbable:false,fallProtection:true}),visual:Object.freeze({color:'#5dff9a',width:5,dash:[10,4]})}),
 'barrier:concrete':Object.freeze({id:'barrier:concrete',name:'Concrete Barrier',type:'barrier',geometry:'edge',physical:Object.freeze({heightFt:3,diameterFt:0,thicknessFt:1.5,blocksMovement:true,blocksVision:false,coverQuality:'major',climbable:true,fallProtection:true}),visual:Object.freeze({color:'#c7b28a',width:8,dash:[]})}),
});
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,clone=v=>v==null?v:JSON.parse(JSON.stringify(v)),clean=v=>String(v??'').trim().toLowerCase();
let boundMapData=null;
function bindMap(mapData){if(mapData&&typeof mapData==='object')boundMapData=mapData;return boundMapData;}
function activeMapData(){return boundMapData;}
function normalizeVertex(v={}){return{col:Math.max(0,Math.trunc(finite(v.col))),row:Math.max(0,Math.trunc(finite(v.row)))};}
function normalizeDefinition(raw={},fallback={}){const type=Object.values(TYPES).includes(raw.type)?raw.type:(Object.values(TYPES).includes(fallback.type)?fallback.type:TYPES.BARRIER);const geometry=type===TYPES.PILLAR?'pillar':'edge';const base=DEFAULT_DEFINITIONS[raw.id]||DEFAULT_DEFINITIONS[fallback.id]||{};const physical={...(base.physical||{}),...(fallback.physical||{}),...(raw.physical||{})};const visual={...(base.visual||{}),...(fallback.visual||{}),...(raw.visual||{})};const cover=Object.values(COVER).includes(clean(physical.coverQuality))?clean(physical.coverQuality):COVER.NONE;return{id:String(raw.id||fallback.id||`${type}:custom`),name:String(raw.name||fallback.name||type),type,geometry,physical:{heightFt:Math.max(0,finite(physical.heightFt,type===TYPES.PILLAR?10:3)),diameterFt:geometry==='pillar'?Math.max(.25,finite(physical.diameterFt,2)):0,thicknessFt:geometry==='edge'?Math.max(.05,finite(physical.thicknessFt,.2)):0,blocksMovement:physical.blocksMovement!==false,blocksVision:physical.blocksVision===true,coverQuality:cover,climbable:physical.climbable===true,fallProtection:physical.fallProtection===true},visual:{color:String(visual.color||'#8b8f93'),width:Math.max(1,finite(visual.width,5)),dash:Array.isArray(visual.dash)?visual.dash.map(Number).filter(Number.isFinite):[]}};}
function normalizeDefinitionCatalog(raw=null){const result={};for(const [id,def] of Object.entries(DEFAULT_DEFINITIONS))result[id]=normalizeDefinition(def,def);if(raw&&typeof raw==='object')for(const [id,value] of Object.entries(raw)){const candidate={...(value||{}),id:String(value?.id||id)};result[candidate.id]=normalizeDefinition(candidate,result[candidate.id]||{});}return result;}
function definitionFor(instance={},mapData=boundMapData||{}){const catalog=mapData.structureDefinitions||normalizeDefinitionCatalog();const id=String(instance.definitionId||'');const direct=catalog[id]||DEFAULT_DEFINITIONS[id];if(direct)return normalizeDefinition(direct,direct);const fallbackId=Object.keys(catalog).find(key=>catalog[key]?.type===instance.type)||Object.keys(DEFAULT_DEFINITIONS).find(key=>DEFAULT_DEFINITIONS[key].type===instance.type);return normalizeDefinition(catalog[fallbackId]||DEFAULT_DEFINITIONS[fallbackId]||{type:instance.type});}
function normalizeInstance(raw={},mapData=boundMapData||{}){const def=definitionFor(raw,mapData);const zLayer=Number.isFinite(Number(raw.zLayer))?Number(raw.zLayer):Number(raw.position?.zLayer??raw.z?.[0]??0)||0;const base={...clone(raw),id:String(raw.id||''),definitionId:String(raw.definitionId||def.id),type:def.type,z:[zLayer],zLayer,elevationOffsetFt:finite(raw.elevationOffsetFt??raw.position?.elevationFt,0)};if(def.geometry==='pillar'){const col=Math.max(0,Math.trunc(finite(raw.position?.col??raw.col))),row=Math.max(0,Math.trunc(finite(raw.position?.row??raw.row)));return{...base,position:{col,row,zLayer,elevationFt:base.elevationOffsetFt}};}return{...base,from:normalizeVertex(raw.from),to:normalizeVertex(raw.to)};}
function ensureMapState(mapData={}){mapData.structureDefinitions=normalizeDefinitionCatalog(mapData.structureDefinitions||null);const list=Array.isArray(mapData.structures)?mapData.structures:[];const normalized=list.map(entry=>normalizeInstance(entry,mapData)).filter(entry=>entry.id);list.splice(0,list.length,...normalized);mapData.structures=list;bindMap(mapData);return mapData;}
function feetPerPixel(mapData={}){return Math.max(.001,finite(mapData.grid?.distancePerCell,5))/Math.max(1,finite(mapData.grid?.size,70));}
function vertexToPoint(v={},grid={}){const size=Math.max(1,finite(grid.size,70)),n=normalizeVertex(v);return{x:n.col*size,y:n.row*size};}
function canonicalEdgeKey(from,to){const a=normalizeVertex(from),b=normalizeVertex(to);const left=a.col<b.col||(a.col===b.col&&a.row<=b.row)?a:b,right=left===a?b:a;return`${left.col},${left.row}-${right.col},${right.row}`;}
function isUnitEdge(from,to){const a=normalizeVertex(from),b=normalizeVertex(to);return Math.abs(a.col-b.col)+Math.abs(a.row-b.row)===1;}
function lineSegment(instance={},mapData={}){const normalized=normalizeInstance(instance,mapData),def=definitionFor(normalized,mapData);if(def.geometry!=='edge')return null;const a=vertexToPoint(normalized.from,mapData.grid||{}),b=vertexToPoint(normalized.to,mapData.grid||{});return{id:normalized.id,type:normalized.type,x1:a.x,y1:a.y,x2:b.x,y2:b.y,z:[normalized.zLayer],zLayer:normalized.zLayer,thicknessFt:def.physical.thicknessFt,thicknessPx:def.physical.thicknessFt/feetPerPixel(mapData),heightFt:def.physical.heightFt,structure:normalized,definition:def};}
function pillarCenter(instance={},mapData={}){const normalized=normalizeInstance(instance,mapData),size=Math.max(1,finite(mapData.grid?.size,70));return{x:(normalized.position.col+.5)*size,y:(normalized.position.row+.5)*size};}
function pillarRadiusPx(instance={},mapData={}){const def=definitionFor(instance,mapData);return(def.physical.diameterFt/2)/feetPerPixel(mapData);}
function pillarRect(instance={},mapData={}){const c=pillarCenter(instance,mapData),r=pillarRadiusPx(instance,mapData);return{x:c.x-r,y:c.y-r,width:r*2,height:r*2};}
function blockingSegments(mapData=boundMapData||{},kind='movement',zLayer=0){if(!mapData)return[];ensureMapState(mapData);const out=[];for(const raw of mapData.structures||[]){const instance=normalizeInstance(raw,mapData);if(Number(instance.zLayer)!==Number(zLayer))continue;const def=definitionFor(instance,mapData),flag=kind==='vision'?'blocksVision':'blocksMovement';if(def.physical[flag]!==true)continue;if(def.geometry==='edge'){const seg=lineSegment(instance,mapData);if(seg)out.push({...seg,blocksMovement:def.physical.blocksMovement,blocksVision:def.physical.blocksVision});continue;}const c=pillarCenter(instance,mapData),r=pillarRadiusPx(instance,mapData);if(kind==='movement'){out.push({id:instance.id,type:'structure_pillar',x1:c.x,y1:c.y,x2:c.x,y2:c.y,z:[instance.zLayer],zLayer:instance.zLayer,thicknessFt:def.physical.diameterFt,thicknessPx:r*2,blocksMovement:true,blocksVision:def.physical.blocksVision,structure:instance,definition:def});}else{const rect=pillarRect(instance,mapData),x1=rect.x,y1=rect.y,x2=rect.x+rect.width,y2=rect.y+rect.height;out.push({id:`${instance.id}:n`,x1,y1,x2,y2:y1,z:[instance.zLayer],zLayer:instance.zLayer,blocksVision:true,structure:instance,definition:def},{id:`${instance.id}:e`,x1:x2,y1,x2,y2,z:[instance.zLayer],zLayer:instance.zLayer,blocksVision:true,structure:instance,definition:def},{id:`${instance.id}:s`,x1:x2,y1:y2,x2:x1,y2,z:[instance.zLayer],zLayer:instance.zLayer,blocksVision:true,structure:instance,definition:def},{id:`${instance.id}:w`,x1,y1:y2,x2:x1,y2:y1,z:[instance.zLayer],zLayer:instance.zLayer,blocksVision:true,structure:instance,definition:def});}}
return out;}
function pointToSegmentDistance(point={},a={},b={}){const px=finite(point.x),py=finite(point.y),ax=finite(a.x),ay=finite(a.y),bx=finite(b.x),by=finite(b.y),dx=bx-ax,dy=by-ay,len2=dx*dx+dy*dy;if(!len2)return Math.hypot(px-ax,py-ay);const t=Math.max(0,Math.min(1,((px-ax)*dx+(py-ay)*dy)/len2));return Math.hypot(px-(ax+dx*t),py-(ay+dy*t));}
function pointInRect(point={},rect={}){return finite(point.x)>=finite(rect.x)&&finite(point.x)<=finite(rect.x)+finite(rect.width)&&finite(point.y)>=finite(rect.y)&&finite(point.y)<=finite(rect.y)+finite(rect.height);}
function hitTest(mapData=boundMapData||{},point={},zLayer=0,tolerancePx=null){ensureMapState(mapData);const tolerance=Math.max(5,finite(tolerancePx,finite(mapData.grid?.size,70)*.18));let best=null,bestDistance=Infinity;for(const instance of mapData.structures||[]){if(Number(instance.zLayer)!==Number(zLayer))continue;const def=definitionFor(instance,mapData);if(def.geometry==='pillar'){const rect=pillarRect(instance,mapData);if(pointInRect(point,rect)){return instance;}const c=pillarCenter(instance,mapData),distance=Math.max(0,Math.hypot(finite(point.x)-c.x,finite(point.y)-c.y)-pillarRadiusPx(instance,mapData));if(distance<=tolerance&&distance<bestDistance){best=instance;bestDistance=distance;}}else{const seg=lineSegment(instance,mapData),distance=pointToSegmentDistance(point,{x:seg.x1,y:seg.y1},{x:seg.x2,y:seg.y2});if(distance<=Math.max(tolerance,seg.thicknessPx/2)&&distance<bestDistance){best=instance;bestDistance=distance;}}}return best;}
function idPart(value){return String(value||'structure').toLowerCase().replace(/[^a-z0-9_-]+/g,'_');}
function createLinearRun({type=TYPES.RAILING,from,to,zLayer=0,definitionId=null,mapData=boundMapData||{}}={}){ensureMapState(mapData);const catalog=mapData.structureDefinitions;const defId=definitionId&&catalog[definitionId]?definitionId:Object.keys(catalog).find(id=>catalog[id].type===type);const a=normalizeVertex(from),b=normalizeVertex(to);if(a.col!==b.col&&a.row!==b.row)return[];const count=Math.abs(b.col-a.col)+Math.abs(b.row-a.row);if(count<1)return[];const dc=Math.sign(b.col-a.col),dr=Math.sign(b.row-a.row),out=[];for(let i=0;i<count;i+=1){const x={col:a.col+dc*i,row:a.row+dr*i},y={col:a.col+dc*(i+1),row:a.row+dr*(i+1)},edge=canonicalEdgeKey(x,y);out.push(normalizeInstance({id:`structure:${idPart(type)}:z${Number(zLayer)||0}:${edge.replace(/[,]/g,'_')}`,type,definitionId:defId,from:x,to:y,zLayer},mapData));}return out;}
function createPillar({col=0,row=0,zLayer=0,definitionId='pillar:concrete',mapData=boundMapData||{}}={}){ensureMapState(mapData);return normalizeInstance({id:`structure:pillar:z${Number(zLayer)||0}:${Math.trunc(finite(col))}_${Math.trunc(finite(row))}`,type:TYPES.PILLAR,definitionId,position:{col,row,zLayer}},mapData);}
function sameLinearSlot(a={},b={}){return a.type!==TYPES.PILLAR&&b.type!==TYPES.PILLAR&&Number(a.zLayer)===Number(b.zLayer)&&canonicalEdgeKey(a.from,a.to)===canonicalEdgeKey(b.from,b.to);}
function reconcileRun(existing=[],incoming=[]){const save=[],skipped=[];for(const next of incoming){const conflict=(existing||[]).find(item=>sameLinearSlot(normalizeInstance(item,boundMapData||{}),next));if(conflict)skipped.push({structure:next,reason:'STRUCTURE_EDGE_OCCUPIED',conflictId:conflict.id});else save.push(next);}return{save,skipped};}
function structuresOnLayer(mapData=boundMapData||{},zLayer=0){ensureMapState(mapData);return(mapData.structures||[]).filter(item=>Number(item.zLayer)===Number(zLayer));}
function fallProtectionSegments(mapData=boundMapData||{},zLayer=0){return structuresOnLayer(mapData,zLayer).flatMap(instance=>{const def=definitionFor(instance,mapData);if(!def.physical.fallProtection||def.geometry!=='edge')return[];const seg=lineSegment(instance,mapData);return seg?[seg]:[];});}
return Object.freeze({TYPES,COVER,DEFAULT_DEFINITIONS,bindMap,activeMapData,normalizeVertex,normalizeDefinition,normalizeDefinitionCatalog,definitionFor,normalizeInstance,ensureMapState,feetPerPixel,vertexToPoint,canonicalEdgeKey,isUnitEdge,lineSegment,pillarCenter,pillarRadiusPx,pillarRect,blockingSegments,pointToSegmentDistance,pointInRect,hitTest,createLinearRun,createPillar,sameLinearSlot,reconcileRun,structuresOnLayer,fallProtectionSegments});});